<?php
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$bytes=static function(float $v):string{foreach(['B','KB','MB','GB','TB','PB'] as $u){if(abs($v)<1024)return number_format($v,$v<10?1:0).' '.$u;$v/=1024;}return number_format($v,1).' EB';};
$rate=static fn($v)=>$bytes((float)$v).'/s';
$age=static function($date):string{if(!$date)return 'Nunca';$s=max(0,time()-strtotime((string)$date));return $s<60?'Ahora':($s<3600?intdiv($s,60).' min':intdiv($s,3600).' h');};
$health=max(0,100-($stats['servers_problem']*20)-($stats['security_alerts']*10)-min(30,$stats['stream_errors']));
?>
<div class="space-y-6" x-data="{refreshing:false}" x-init="setTimeout(()=>{if(!document.hidden)location.reload()},30000)">
 <header class="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><div class="flex items-center gap-3"><h1 class="text-3xl font-bold">Centro de operaciones</h1><span class="px-2 py-1 rounded-full text-xs <?=$health>=90?'bg-emerald-500/20 text-emerald-300':($health>=70?'bg-amber-500/20 text-amber-300':'bg-red-500/20 text-red-300')?>">Salud <?=$health?>%</span></div><p class="text-slate-400 mt-1">Visión en tiempo real de OrionX · actualización automática cada 30 segundos</p></div><div class="flex gap-2"><a href="/libraries" class="bg-slate-800 border border-slate-700 px-4 py-2 rounded-lg">Escanear contenido</a><a href="/servers" class="bg-cyan-600 hover:bg-cyan-500 px-4 py-2 rounded-lg">Gestionar servidores</a></div></header>
 <section class="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-3">
  <?php $realtime=[
   ['Usuarios conectados',$stats['connected_users'],number_format($stats['connections']).' conexiones','bg-emerald-500','U'],
   ['Canales viéndose',$stats['watching_live'],number_format($stats['live_viewers']).' espectadores','bg-cyan-500','TV'],
   ['Películas viéndose',$stats['watching_movies'],number_format($stats['movie_viewers']).' espectadores','bg-violet-500','VOD'],
   ['Series viéndose',$stats['watching_series'],number_format($stats['series_viewers']).' espectadores','bg-fuchsia-500','SER'],
   ['Descarga total',$rate($metrics['network_rx_bps']??0),'Todos los servidores','bg-blue-500','↓'],
   ['Subida total',$rate($metrics['network_tx_bps']??0),'Todos los servidores','bg-amber-500','↑'],
  ];foreach($realtime as [$label,$value,$sub,$color,$icon]):?>
  <article class="relative overflow-hidden bg-slate-900 border border-slate-800 rounded-2xl p-4 min-h-32"><i class="absolute left-0 top-0 bottom-0 w-1 <?=$color?>"></i><div class="flex items-center justify-between"><span class="text-xs text-slate-400"><?=$label?></span><span class="text-[10px] font-bold rounded-md bg-slate-800 px-2 py-1"><?=$icon?></span></div><strong class="block text-2xl xl:text-3xl mt-4 truncate"><?=is_numeric($value)?number_format((float)$value):$value?></strong><span class="text-xs text-slate-500"><?=$sub?></span></article><?php endforeach?>
 </section>
 <section class="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">
  <?php $hero=[['Conexiones ahora',$stats['connections'],'↯','from-violet-600 to-indigo-700','Sesiones autorizadas'],['Usuarios activos',$stats['active_users'],'♙','from-emerald-500 to-teal-700',number_format($stats['expired_users']).' expirados'],['Streams disponibles',$stats['active_streams'],'▶','from-cyan-500 to-blue-700',number_format($stats['stream_errors']).' con fallos'],['Tareas en curso',$stats['pending_jobs'],'⚙','from-amber-500 to-orange-700',number_format($stats['security_alerts']).' alertas críticas']];foreach($hero as [$label,$value,$icon,$color,$sub]):?>
  <article class="relative overflow-hidden rounded-2xl bg-gradient-to-br <?=$color?> p-5 shadow-lg"><div class="absolute -right-8 -top-8 w-32 h-32 rounded-full bg-white/10"></div><div class="flex justify-between items-start"><span class="grid place-items-center w-11 h-11 rounded-xl bg-white/15 text-2xl"><?=$icon?></span><span class="w-2 h-2 rounded-full bg-white animate-pulse"></span></div><strong class="block text-3xl mt-5"><?=number_format($value)?></strong><div class="font-medium"><?=$label?></div><div class="text-xs text-white/70 mt-1"><?=$sub?></div></article><?php endforeach?>
 </section>
 <section class="grid lg:grid-cols-3 gap-4">
  <article class="lg:col-span-2 bg-slate-900 border border-slate-800 rounded-2xl p-5"><div class="flex justify-between"><div><h2 class="font-bold text-lg">Rendimiento del clúster</h2><p class="text-sm text-slate-400">Promedio de los últimos reportes de cada nodo</p></div><span class="text-xs text-slate-500"><?=count($servers)?> nodos</span></div><div class="grid sm:grid-cols-3 gap-6 mt-6"><?php foreach(['cpu'=>'CPU','ram'=>'Memoria','disk'=>'Disco'] as $key=>$label):$v=min(100,max(0,(float)($metrics[$key]??0)));?><div><div class="flex justify-between text-sm"><span><?=$label?></span><strong><?=number_format($v,1)?>%</strong></div><div class="h-3 bg-slate-800 rounded-full mt-2 overflow-hidden"><div class="h-full rounded-full <?=$v>=90?'bg-red-500':($v>=75?'bg-amber-500':'bg-cyan-500')?>" style="width:<?=$v?>%"></div></div></div><?php endforeach?></div><div class="grid sm:grid-cols-3 gap-3 mt-6"><div class="bg-slate-800/60 rounded-xl p-4"><span class="text-xs text-slate-400">Entrada de red</span><strong class="block text-xl text-emerald-400"><?=$rate($metrics['network_rx_bps']??0)?></strong></div><div class="bg-slate-800/60 rounded-xl p-4"><span class="text-xs text-slate-400">Salida de red</span><strong class="block text-xl text-cyan-400"><?=$rate($metrics['network_tx_bps']??0)?></strong></div><div class="bg-slate-800/60 rounded-xl p-4"><span class="text-xs text-slate-400">Contenido validado</span><strong class="block text-xl"><?=$bytes($stats['storage_bytes'])?></strong></div></div></article>
  <article class="bg-slate-900 border border-slate-800 rounded-2xl p-5"><h2 class="font-bold text-lg">Catálogo</h2><div class="space-y-4 mt-5"><?php foreach([['Películas',$stats['movies'],'/movies','bg-violet-500'],['Series',$stats['series'],'/libraries','bg-cyan-500'],['Episodios',$stats['episodes'],'/libraries','bg-emerald-500'],['Revendedores',$stats['resellers'],'/resellers','bg-amber-500']] as [$label,$value,$url,$color]):?><a href="<?=$url?>" class="flex items-center justify-between group"><span class="flex items-center gap-3"><i class="w-2 h-8 rounded <?=$color?>"></i><?=$label?></span><strong class="text-xl group-hover:text-cyan-400"><?=number_format($value)?></strong></a><?php endforeach?></div></article>
 </section>
 <section><div class="flex items-end justify-between mb-3"><div><h2 class="text-xl font-bold">Infraestructura</h2><p class="text-sm text-slate-400">Estado y carga actual por servidor</p></div><a href="/deployments" class="text-cyan-400 text-sm">Instalar o actualizar →</a></div><div class="grid xl:grid-cols-2 gap-4">
 <?php foreach($servers as $s):$stale=!$s['last_heartbeat_at']||strtotime($s['last_heartbeat_at'])<time()-90;$bad=$stale||in_array($s['status'],['offline','quarantined'],true);?>
  <article class="bg-slate-900 border <?=$bad?'border-red-800':'border-slate-800'?> rounded-2xl overflow-hidden"><div class="p-4 flex justify-between items-start <?=$bad?'bg-red-950/40':'bg-gradient-to-r from-slate-800 to-slate-900'?>"><div><div class="flex items-center gap-2"><span class="w-2.5 h-2.5 rounded-full <?=$bad?'bg-red-500':($s['status']==='degraded'?'bg-amber-400':'bg-emerald-400')?>"></span><h3 class="font-bold"><?=$e($s['name'])?></h3></div><p class="text-xs text-slate-400 mt-1"><?=$e($s['region']?:'Sin región')?> · v<?=$e($s['installed_version']?:'pendiente')?></p></div><div class="text-right"><span class="uppercase text-xs <?=$bad?'text-red-400':'text-emerald-400'?>"><?=$stale?'sin heartbeat':$e($s['status'])?></span><div class="text-xs text-slate-500"><?=$age($s['last_heartbeat_at'])?></div></div></div><div class="p-4"><div class="grid grid-cols-3 gap-3 text-center"><div><strong class="text-xl"><?=number_format($s['active_sessions'])?></strong><div class="text-xs text-slate-500">Conexiones</div></div><div><strong class="text-xl"><?=number_format($s['connected_users'])?></strong><div class="text-xs text-slate-500">Usuarios</div></div><div><strong class="text-xl"><?=number_format($s['active_streams'])?></strong><div class="text-xs text-slate-500">Streams</div></div></div><div class="grid sm:grid-cols-3 gap-3 mt-5"><?php foreach(['cpu'=>'CPU','ram'=>'RAM','disk'=>'Disco'] as $key=>$label):$v=min(100,max(0,(float)$s[$key]));?><div><div class="flex justify-between text-xs"><span><?=$label?></span><span><?=number_format($v)?>%</span></div><div class="h-1.5 bg-slate-800 rounded mt-1"><div class="h-full rounded <?=$v>=90?'bg-red-500':($v>=75?'bg-amber-400':'bg-emerald-500')?>" style="width:<?=$v?>%"></div></div></div><?php endforeach?></div><div class="flex justify-between mt-4 text-xs text-slate-400"><span>↓ <?=$rate($s['network_rx_bps'])?></span><span>↑ <?=$rate($s['network_tx_bps'])?></span><span>Agente <?=$e($s['agent_status'])?></span></div><?php if($s['quarantined_reason']):?><div class="mt-3 p-2 rounded bg-red-950 text-red-300 text-xs"><?=$e($s['quarantined_reason'])?></div><?php endif?></div></article>
 <?php endforeach?><?php if(!$servers):?><div class="xl:col-span-2 border border-dashed border-slate-700 rounded-2xl p-10 text-center text-slate-400">Todavía no hay balanceadores registrados. <a class="text-cyan-400" href="/servers">Añadir servidor</a></div><?php endif?></div></section>
 <section class="grid lg:grid-cols-3 gap-4">
  <article class="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div class="flex justify-between"><h2 class="font-bold">Alertas abiertas</h2><a href="/logs" class="text-xs text-cyan-400">Ver logs</a></div><div class="mt-3 space-y-2"><?php foreach($alerts as $a):?><div class="p-3 rounded-lg <?=$a['severity']==='critical'?'bg-red-950/50 border border-red-900':'bg-amber-950/30 border border-amber-900/50'?>"><div class="flex justify-between"><strong class="text-sm"><?=$e($a['title'])?></strong><span class="text-xs"><?=$e($a['severity'])?></span></div><p class="text-xs text-slate-400 mt-1"><?=$e($a['message'])?></p></div><?php endforeach?><?php if(!$alerts):?><p class="text-emerald-400 py-8 text-center">✓ Sin alertas abiertas</p><?php endif?></div></article>
  <article class="bg-slate-900 border border-slate-800 rounded-2xl p-5"><h2 class="font-bold">Tareas</h2><div class="mt-3 space-y-3"><?php foreach($jobs as $j):?><div><div class="flex justify-between text-sm"><span class="truncate mr-3"><?=$e(str_replace('_',' ',$j['type']))?></span><span class="<?=$j['status']==='failed'?'text-red-400':'text-slate-400'?>"><?=$e($j['status'])?> · <?=$j['progress']?>%</span></div><div class="h-1.5 bg-slate-800 rounded mt-1"><div class="h-full <?=$j['status']==='failed'?'bg-red-500':'bg-cyan-500'?>" style="width:<?=$j['progress']?>%"></div></div></div><?php endforeach?><?php if(!$jobs):?><p class="text-slate-500 py-8 text-center">No hay tareas pendientes</p><?php endif?></div></article>
  <article class="bg-slate-900 border border-slate-800 rounded-2xl p-5"><h2 class="font-bold">Actividad reciente</h2><div class="mt-3 relative before:absolute before:left-1.5 before:top-2 before:bottom-2 before:w-px before:bg-slate-700"><?php foreach($events as $event):?><div class="relative pl-6 pb-4"><i class="absolute left-0 top-1 w-3 h-3 rounded-full bg-cyan-500 ring-4 ring-slate-900"></i><div class="text-sm"><?=$e(str_replace(['.','_'],' ',$event['action']))?></div><div class="text-xs text-slate-500"><?=$e($event['entity_type'])?> #<?=$e($event['entity_id'])?> · <?=$age($event['created_at'])?></div></div><?php endforeach?></div></article>
 </section>
</div>
