<?php $e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$f=$filters??[];?>
<div x-data="{selected:[],all:false,toggleAll(){this.selected=this.all?[...document.querySelectorAll('[data-media-id]')].map(x=>x.value):[]}}" class="space-y-5">
 <div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-3xl font-bold">Edición masiva de VOD</h1><p class="text-slate-400">Modifica películas y episodios seleccionados en una sola operación auditada.</p></div><a href="/movies" class="bg-slate-700 px-4 py-2 rounded self-start">Volver a películas</a></div>
 <?php if((int)($f['updated']??0)>0):?><div class="bg-emerald-950 border border-emerald-700 text-emerald-300 rounded-xl p-4"><?=number_format((int)$f['updated'])?> elementos actualizados correctamente.</div><?php endif?>
 <form method="get" class="grid md:grid-cols-5 gap-3 bg-slate-900 border border-slate-800 rounded-xl p-4"><input name="search" value="<?=$e($f['search']??'')?>" placeholder="Buscar título o ID" class="md:col-span-2 bg-slate-800 p-2 rounded"><select name="type" class="bg-slate-800 p-2 rounded"><option value="">Películas y episodios</option><option value="movie" <?=($f['type']??'')==='movie'?'selected':''?>>Solo películas</option><option value="episode" <?=($f['type']??'')==='episode'?'selected':''?>>Solo episodios</option></select><select name="status" class="bg-slate-800 p-2 rounded"><option value="">Todos los estados</option><?php foreach(['draft'=>'Borrador','active'=>'Activo','disabled'=>'Deshabilitado','missing'=>'Archivo faltante'] as $v=>$l):?><option value="<?=$v?>" <?=($f['status']??'')===$v?'selected':''?>><?=$l?></option><?php endforeach?></select><button class="bg-cyan-700 rounded p-2">Filtrar</button></form>
 <form method="post" action="/media/bulk" onsubmit="return this.querySelectorAll('[name=\'ids[]\']:checked').length>0&&confirm('¿Aplicar estos cambios a todos los elementos seleccionados?')" class="space-y-4"><?=$csrf->field()?>
  <section class="bg-slate-900 border border-slate-800 rounded-xl p-4"><div class="flex justify-between mb-4"><strong><span x-text="selected.length"></span> seleccionados</strong><span class="text-xs text-slate-500">Máximo 500 por operación</span></div><div class="grid md:grid-cols-5 gap-3"><select name="set_status" class="bg-slate-800 p-2 rounded"><option value="">No cambiar estado</option><option value="active">Publicar / activar</option><option value="draft">Dejar en borrador</option><option value="disabled">Deshabilitar</option><option value="missing">Marcar faltante</option></select><select name="set_category" class="bg-slate-800 p-2 rounded"><option value="">No cambiar categoría</option><option value="0">Quitar categoría</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>"><?=$c['type']==='movie'?'Película':'Serie'?> · <?=$e($c['name'])?></option><?php endforeach?></select><select name="set_server" class="bg-slate-800 p-2 rounded"><option value="">No cambiar servidor</option><option value="0">Usar servidor de biblioteca</option><?php foreach($servers as $s):?><option value="<?=$s['id']?>"><?=$e($s['name'])?></option><?php endforeach?></select><div class="flex gap-2"><select name="package_action" class="w-1/3 bg-slate-800 p-2 rounded"><option value="add">Añadir</option><option value="remove">Quitar</option></select><select name="package_id" class="w-2/3 bg-slate-800 p-2 rounded"><option value="">Package…</option><?php foreach($packages as $p):?><option value="<?=$p['id']?>"><?=$e($p['name'])?></option><?php endforeach?></select></div><button :disabled="selected.length===0" class="bg-indigo-700 disabled:opacity-40 rounded p-2 font-bold">Aplicar cambios</button></div></section>
  <div class="overflow-x-auto bg-slate-900 border border-slate-800 rounded-xl"><table class="w-full min-w-[1000px] text-sm"><thead><tr class="text-left text-xs uppercase text-slate-400"><th class="p-3"><input type="checkbox" x-model="all" @change="toggleAll()"></th><th>ID</th><th>Tipo</th><th>Título</th><th>Serie / episodio</th><th>Categoría</th><th>Servidor</th><th>Estado</th><th>TMDB</th></tr></thead><tbody><?php foreach($items as $item):?><tr class="border-t border-slate-800 odd:bg-slate-800/30"><td class="p-3"><input data-media-id type="checkbox" name="ids[]" value="<?=$item['id']?>" x-model="selected"></td><td><?=$item['id']?></td><td><span class="px-2 py-1 rounded <?=$item['type']==='movie'?'bg-violet-700':'bg-fuchsia-700'?>"><?=$item['type']==='movie'?'Película':'Episodio'?></span></td><td class="font-semibold"><?=$e($item['title'])?></td><td class="text-slate-400"><?=$item['type']==='episode'?$e(($item['series_title']??'Serie').' · S'.str_pad((string)$item['season_number'],2,'0',STR_PAD_LEFT).'E'.str_pad((string)$item['episode_number'],2,'0',STR_PAD_LEFT)):'—'?></td><td><?=$e($item['category_name']??'Sin categoría')?></td><td><?=$e($item['server_name']??'Biblioteca/principal')?></td><td><span class="<?=$item['status']==='active'?'text-emerald-400':($item['status']==='missing'?'text-red-400':'text-amber-400')?>"><?=$e($item['status'])?></span></td><td><?=$item['tmdb_id']?'✓ '.$item['tmdb_id']:'—'?></td></tr><?php endforeach?><?php if(!$items):?><tr><td colspan="9" class="p-8 text-center text-slate-500">No hay contenido que coincida con los filtros.</td></tr><?php endif?></tbody></table></div>
 </form>
</div>
