<?php $e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$f=$filters??[];?>
<div x-data="{selected:[],all:false,confirmation:'',toggleAll(){this.selected=this.all?[...document.querySelectorAll('[data-media-id]')].map(x=>x.value):[]}}" class="space-y-5">
 <div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-3xl font-bold text-red-400">Eliminación masiva de VOD</h1><p class="text-slate-400">Retira películas y episodios del catálogo sin borrar sus archivos físicos.</p></div><a href="/media/bulk" class="bg-slate-700 px-4 py-2 rounded self-start">Edición masiva</a></div>
 <?php if((int)($f['deleted']??0)>0):?><div class="bg-red-950 border border-red-700 text-red-200 rounded-xl p-4"><?=number_format((int)$f['deleted'])?> elementos eliminados del catálogo.</div><?php endif?>
 <div class="bg-amber-950/50 border border-amber-700 rounded-xl p-4 text-amber-200"><strong>Protección:</strong> no se eliminarán archivos de los discos ni contenidos con sesiones activas. Esta acción sí elimina metadatos, asignaciones, análisis y relaciones del catálogo.</div>
 <form method="get" class="grid md:grid-cols-5 gap-3 bg-slate-900 border border-slate-800 rounded-xl p-4"><input name="search" value="<?=$e($f['search']??'')?>" placeholder="Buscar título o ID" class="md:col-span-2 bg-slate-800 p-2 rounded"><select name="type" class="bg-slate-800 p-2 rounded"><option value="">Películas y episodios</option><option value="movie" <?=($f['type']??'')==='movie'?'selected':''?>>Solo películas</option><option value="episode" <?=($f['type']??'')==='episode'?'selected':''?>>Solo episodios</option></select><select name="status" class="bg-slate-800 p-2 rounded"><option value="">Todos los estados</option><?php foreach(['draft'=>'Borrador','active'=>'Activo','disabled'=>'Deshabilitado','missing'=>'Archivo faltante'] as $v=>$l):?><option value="<?=$v?>" <?=($f['status']??'')===$v?'selected':''?>><?=$l?></option><?php endforeach?></select><button class="bg-cyan-700 rounded p-2">Filtrar</button></form>
 <form method="post" action="/media/delete" onsubmit="return confirm('Esta acción elimina definitivamente los registros seleccionados del catálogo. ¿Continuar?')" class="space-y-4"><?=$csrf->field()?>
  <section class="bg-red-950/40 border border-red-800 rounded-xl p-4"><div class="grid md:grid-cols-[1fr_300px_220px] gap-3 items-end"><div><strong class="text-red-300"><span x-text="selected.length"></span> seleccionados</strong><p class="text-xs text-slate-400">Máximo 500 por operación.</p></div><label class="text-sm">Escribe ELIMINAR<input name="confirmation" x-model="confirmation" autocomplete="off" class="mt-1 w-full bg-slate-900 border border-red-800 p-2 rounded" placeholder="ELIMINAR"></label><button :disabled="selected.length===0||confirmation!=='ELIMINAR'" class="bg-red-700 hover:bg-red-600 disabled:opacity-40 rounded p-2 font-bold">Eliminar seleccionados</button></div></section>
  <div class="overflow-x-auto bg-slate-900 border border-slate-800 rounded-xl"><table class="w-full min-w-[900px] text-sm"><thead><tr class="text-left text-xs uppercase text-slate-400"><th class="p-3"><input type="checkbox" x-model="all" @change="toggleAll()"></th><th>ID</th><th>Tipo</th><th>Título</th><th>Serie / episodio</th><th>Categoría</th><th>Servidor</th><th>Estado</th></tr></thead><tbody><?php foreach($items as $item):?><tr class="border-t border-slate-800 odd:bg-slate-800/30"><td class="p-3"><input data-media-id type="checkbox" name="ids[]" value="<?=$item['id']?>" x-model="selected"></td><td><?=$item['id']?></td><td><?=$item['type']==='movie'?'Película':'Episodio'?></td><td class="font-semibold"><?=$e($item['title'])?></td><td class="text-slate-400"><?=$item['type']==='episode'?$e(($item['series_title']??'Serie').' · S'.str_pad((string)$item['season_number'],2,'0',STR_PAD_LEFT).'E'.str_pad((string)$item['episode_number'],2,'0',STR_PAD_LEFT)):'—'?></td><td><?=$e($item['category_name']??'Sin categoría')?></td><td><?=$e($item['server_name']??'Biblioteca/principal')?></td><td class="<?=$item['status']==='active'?'text-emerald-400':($item['status']==='missing'?'text-red-400':'text-amber-400')?>"><?=$e($item['status'])?></td></tr><?php endforeach?><?php if(!$items):?><tr><td colspan="8" class="p-8 text-center text-slate-500">No hay contenido que coincida con los filtros.</td></tr><?php endif?></tbody></table></div>
 </form>
</div>
