<?php $e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$query=static function(array $changes)use($filters){return http_build_query(array_filter(array_merge($filters,$changes),static fn($v)=>$v!==''&&$v!==null));};?>
<div x-data="movieWizard()" class="space-y-5">
 <div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">Películas</h1><p class="text-slate-400"><?=number_format($pagination['total'])?> títulos registrados</p></div><div class="flex gap-2"><a href="/sessions?type=movie" class="bg-violet-800 px-4 py-2 rounded">Clientes y países</a><a href="/sessions?type=episode" class="bg-fuchsia-800 px-4 py-2 rounded">Episodios activos</a><a href="/libraries" class="bg-slate-800 px-4 py-2 rounded">Importar carpeta</a><button @click="open=!open" class="bg-cyan-600 px-4 py-2 rounded">Añadir película</button></div></div>
 <form method="get" class="bg-slate-900 border border-slate-800 rounded-xl p-4 grid md:grid-cols-4 xl:grid-cols-8 gap-3">
  <input name="search" value="<?=$e($filters['search']??'')?>" placeholder="Buscar películas..." class="xl:col-span-2 bg-slate-800 p-2 rounded">
  <select name="server_id" class="bg-slate-800 p-2 rounded"><option value="">Todos los servidores</option><?php foreach($servers as $s):?><option value="<?=$s['id']?>" <?=((int)($filters['server_id']??0)===(int)$s['id'])?'selected':''?>><?=$e($s['name'])?></option><?php endforeach?></select>
  <select name="category_id" class="bg-slate-800 p-2 rounded"><option value="">Todas las categorías</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=((int)($filters['category_id']??0)===(int)$c['id'])?'selected':''?>><?=$e($c['name'])?></option><?php endforeach?></select>
  <select name="status" class="bg-slate-800 p-2 rounded"><option value="">Cualquier estado</option><?php foreach(['active'=>'Publicado','draft'=>'Borrador','disabled'=>'Desactivado','missing'=>'Faltante'] as $v=>$n):?><option value="<?=$v?>" <?=($filters['status']??'')===$v?'selected':''?>><?=$n?></option><?php endforeach?></select>
  <select name="tmdb" class="bg-slate-800 p-2 rounded"><option value="">TMDB: todos</option><option value="yes" <?=($filters['tmdb']??'')==='yes'?'selected':''?>>Con TMDB</option><option value="no" <?=($filters['tmdb']??'')==='no'?'selected':''?>>Sin TMDB</option></select>
  <select name="video" class="bg-slate-800 p-2 rounded"><option value="">Vídeo</option><?php foreach(['h264','hevc','av1','mpeg4'] as $v):?><option <?=($filters['video']??'')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select>
  <select name="audio" class="bg-slate-800 p-2 rounded"><option value="">Audio</option><?php foreach(['aac','ac3','eac3','mp3','opus'] as $v):?><option <?=($filters['audio']??'')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select>
  <select name="quality" class="bg-slate-800 p-2 rounded"><option value="">Calidad</option><?php foreach([720=>'720p+',1080=>'1080p+',2160=>'4K'] as $v=>$n):?><option value="<?=$v?>" <?=((int)($filters['quality']??0)===$v)?'selected':''?>><?=$n?></option><?php endforeach?></select>
  <select name="per_page" class="bg-slate-800 p-2 rounded"><?php foreach([25,50,100,200] as $v):?><option value="<?=$v?>" <?=$pagination['per_page']===$v?'selected':''?>><?=$v?> por página</option><?php endforeach?></select><button class="bg-cyan-700 p-2 rounded">Aplicar filtros</button><a href="/movies" class="text-center bg-slate-700 p-2 rounded">Limpiar</a>
 </form>
 <div class="bg-slate-900 border border-slate-800 rounded-xl overflow-x-auto"><table class="w-full min-w-[1200px] text-sm"><thead class="text-left text-slate-400 uppercase text-xs"><tr><th class="p-4">ID</th><th>Imagen</th><th>Nombre</th><th>Servidor</th><th>Clientes</th><th>Estado</th><th>TMDB</th><th>Acciones</th><th>Player</th><th class="pr-4">Información del stream</th></tr></thead><tbody>
 <?php foreach($movies as $m):$duration=(int)round((float)($m['probe_duration']?:$m['duration_seconds']));$bitrate=(int)round(((int)$m['bit_rate'])/1000);?>
  <tr class="odd:bg-slate-800/45 border-t border-slate-800 hover:bg-slate-800"><td class="p-4 text-slate-400"><?=$m['id']?></td><td><?php if($m['poster_url']):?><img loading="lazy" src="<?=$e($m['poster_url'])?>" class="w-11 h-16 object-cover rounded" alt=""><?php else:?><div class="w-11 h-16 bg-slate-700 rounded grid place-items-center">🎬</div><?php endif?></td><td class="py-3"><strong><?=$e($m['title'])?></strong><div class="text-xs"><span><?=$e($m['release_year']??'')?></span> <span class="text-amber-400"><?=str_repeat('★',max(0,min(5,(int)round(((float)$m['rating'])/2))))?></span></div><div class="text-xs text-cyan-400 uppercase"><?=$e($m['category_name']??'Sin categoría')?></div></td><td><?=$e($m['server_name']??'Principal')?><div class="text-xs text-slate-500"><?=$e($m['library_name']??'')?></div></td><td><span class="inline-grid place-items-center min-w-7 h-7 bg-cyan-600 rounded"><?=(int)$m['clients']?></span></td><td><span title="<?=$e($m['file_status']??'')?>" class="inline-grid place-items-center w-8 h-8 rounded <?=$m['status']==='active'&&$m['file_status']==='available'?'bg-emerald-600':'bg-amber-600'?>"><?=$m['status']==='active'&&$m['file_status']==='available'?'✓':'!'?></span></td><td><span class="inline-grid place-items-center w-8 h-8 rounded <?=$m['tmdb_id']?'bg-emerald-600':'bg-slate-700'?>"><?=$m['tmdb_id']?'✓':'—'?></span></td><td><div class="flex"><button title="Ver archivo" class="bg-slate-700 px-3 py-2">▣</button><button title="Revalidar" onclick="location.href='/libraries'" class="bg-slate-700 px-3 py-2">↻</button><button title="Editar" @click="open=true;tab=1" class="bg-slate-700 px-3 py-2">✎</button></div></td><td><button type="button" @click="preview={title:<?=json_encode($m['title'])?>,poster:<?=json_encode($m['poster_url'])?>,trailer:''}" class="w-9 h-9 rounded <?=$m['file_status']==='available'?'bg-cyan-600':'bg-slate-700'?>">▶</button></td><td class="pr-4 text-xs"><div><?=$bitrate?number_format($bitrate).' Kbps':'Pendiente de análisis'?></div><div class="flex gap-4 text-slate-400"><span><?=$e(($m['width']&&$m['height'])?$m['width'].' × '.$m['height']:'—')?></span><span><?=$e($m['video_codec']??'—')?></span><span><?=$e($m['audio_codec']??'—')?></span><span><?=$duration?sprintf('%02d:%02d',intdiv($duration,60),$duration%60):'—'?></span></div></td></tr>
 <?php endforeach?><?php if(!$movies):?><tr><td colspan="10" class="p-12 text-center text-slate-400">No hay películas que coincidan con estos filtros.</td></tr><?php endif?></tbody></table></div>
 <div class="flex justify-between items-center"><span class="text-slate-400">Página <?=$pagination['page']?> de <?=$pagination['pages']?></span><div class="flex gap-2"><?php if($pagination['page']>1):?><a class="bg-slate-800 px-4 py-2 rounded" href="/movies?<?=$query(['page'=>$pagination['page']-1])?>">Anterior</a><?php endif?><?php if($pagination['page']<$pagination['pages']):?><a class="bg-slate-800 px-4 py-2 rounded" href="/movies?<?=$query(['page'=>$pagination['page']+1])?>">Siguiente</a><?php endif?></div></div>
 <div x-show="preview" x-cloak style="display:none" class="relative bg-black/80 z-50 grid place-items-center p-4" @click.self="preview=null"><div class="bg-slate-900 rounded-xl p-5 max-w-lg w-full"><button @click="preview=null" class="float-right">✕</button><h2 class="text-xl font-bold" x-text="preview?.title"></h2><img :src="preview?.poster" class="max-h-[65vh] mx-auto mt-4 rounded" alt=""><p class="text-slate-400 mt-3">La reproducción del archivo original exige una sesión autorizada; esta vista no expone rutas físicas.</p></div></div>
 <form x-show="open" x-cloak method="post" action="/movies" class="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden"><?=$csrf->field()?><div class="grid grid-cols-4 bg-slate-800"><?php foreach(['Detalles','Información','Avanzado','Servidor'] as $n=>$label):?><button type="button" @click="tab=<?=$n+1?>" :class="tab===<?=$n+1?>?'bg-cyan-700':''" class="p-3"><?=$label?></button><?php endforeach?></div>
  <section x-show="tab===1" class="p-6 grid md:grid-cols-3 gap-4"><label class="md:col-span-2">Nombre<input x-model="title" required name="title" class="w-full bg-slate-800 p-2 rounded mt-1"></label><label>Año<input x-model="year" type="number" name="year" class="w-full bg-slate-800 p-2 rounded mt-1"></label><label>Idioma TMDB<select x-model="language" name="tmdb_language" class="w-full bg-slate-800 p-2 rounded mt-1"><option>es-ES</option><option>en-US</option></select></label><button type="button" @click="searchTmdb" class="self-end bg-indigo-700 p-2 rounded">Buscar en TMDB</button><span x-text="tmdbError" class="text-red-400"></span><div class="md:col-span-3 grid md:grid-cols-3 gap-3"><template x-for="m in results" :key="m.id"><button type="button" @click="selectTmdb(m)" class="text-left border border-slate-700 rounded p-3"><strong x-text="m.title"></strong><div x-text="(m.release_date||'').slice(0,4)"></div></button></template></div><input type="hidden" name="tmdb_id" :value="tmdbId"><label>Categoría<select name="category_id" class="w-full bg-slate-800 p-2 rounded mt-1"><option value="">Sin categoría</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>"><?=$e($c['name'])?></option><?php endforeach?></select></label><label class="md:col-span-2">Paquetes<select multiple name="package_ids[]" class="w-full bg-slate-800 p-2 rounded mt-1"><?php foreach($packages as $p):?><option value="<?=$p['id']?>"><?=$e($p['name'])?></option><?php endforeach?></select></label><button type="button" @click="tab=2" class="md:col-start-3 bg-cyan-700 p-2 rounded">Siguiente</button></section>
  <section x-show="tab===2" class="p-6 grid md:grid-cols-2 gap-4"><label>Título original<input name="original_title" class="w-full bg-slate-800 p-2 rounded"></label><label>Póster URL<input x-model="poster" name="poster_url" class="w-full bg-slate-800 p-2 rounded"></label><label>Backdrop URL<input x-model="backdrop" name="backdrop_url" class="w-full bg-slate-800 p-2 rounded"></label><label>Director<input name="director" class="w-full bg-slate-800 p-2 rounded"></label><label class="md:col-span-2">Descripción<textarea x-model="plot" name="description" class="w-full h-28 bg-slate-800 p-2 rounded"></textarea></label><label>Reparto<input name="cast" class="w-full bg-slate-800 p-2 rounded"></label><label>Géneros<input name="genres" class="w-full bg-slate-800 p-2 rounded"></label><button type="button" @click="tab=3" class="md:col-start-2 bg-cyan-700 p-2 rounded">Siguiente</button></section>
  <section x-show="tab===3" class="p-6 grid md:grid-cols-2 gap-4"><?php foreach(['direct_source'=>'Fuente directa','direct_stream'=>'Stream directo','native_frames'=>'Frames nativos','create_symlink'=>'Crear symlink','remove_subtitles'=>'Eliminar subtítulos','process_movie'=>'Procesar película'] as $name=>$label):?><label class="flex justify-between bg-slate-800 p-3 rounded"><?=$label?><input type="checkbox" name="<?=$name?>" value="1"></label><?php endforeach?><label>Contenedor<select name="target_container" class="w-full bg-slate-800 p-2 rounded"><option value="">Original</option><option>mp4</option><option>mkv</option><option>ts</option></select></label><button type="button" @click="tab=4" class="bg-cyan-700 p-2 rounded">Siguiente</button></section>
  <section x-show="tab===4" class="p-6 space-y-4"><select required name="library_id" class="w-full bg-slate-800 p-3 rounded"><option value="">Balanceador y biblioteca</option><?php foreach($libraries as $l):?><option value="<?=$l['id']?>"><?=$e(($l['server_name']??'Principal').' → '.$l['name'].' · '.$l['mount_path'])?></option><?php endforeach?></select><input required name="relative_path" placeholder="Movies/Película (2026).mkv" class="w-full bg-slate-800 p-3 rounded"><div class="flex justify-between"><button type="button" @click="tab=3" class="bg-slate-700 px-4 py-2 rounded">Anterior</button><button class="bg-emerald-700 px-5 py-2 rounded">Añadir y validar</button></div></section>
 </form>
</div>
<script>function movieWizard(){return{open:false,tab:1,preview:null,title:'',year:'',language:'es-ES',results:[],tmdbId:'',poster:'',backdrop:'',plot:'',tmdbError:'',searchTmdb(){this.tmdbError='';fetch('/movies/tmdb?'+new URLSearchParams({title:this.title,year:this.year,language:this.language})).then(r=>r.json()).then(r=>{if(!r.ok)throw new Error(r.error);this.results=r.data.results||[]}).catch(e=>this.tmdbError=e.message)},selectTmdb(m){this.tmdbId=m.id;this.title=m.title||this.title;this.year=(m.release_date||'').slice(0,4)||this.year;this.poster=m.poster_path?'https://image.tmdb.org/t/p/w500'+m.poster_path:'';this.backdrop=m.backdrop_path?'https://image.tmdb.org/t/p/original'+m.backdrop_path:'';this.plot=m.overview||'';this.results=[]}}}</script>
