<div x-data="{open:false, secret:null}" class="space-y-6">
 <div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">Cuentas finales</h1><p class="text-slate-400 mt-1">Accesos, expiraciones, restricciones y sesiones.</p></div><?php if(\App\Security\Auth::can('accounts.create')):?><button @click="open=!open" class="bg-cyan-600 hover:bg-cyan-500 px-4 py-2 rounded-lg">Nueva cuenta</button><?php endif?></div>
 <form x-show="open" x-cloak method="post" action="/accounts" class="bg-slate-900 border border-slate-800 rounded-xl p-5 grid md:grid-cols-3 gap-4">
  <?=$csrf->field()?>
  <label class="space-y-1"><span>Usuario</span><input name="username" required minlength="3" class="w-full bg-slate-800 rounded p-2"></label>
  <label class="space-y-1"><span>Credencial del dispositivo</span><input name="password" required minlength="8" autocomplete="new-password" class="w-full bg-slate-800 rounded p-2"></label>
  <label class="space-y-1"><span>Expira</span><input type="datetime-local" name="expires_at" class="w-full bg-slate-800 rounded p-2"></label>
  <label class="space-y-1"><span>Conexiones</span><input type="number" min="1" max="100" value="1" name="max_connections" class="w-full bg-slate-800 rounded p-2"></label>
  <label class="space-y-1"><span>IP permitida</span><input name="allowed_ip" class="w-full bg-slate-800 rounded p-2"></label>
  <label class="space-y-1"><span>País ISO</span><input name="allowed_country" maxlength="2" class="w-full bg-slate-800 rounded p-2"></label>
  <label class="space-y-1 md:col-span-2"><span>User-Agent permitido</span><input name="allowed_user_agent" class="w-full bg-slate-800 rounded p-2"></label>
  <label class="space-y-1"><span>Paquetes</span><select name="package_ids[]" multiple class="w-full bg-slate-800 rounded p-2"><?php foreach($packages as $package):?><option value="<?=$package['id']?>"><?=htmlspecialchars($package['name'])?></option><?php endforeach?></select></label>
  <label class="space-y-1 md:col-span-3"><span>Notas administrativas</span><textarea name="notes" class="w-full bg-slate-800 rounded p-2"></textarea></label>
  <button class="md:col-span-3 bg-cyan-600 px-4 py-2 rounded-lg">Crear cuenta</button>
 </form>
 <div class="overflow-x-auto rounded-xl border border-slate-800"><table class="w-full text-sm"><thead class="bg-slate-900 text-slate-400"><tr><th class="p-3 text-left">Cuenta</th><th>Estado</th><th>Expira</th><th>Conexiones</th><th>Paquetes</th><th class="text-right p-3">Acciones</th></tr></thead><tbody class="divide-y divide-slate-800">
 <?php foreach($accounts as $account):?><tr class="hover:bg-slate-900/50"><td class="p-3"><strong><?=htmlspecialchars($account['username'])?></strong><div class="text-xs text-slate-500"><?=htmlspecialchars($account['allowed_ip']??'Sin restricción IP')?></div></td><td class="text-center"><?=htmlspecialchars($account['status'])?></td><td class="text-center"><?=htmlspecialchars($account['expires_at']??'Sin expiración')?></td><td class="text-center"><?=$account['active_sessions']?> / <?=$account['max_connections']?></td><td class="text-center"><?=htmlspecialchars($account['packages']??'—')?></td><td class="p-3"><div class="flex flex-wrap justify-end gap-2">
 <?php if(\App\Security\Auth::can('accounts.update')):?><form method="post" action="/accounts/renew"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$account['id']?>"><input type="hidden" name="days" value="30"><button class="bg-emerald-700 px-2 py-1 rounded">+30 días</button></form><form method="post" action="/accounts/status"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$account['id']?>"><input type="hidden" name="status" value="<?=$account['status']==='suspended'?'active':'suspended'?>"><button class="bg-amber-700 px-2 py-1 rounded"><?=$account['status']==='suspended'?'Activar':'Suspender'?></button></form><?php endif?>
 <?php if(\App\Security\Auth::can('sessions.disconnect')):?><form method="post" action="/accounts/disconnect"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$account['id']?>"><button class="bg-slate-700 px-2 py-1 rounded">Desconectar</button></form><?php endif?>
 <?php if(\App\Security\Auth::can('accounts.secrets.view')):?><button class="bg-indigo-700 px-2 py-1 rounded" @click="fetch('/accounts/reveal',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf=<?=rawurlencode($csrf->token())?>&id=<?=$account['id']?>'}).then(r=>r.json()).then(r=>secret=r.error||('Servidor: '+r.server+'\nUsuario: '+r.username+'\nContraseña: '+r.credential+'\n\nM3U:\n'+r.m3u+'\n\nEPG:\n'+r.epg))">Datos de conexión</button><?php endif?>
 </div></td></tr><?php endforeach?></tbody></table></div>
 <div x-show="secret" class="fixed inset-0 bg-black/70 grid place-items-center p-4"><div class="bg-slate-900 border border-slate-700 rounded-xl p-6 max-w-2xl"><h2 class="font-bold mb-3">Datos de conexión</h2><code class="block bg-black p-3 rounded break-all whitespace-pre-wrap" x-text="secret"></code><p class="text-xs text-amber-400 mt-3">La visualización quedó registrada en auditoría. Comparte estos datos únicamente con el cliente autorizado.</p><button @click="secret=null" class="mt-4 bg-slate-700 px-4 py-2 rounded">Cerrar</button></div></div>
</div>
