<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use App\Security\{Auth,DeviceCredentialCipher};use PDO;use phpseclib3\Net\SFTP;use RuntimeException;use Throwable;
final readonly class BackupService
{
 public function __construct(private PDO $db,private DeviceCredentialCipher $cipher,private TaskQueueService $queue,private AuditRepository $audit){}
 public function createDestination(array $in):int{$name=trim((string)($in['name']??''));$type=(string)($in['type']??'local');if($name===''||strlen($name)>150||!in_array($type,['local','sftp','s3'],true))throw new RuntimeException('Destino inválido.');$config=$this->config($type,$in);$this->db->prepare('INSERT INTO backup_destinations(name,type,config_ciphertext,retention_days,active,created_by) VALUES(?,?,?,?,1,?)')->execute([$name,$type,$this->cipher->encrypt(json_encode($config,JSON_THROW_ON_ERROR)),max(1,min(3650,(int)($in['retention_days']??30))),Auth::id()]);$id=(int)$this->db->lastInsertId();$this->audit->record('backup.destination_created','backup_destination',$id,['name'=>$name,'type'=>$type]);return $id;}
 public function request(int $destination):int{$s=$this->db->prepare('SELECT 1 FROM backup_destinations WHERE id=? AND active=1');$s->execute([$destination]);if(!$s->fetchColumn())throw new RuntimeException('Destino de backup no disponible.');$this->db->prepare("INSERT INTO backup_runs(destination_id,requested_by) VALUES(?,?)")->execute([$destination,Auth::id()]);$run=(int)$this->db->lastInsertId();$job=$this->queue->enqueue('create_backup',['run_id'=>$run],5,'backup-run-'.$run);$this->db->prepare('UPDATE backup_runs SET job_id=? WHERE id=?')->execute([$job,$run]);return $run;}
 public function scheduleDue():int{$rows=$this->db->query("SELECT d.id FROM backup_destinations d WHERE d.active=1 AND (d.last_backup_at IS NULL OR d.last_backup_at<DATE_SUB(NOW(),INTERVAL 24 HOUR)) AND NOT EXISTS(SELECT 1 FROM backup_runs r WHERE r.destination_id=d.id AND r.status IN ('queued','running'))")->fetchAll(PDO::FETCH_COLUMN);foreach($rows as $id)$this->request((int)$id);return count($rows);}
 public function run(int $id):array{$s=$this->db->prepare('SELECT r.*,d.type,d.config_ciphertext,d.retention_days FROM backup_runs r JOIN backup_destinations d ON d.id=r.destination_id WHERE r.id=?');$s->execute([$id]);$run=$s->fetch()?:throw new RuntimeException('Backup no encontrado.');$config=json_decode($this->cipher->decrypt($run['config_ciphertext']),true,32,JSON_THROW_ON_ERROR);$dir='/var/backups/orionx/work';if(!is_dir($dir)&&!mkdir($dir,0700,true)&&!is_dir($dir))throw new RuntimeException('No se pudo crear el área temporal.');$base='orionx-'.gmdate('Ymd-His').'-'.bin2hex(random_bytes(4)).'.sql';$plain=$dir.'/'.$base;$encrypted=$plain.'.enc';$this->db->prepare("UPDATE backup_runs SET status='running',started_at=NOW() WHERE id=?")->execute([$id]);try{$this->dump($plain);$this->encrypt($plain,$encrypted);$size=filesize($encrypted);$hash=hash_file('sha256',$encrypted);$this->deliver($run['type'],$config,$encrypted,basename($encrypted));$this->db->prepare("UPDATE backup_runs SET status='completed',filename=?,size_bytes=?,checksum_sha256=?,completed_at=NOW() WHERE id=?")->execute([basename($encrypted),$size,$hash,$id]);$this->db->prepare('UPDATE backup_destinations SET last_backup_at=NOW() WHERE id=?')->execute([$run['destination_id']]);return ['filename'=>basename($encrypted),'size_bytes'=>$size,'sha256'=>$hash];}catch(Throwable $e){$this->db->prepare("UPDATE backup_runs SET status='failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($e->getMessage(),0,65535),$id]);throw $e;}finally{if(is_file($plain))unlink($plain);if(is_file($encrypted))unlink($encrypted);}}
 private function dump(string $target):void{$out=fopen($target,'wb');$args=['/usr/bin/mariadb-dump','--single-transaction','--quick','--skip-lock-tables','--routines','--triggers','--host',(string)$_ENV['DB_HOST'],'--port',(string)($_ENV['DB_PORT']??3306),'--user',(string)$_ENV['DB_USERNAME'],(string)$_ENV['DB_DATABASE']];$p=proc_open($args,[1=>$out,2=>['pipe','w']],$pipes,null,['MYSQL_PWD'=>(string)$_ENV['DB_PASSWORD']],['bypass_shell'=>true]);if(!is_resource($p)){fclose($out);throw new RuntimeException('No se pudo iniciar mariadb-dump.');}$error=stream_get_contents($pipes[2]);fclose($pipes[2]);$exit=proc_close($p);fclose($out);if($exit!==0)throw new RuntimeException('Falló el backup SQL: '.substr($error,0,500));}
 private function encrypt(string $in,string $out):void{$key=hash('sha256',(string)$_ENV['CREDENTIALS_KEY']);$p=proc_open(['/usr/bin/openssl','enc','-aes-256-cbc','-salt','-pbkdf2','-iter','200000','-in',$in,'-out',$out,'-pass','env:ORIONX_BACKUP_KEY'],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,['ORIONX_BACKUP_KEY'=>$key],['bypass_shell'=>true]);if(!is_resource($p))throw new RuntimeException('No se pudo cifrar el backup.');$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($p)!==0)throw new RuntimeException('Falló el cifrado: '.substr($error,0,300));}
 private function deliver(string $type,array $c,string $file,string $name):void{if($type==='local'){$dir='/var/backups/orionx/local';if(!is_dir($dir))mkdir($dir,0700,true);if(!rename($file,$dir.'/'.$name))throw new RuntimeException('No se pudo guardar el backup local.');return;}if($type==='sftp'){$sftp=new SFTP($c['host'],(int)$c['port'],15);if(!$sftp->login($c['username'],$c['password']))throw new RuntimeException('Autenticación SFTP rechazada.');if(!$sftp->put(rtrim($c['path'],'/').'/'.$name,$file,SFTP::SOURCE_LOCAL_FILE))throw new RuntimeException('Falló la carga SFTP.');return;}$cfg=tempnam(sys_get_temp_dir(),'orionx-rclone-');file_put_contents($cfg,"[cloud]\ntype = s3\nprovider = Other\naccess_key_id = {$c['access_key']}\nsecret_access_key = {$c['secret_key']}\nendpoint = {$c['endpoint']}\n");chmod($cfg,0600);try{$p=proc_open(['/usr/bin/rclone','--config',$cfg,'copyto',$file,'cloud:'.$c['bucket'].'/'.trim($c['path'],'/').'/'.$name],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,null,['bypass_shell'=>true]);if(!is_resource($p))throw new RuntimeException('No se pudo iniciar rclone.');$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($p)!==0)throw new RuntimeException('Falló la carga S3: '.substr($error,0,500));}finally{unlink($cfg);}}
 private function config(string $type,array $in):array{if($type==='local')return [];if($type==='sftp'){if(!filter_var($in['host']??'',FILTER_VALIDATE_DOMAIN,FILTER_FLAG_HOSTNAME)&&!filter_var($in['host']??'',FILTER_VALIDATE_IP))throw new RuntimeException('Host SFTP inválido.');return ['host'=>$in['host'],'port'=>max(1,min(65535,(int)($in['port']??22))),'username'=>trim((string)$in['username']),'password'=>(string)$in['password'],'path'=>trim((string)($in['path']??'/backups'))];}foreach(['endpoint','bucket','access_key','secret_key'] as $k)if(trim((string)($in[$k]??''))==='')throw new RuntimeException('Completa la configuración S3.');if(!filter_var($in['endpoint'],FILTER_VALIDATE_URL))throw new RuntimeException('Endpoint S3 inválido.');return ['endpoint'=>$in['endpoint'],'bucket'=>$in['bucket'],'access_key'=>$in['access_key'],'secret_key'=>$in['secret_key'],'path'=>trim((string)($in['path']??'orionx'))];}
}
