<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\{AuditRepository,CertificateRepository};use App\Security\Auth;use PDO;use RuntimeException;use Throwable;
final readonly class CertificateService
{
 public function __construct(private PDO $db,private TaskQueueService $queue,private AuditRepository $audit,private CertificateRepository $repo){}
 public function request(string $target,?int $serverId,string $domain,string $email):int
 {
  if(!in_array($target,['main','balancer'],true))throw new RuntimeException('Destino TLS inválido.');$domain=strtolower(rtrim(trim($domain),'.'));if(!$this->domain($domain))throw new RuntimeException('Dominio inválido.');if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Correo inválido.');if($target==='main')$serverId=null;elseif(!$serverId)throw new RuntimeException('Selecciona un balanceador.');
  if($serverId){$s=$this->db->prepare('SELECT public_ip FROM servers WHERE id=?');$s->execute([$serverId]);$serverIp=$s->fetchColumn();if($serverIp===false)throw new RuntimeException('Balanceador no encontrado.');$records=dns_get_record($domain,DNS_A|DNS_AAAA)?:[];$resolved=array_merge(array_filter(array_column($records,'ip')),array_filter(array_column($records,'ipv6')));if($resolved&&!in_array($serverIp,$resolved,true))throw new RuntimeException('El dominio no apunta a la IP pública del balanceador.');}
  $this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO certificate_requests(target_type,server_id,domain,email,status,requested_by) VALUES(?,?,?,?, 'queued',?) ON DUPLICATE KEY UPDATE email=VALUES(email),status=IF(status='processing',status,'queued'),last_error=NULL,requested_by=VALUES(requested_by),requested_at=NOW()");$s->execute([$target,$serverId,$domain,$email,Auth::id()??throw new RuntimeException('Sesión inválida.')]);$id=(int)$this->db->lastInsertId();if($id===0){$find=$this->db->prepare('SELECT id FROM certificate_requests WHERE target_type=? AND server_id<=>? AND domain=?');$find->execute([$target,$serverId,$domain]);$id=(int)$find->fetchColumn();}$this->audit->record('certificate.requested','certificate_request',$id,['target'=>$target,'server_id'=>$serverId,'domain'=>$domain]);$this->db->commit();if($target==='main')$this->queue->enqueue('issue_certificate',['request_id'=>$id],5,'certificate-'.$id.'-'.date('YmdHi'));return $id;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
 public function claimForNode(int $serverId):?array{$this->db->beginTransaction();try{$request=$this->repo->pendingForNode($serverId);if($request)$this->db->prepare("UPDATE certificate_requests SET status='processing',started_at=NOW() WHERE id=? AND server_id=?")->execute([$request['id'],$serverId]);$this->db->commit();return $request;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function scheduleRenewals():int
 {
  $rows=$this->db->query("SELECT id,target_type FROM certificate_requests WHERE expires_at IS NOT NULL AND expires_at<=DATE_ADD(NOW(),INTERVAL 30 DAY) AND status IN ('issued','failed','renewal_due') AND (completed_at IS NULL OR completed_at<DATE_SUB(NOW(),INTERVAL 12 HOUR)) AND (last_renewal_at IS NULL OR last_renewal_at<DATE_SUB(NOW(),INTERVAL 12 HOUR)) ORDER BY expires_at LIMIT 200")->fetchAll();$count=0;foreach($rows as $row){$id=(int)$row['id'];if($row['target_type']==='main'){$this->db->prepare("UPDATE certificate_requests SET status='renewal_due',last_error=NULL WHERE id=?")->execute([$id]);$this->queue->enqueue('issue_certificate',['request_id'=>$id],2,'certificate-renew-'.$id.'-'.date('Ymd'));}else{$this->db->prepare("UPDATE certificate_requests SET status='queued',last_error=NULL WHERE id=?")->execute([$id]);}$count++;}return $count;
 }
 public function nodeResult(int $serverId,int $requestId,bool $success,?string $path,?string $expires,?string $error):void{$s=$this->db->prepare("UPDATE certificate_requests SET status=?,certificate_path=?,expires_at=?,last_error=?,completed_at=NOW(),last_renewal_at=IF(?='issued',NOW(),last_renewal_at) WHERE id=? AND server_id=? AND target_type='balancer' AND status='processing'");$status=$success?'issued':'failed';$s->execute([$status,$success?substr((string)$path,0,1024):null,$success?$expires:null,$success?null:substr((string)$error,0,65535),$status,$requestId,$serverId]);if($s->rowCount()!==1)throw new RuntimeException('Solicitud TLS no disponible.');}
 private function domain(string $domain):bool{return strlen($domain)<=253&&!filter_var($domain,FILTER_VALIDATE_IP)&&preg_match('/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/',$domain)===1;}
}
