<?php
declare(strict_types=1);
namespace App\Services;
use App\Security\DeviceCredentialCipher;use PDO;use RuntimeException;
final readonly class CompatibilityService
{
 public function __construct(private PDO $db,private DeviceCredentialCipher $cipher,private MediaTokenService $tokens){}
 public function account(string $username,string $password):array{$s=$this->db->prepare("SELECT * FROM end_user_accounts WHERE username=? AND deleted_at IS NULL LIMIT 1");$s->execute([$username]);$a=$s->fetch();if(!$a||!hash_equals($this->cipher->decrypt($a['credential_ciphertext']),$password)||$a['status']!=='active'||($a['expires_at']&&strtotime($a['expires_at'])<=time()))throw new RuntimeException('Credenciales inválidas.');return $a;}
 public function player(array $a,string $action):array{if($action==='')return ['user_info'=>['username'=>$a['username'],'password'=>'','message'=>'','auth'=>1,'status'=>'Active','exp_date'=>$a['expires_at']?(string)strtotime($a['expires_at']):null,'is_trial'=>(string)(int)($a['is_trial']??0),'active_cons'=>'0','created_at'=>(string)strtotime($a['created_at']),'max_connections'=>(string)$a['max_connections'],'allowed_output_formats'=>['m3u8','ts']],'server_info'=>$this->serverInfo()];return match($action){'get_live_categories'=>$this->categories('live'),'get_vod_categories'=>$this->categories('movie'),'get_series_categories'=>$this->categories('series'),'get_live_streams'=>$this->items('live'),'get_vod_streams'=>$this->items('movie'),'get_series'=>$this->items('series'),default=>[]};}
 public function categories(string $type):array{$s=$this->db->prepare('SELECT DISTINCT c.id,c.name FROM categories c JOIN content_items i ON i.category_id=c.id AND i.type=? AND i.status=\'active\' ORDER BY c.name');$s->execute([$type]);return array_map(static fn($r)=>['category_id'=>(string)$r['id'],'category_name'=>$r['name'],'parent_id'=>0],$s->fetchAll());}
 public function items(string $type):array{$s=$this->db->prepare("SELECT i.id,i.title,i.category_id,i.metadata FROM content_items i WHERE i.type=? AND i.status='active' ORDER BY i.title LIMIT 5000");$s->execute([$type]);$out=[];foreach($s->fetchAll() as $r){$m=json_decode($r['metadata']?:'{}',true)?:[];$out[]=$type==='series'?['num'=>(int)$r['id'],'name'=>$r['title'],'series_id'=>(int)$r['id'],'cover'=>$m['poster_url']??'','plot'=>$m['overview']??'','category_id'=>(string)$r['category_id']]:['num'=>(int)$r['id'],'name'=>$r['title'],'stream_type'=>$type==='live'?'live':'movie','stream_id'=>(int)$r['id'],'stream_icon'=>$m['poster_url']??$m['logo']??'','epg_channel_id'=>$m['epg_channel_id']??null,'added'=>(string)($m['added']??time()),'category_id'=>(string)$r['category_id'],'container_extension'=>$type==='live'?'ts':($m['container_extension']??'mp4')];}return $out;}
 public function playlist(array $a,string $password):string{$base=rtrim((string)$_ENV['APP_URL'],'/');$lines=['#EXTM3U'];foreach($this->items('live') as $i){$lines[]='#EXTINF:-1 tvg-id="'.($i['epg_channel_id']??'').'" tvg-logo="'.$i['stream_icon'].'",'.$i['name'];$lines[]=$base.'/live/'.rawurlencode($a['username']).'/'.rawurlencode($password).'/'.$i['stream_id'].'.ts';}foreach($this->items('movie') as $i){$lines[]='#EXTINF:-1 tvg-logo="'.$i['stream_icon'].'",'.$i['name'];$lines[]=$base.'/movie/'.rawurlencode($a['username']).'/'.rawurlencode($password).'/'.$i['stream_id'].'.'.$i['container_extension'];}return implode("\n",$lines)."\n";}
 public function xmltv():string{$rows=$this->db->query("SELECT external_channel_id,starts_at,ends_at,title,description FROM epg_programmes WHERE ends_at>=NOW() AND starts_at<DATE_ADD(NOW(),INTERVAL 7 DAY) ORDER BY starts_at LIMIT 50000")->fetchAll();$channels=[];foreach($rows as $r)$channels[$r['external_channel_id']]=true;$xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<tv generator-info-name=\"Media Panel\">\n";foreach(array_keys($channels) as $id)$xml.='<channel id="'.$this->x($id).'"><display-name>'.$this->x($id)."</display-name></channel>\n";foreach($rows as $r)$xml.='<programme start="'.date('YmdHis O',strtotime($r['starts_at'])).'" stop="'.date('YmdHis O',strtotime($r['ends_at'])).'" channel="'.$this->x($r['external_channel_id']).'"><title>'.$this->x($r['title']).'</title><desc>'.$this->x($r['description']??'')."</desc></programme>\n";return $xml."</tv>\n";}
 public function magCatalog(string $type):array{return $this->items($type);}
 public function playback(array $account,int $contentId,?string $ip,?string $agent):string{$s=$this->db->prepare("SELECT f.public_id FROM content_files f JOIN content_items c ON c.id=f.content_item_id WHERE c.id=? AND c.status='active' AND f.status='available' AND (EXISTS(SELECT 1 FROM account_content_items ac WHERE ac.account_id=? AND ac.content_item_id=c.id) OR EXISTS(SELECT 1 FROM account_categories cat WHERE cat.account_id=? AND cat.category_id=c.category_id) OR EXISTS(SELECT 1 FROM account_packages ap JOIN package_content_items pc ON pc.package_id=ap.package_id WHERE ap.account_id=? AND pc.content_item_id=c.id)) LIMIT 1");$s->execute([$contentId,$account['id'],$account['id'],$account['id']]);$file=$s->fetchColumn();if(!$file)throw new RuntimeException('Contenido no autorizado o sin archivo disponible.');$count=$this->db->prepare('SELECT COUNT(*) FROM active_sessions WHERE account_id=? AND disconnected_at IS NULL');$count->execute([$account['id']]);if((int)$count->fetchColumn()>=(int)$account['max_connections'])throw new RuntimeException('Límite de conexiones alcanzado.');$session=sprintf('%s-%s-4%s-%s%s-%s',bin2hex(random_bytes(4)),bin2hex(random_bytes(2)),bin2hex(random_bytes(2)),dechex(random_int(8,11)),bin2hex(random_bytes(1)),bin2hex(random_bytes(6)));$this->db->prepare('INSERT INTO active_sessions(id,account_id,ip,user_agent) VALUES(?,?,?,?)')->execute([$session,$account['id'],$ip?:'0.0.0.0',substr((string)$agent,0,255)]);return '/media/'.$this->tokens->issue((int)$account['id'],$session,(string)$file,$ip,$agent);}
 private function serverInfo():array{$url=parse_url((string)$_ENV['APP_URL']);return ['url'=>$url['host']??'','port'=>(string)($url['port']??80),'https_port'=>(string)($url['port']??443),'server_protocol'=>$url['scheme']??'https','rtmp_port'=>'0','timezone'=>'UTC','timestamp_now'=>time(),'time_now'=>date('Y-m-d H:i:s')];}
 private function x(string $value):string{return htmlspecialchars($value,ENT_XML1|ENT_QUOTES,'UTF-8');}
}
