<?php
declare(strict_types=1);namespace App\Services;use App\Repositories\AuditRepository;use App\Security\Auth;use PDO;use RuntimeException;
final readonly class DatabaseFirewallService{
 public function __construct(private PDO $db,private AuditRepository $audit){}
 public function add(int $serverId,string $kind):void{if(!in_array($kind,['public','private'],true))throw new RuntimeException('Tipo de IP inválido.');$s=$this->db->prepare('SELECT name,public_ip,private_ip FROM servers WHERE id=?');$s->execute([$serverId]);$server=$s->fetch()?:throw new RuntimeException('Balanceador no encontrado.');$ip=(string)$server[$kind.'_ip'];if(!filter_var($ip,FILTER_VALIDATE_IP))throw new RuntimeException('El balanceador no tiene una IP válida de ese tipo.');if($this->unsafe($ip))throw new RuntimeException('No se permiten loopback, IP sin especificar ni direcciones multicast.');$this->db->prepare("INSERT INTO database_ip_allowlist(server_id,ip,ip_kind,active,created_by) VALUES(?,?,?,1,?) ON DUPLICATE KEY UPDATE server_id=VALUES(server_id),ip_kind=VALUES(ip_kind),active=1,created_by=VALUES(created_by)")->execute([$serverId,$ip,$kind,Auth::id()]);$this->audit->record('database.firewall_rule_added','server',$serverId,['ip'=>$ip,'kind'=>$kind]);}
 public function remove(int $id):void{$s=$this->db->prepare('SELECT server_id,ip FROM database_ip_allowlist WHERE id=?');$s->execute([$id]);$r=$s->fetch()?:throw new RuntimeException('Regla no encontrada.');$this->db->prepare('UPDATE database_ip_allowlist SET active=0 WHERE id=?')->execute([$id]);$this->audit->record('database.firewall_rule_disabled','server',(int)$r['server_id'],['ip'=>$r['ip']]);}
 public function apply():void{$count=(int)$this->db->query('SELECT COUNT(*) FROM database_ip_allowlist WHERE active=1')->fetchColumn();$this->db->prepare('INSERT INTO database_firewall_runs(status,requested_by,rules_count) VALUES(\'queued\',?,?)')->execute([Auth::id(),$count]);$id=(int)$this->db->lastInsertId();$helper='/usr/local/sbin/orionx-db-firewall-helper';if(!is_executable($helper))throw new RuntimeException('El helper del firewall no está instalado. Actualiza el servidor principal.');$p=proc_open(['/usr/bin/sudo','-n',$helper,(string)$id],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,['PATH'=>'/usr/sbin:/usr/bin:/sbin:/bin'],['bypass_shell'=>true]);if(!is_resource($p))throw new RuntimeException('No se pudo iniciar el helper del firewall.');$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);if($exit!==0)throw new RuntimeException('No se aplicaron las reglas: '.substr(trim($err?:$out),0,1000));$this->audit->record('database.firewall_applied','database_firewall_run',$id,['rules'=>$count]);}
 private function unsafe(string $ip):bool{return in_array($ip,['0.0.0.0','::','127.0.0.1','::1'],true)||(filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_IPV4)&&ip2long($ip)>=ip2long('224.0.0.0'));}
}
