<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use PDO;use RuntimeException;use Throwable;
final readonly class EpgService
{
 public function __construct(private PDO $db,private TaskQueueService $queue,private AuditRepository $audit){}
 public function save(array $in):int{$name=trim((string)($in['name']??''));$url=trim((string)($in['source_url']??''));$timezone=trim((string)($in['timezone']??'UTC'));$minutes=max(15,min(10080,(int)($in['refresh_minutes']??360)));if($name===''||strlen($name)>150)throw new RuntimeException('Nombre EPG inválido.');$this->safeUrl($url);try{new \DateTimeZone($timezone);}catch(Throwable){throw new RuntimeException('Zona horaria inválida.');}$this->db->prepare('INSERT INTO epg_sources(name,source_url,timezone,refresh_minutes,active) VALUES(?,?,?,?,?)')->execute([$name,$url,$timezone,$minutes,isset($in['active'])]);$id=(int)$this->db->lastInsertId();$this->audit->record('epg.source_created','epg_source',$id,['name'=>$name]);return $id;}
 public function queue(int $id):string{$s=$this->db->prepare('SELECT 1 FROM epg_sources WHERE id=? AND active=1');$s->execute([$id]);if(!$s->fetchColumn())throw new RuntimeException('Fuente EPG no disponible.');$job=$this->queue->enqueue('import_epg',['source_id'=>$id],30,'epg-'.$id.'-'.date('YmdHi'));$this->db->prepare("UPDATE epg_sources SET last_status='queued',last_job_id=?,last_error=NULL WHERE id=?")->execute([$job,$id]);return $job;}
 public function queueDue():int{$rows=$this->db->query("SELECT id FROM epg_sources WHERE active=1 AND (last_import_at IS NULL OR last_import_at<=DATE_SUB(NOW(),INTERVAL refresh_minutes MINUTE)) AND last_status NOT IN ('queued','running') LIMIT 50")->fetchAll(PDO::FETCH_COLUMN);foreach($rows as $id)$this->queue((int)$id);return count($rows);}
 public function import(int $id):array{$s=$this->db->prepare('SELECT * FROM epg_sources WHERE id=? AND active=1');$s->execute([$id]);$source=$s->fetch()?:throw new RuntimeException('Fuente EPG no encontrada.');$this->db->prepare("UPDATE epg_sources SET last_status='running',last_error=NULL WHERE id=?")->execute([$id]);$tmp=tempnam(sys_get_temp_dir(),'orionx-epg-');try{$this->download($source['source_url'],$tmp);$xml=simplexml_load_file($tmp,'SimpleXMLElement',LIBXML_NONET|LIBXML_COMPACT);if($xml===false)throw new RuntimeException('XMLTV inválido.');$insert=$this->db->prepare('INSERT INTO epg_programmes(source_id,external_channel_id,starts_at,ends_at,title,description,metadata) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE ends_at=VALUES(ends_at),title=VALUES(title),description=VALUES(description),metadata=VALUES(metadata)');$count=0;foreach($xml->programme as $p){$channel=trim((string)$p['channel']);$start=$this->xmlDate((string)$p['start']);$end=$this->xmlDate((string)$p['stop']);$title=trim((string)$p->title);if($channel===''||!$start||!$end||$end<=$start||$title==='')continue;$insert->execute([$id,substr($channel,0,255),$start,$end,substr($title,0,255),trim((string)$p->desc)?:null,json_encode(['category'=>(string)($p->category??''),'icon'=>(string)($p->icon['src']??'')],JSON_UNESCAPED_UNICODE)]);$count++;if($count>=500000)break;}$this->db->prepare('DELETE FROM epg_programmes WHERE source_id=? AND ends_at<DATE_SUB(NOW(),INTERVAL 1 DAY)')->execute([$id]);$this->db->prepare("UPDATE epg_sources SET last_status='completed',last_import_at=NOW(),last_error=NULL WHERE id=?")->execute([$id]);return ['programmes'=>$count];}catch(Throwable $e){$this->db->prepare("UPDATE epg_sources SET last_status='failed',last_error=? WHERE id=?")->execute([substr($e->getMessage(),0,500),$id]);throw $e;}finally{if(is_file($tmp))unlink($tmp);}}
 private function safeUrl(string $url):void{$p=parse_url($url);if(!$p||!in_array($p['scheme']??'',['http','https'],true)||empty($p['host'])||isset($p['user'])||isset($p['pass']))throw new RuntimeException('URL EPG inválida.');$ips=gethostbynamel($p['host'])?:[];if(!$ips)throw new RuntimeException('No se pudo resolver el host EPG.');foreach($ips as $ip)if(filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)===false)throw new RuntimeException('La fuente EPG apunta a una red privada o reservada.');}
 private function download(string $url,string $target):void{$this->safeUrl($url);$h=fopen($target,'wb');$size=0;$c=curl_init($url);curl_setopt_array($c,[CURLOPT_FILE=>$h,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>120,CURLOPT_FAILONERROR=>true,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_USERAGENT=>'OrionX-EPG/1.0',CURLOPT_NOPROGRESS=>false,CURLOPT_PROGRESSFUNCTION=>static function($r,$total,$now)use(&$size){$size=(int)$now;return $now>104857600?1:0;}]);$ok=curl_exec($c);$error=curl_error($c);curl_close($c);fclose($h);if(!$ok||$size>104857600)throw new RuntimeException('No se pudo descargar XMLTV: '.substr($error,0,200));}
 private function xmlDate(string $value):?string{if(!preg_match('/^(\d{14})(?:\s*([+-]\d{4}))?/',$value,$m))return null;$d=\DateTimeImmutable::createFromFormat('YmdHis O',$m[1].' '.($m[2]??'+0000'));return $d?$d->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'):null;}
}
