<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use App\Security\{Auth,DeviceCredentialCipher};use PDO;use RuntimeException;
final readonly class GeneralSettingsService
{
 public function __construct(private PDO $db,private DeviceCredentialCipher $cipher,private AuditRepository $audit){}
 public function definitions():array{return [
 'general'=>['label'=>'Preferencias','sections'=>[
  'Servidor'=>[$this->t('server_name','Nombre del servidor','OrionX'),$this->t('tv_domain','Dominio TV'),$this->t('server_timezone','Zona horaria','America/Panama'),$this->t('motd','Mensaje del día','Bienvenido a OrionX'),$this->n('show_entries','Mostrar entradas',50,10,500),$this->n('fails_per_time','Ventana de fallos',86400,60,604800),$this->t('date_format','Formato de fecha','Y-m-d'),$this->t('datetime_format','Formato fecha y hora','Y-m-d H:i:s'),$this->b('group_streams_table','Agrupar tabla de streams'),$this->b('seamless_navigation','Navegación continua'),$this->b('show_tickets_icon','Mostrar icono de tickets'),$this->b('disable_restart_counter','Desactivar contador de reinicios'),$this->b('auto_cleanup_files','Limpieza automática de archivos'),$this->b('check_vod_cron','Comprobar VOD por cron'),$this->b('show_images_picons','Mostrar imágenes y picons',true),$this->b('quick_edit_modal','Edición rápida'),$this->n('mysql_sleep_timeout','MySQL sleep timeout',21600,60,86400)],
  'Dashboard'=>[$this->b('dashboard_graphs','Mostrar gráficas',true),$this->b('dashboard_connections_map','Mapa de conexiones'),$this->b('dashboard_alt_server_view','Vista alternativa de servidores'),$this->b('dashboard_header_stats','Estadísticas en cabecera',true),$this->b('dashboard_service_status','Estado de servicios',true),$this->n('cpu_threshold','Umbral CPU %',67,1,100),$this->n('memory_threshold','Umbral memoria %',67,1,100),$this->n('disk_threshold','Umbral disco %',67,1,100),$this->n('network_threshold','Umbral red %',67,1,100),$this->n('clients_threshold','Umbral clientes %',67,1,100)],
  'Búsqueda y revendedores'=>[$this->b('search_enabled','Habilitar búsqueda',true),$this->n('search_items','Número de resultados',20,1,500),$this->b('disable_trials','Desactivar trials'),$this->b('ssl_custom_dns','DNS SSL personalizado'),$this->b('debug_mode','Modo debug'),$this->b('send_logs_xui','Enviar logs a XUI',false,false)],
  'reCAPTCHA'=>[$this->b('recaptcha_enabled','Habilitar reCAPTCHA'),$this->p('recaptcha_site_key','Site key'),$this->p('recaptcha_secret_key','Secret key')],
  'Argumentos predeterminados'=>[$this->t('default_user_agent','User-Agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'),$this->t('default_http_proxy','Proxy HTTP'),$this->p('default_cookie','Cookie'),$this->a('default_headers','Headers JSON'),$this->n('ondemand_probesize','On-demand probesize',10000000,32,100000000)]
 ]],
 'security'=>['label'=>'Seguridad IP y abuso','sections'=>[
  'Seguridad IP'=>[$this->b('match_ip_subnet','Coincidir subred IP'),$this->b('logout_ip_change','Cerrar sesión al cambiar IP'),$this->b('restrict_same_ip','Restringir a la misma IP'),$this->b('random_rtmp_ip','IP RTMP aleatoria'),$this->b('disallow_second_ip','Prohibir segunda IP'),$this->n('disallow_connections_lte','Prohibir si conexiones ≤',5,0,100)],
  'Prevención de restream'=>[$this->b('xui_detect_deny','Detectar XUI y denegar'),$this->b('xui_detect_ban_lines','Detectar XUI y bloquear líneas'),$this->b('block_hosting','Bloquear servidores de hosting'),$this->b('block_proxy_vpn','Bloquear proxies/VPN')],
  'Flood y fuerza bruta'=>[$this->n('flood_limit','Límite flood',20,1,10000),$this->n('flood_seconds','Por segundos',2,1,3600),$this->n('auth_flood_limit','Límite flood autenticación',30,1,10000),$this->n('auth_flood_seconds','Ventana autenticación',10,1,3600),$this->n('auth_flood_sleep','Espera autenticación',5,0,60),$this->a('flood_ip_exclusions','IP excluidas'),$this->n('mac_bruteforce','Bruteforce MAC',3,1,100),$this->n('username_bruteforce','Bruteforce usuario',3,1,100),$this->n('bruteforce_frequency','Frecuencia bruteforce',300,10,86400),$this->n('maximum_login_attempts','Intentos máximos de login',3,1,100),$this->n('max_simultaneous_downloads','Descargas simultáneas',2,1,100)]
 ]],
 'api'=>['label'=>'API, TMDB y EPG','sections'=>[
  'TMDB y VOD'=>[$this->p('tmdb_key','TMDB key'),$this->s('tmdb_language','Idioma TMDB','es-ES',['es-ES'=>'Español','en-US'=>'English']),$this->b('tmdb_download_images','Descargar imágenes',true),$this->b('api_redirect','API redirect'),$this->s('append_movie_year','Añadir año a película','disabled',['disabled'=>'Desactivado','title'=>'Título','year'=>'Año']),$this->s('api_container','Contenedor API','hls',['hls'=>'HLS','ts'=>'MPEG-TS']),$this->n('playlist_cache','Cache de playlists',0,0,86400),$this->b('playlist_from_mysql','Obtener playlists de MySQL'),$this->b('epg_force_utc','Forzar EPG a UTC',true),$this->b('keep_request_protocol','Mantener protocolo solicitado'),$this->s('vod_parser','Parser VOD','guessit',['guessit'=>'GuessIt','filename'=>'Nombre de archivo']),$this->b('cloudflare_enabled','Habilitar Cloudflare')],
  'Legacy y EPG API'=>[$this->b('legacy_playlist','URL playlist legacy'),$this->b('legacy_xmltv','URL XMLTV legacy'),$this->b('legacy_panel_api','Panel API legacy'),$this->b('legacy_duplicate_streams','Duplicar streams en apps legacy'),$this->b('epg_api_enabled','Habilitar EPG API',true),$this->s('epg_extra_data','Datos extra EPG','extended',['none'=>'Ninguno','extended'=>'Descripción extendida']),$this->n('epg_days_fetch','Días a obtener',7,1,30),$this->n('epg_days_keep','Días a conservar',7,1,90)],
  'Servicios API'=>[$this->a('admin_streaming_ips','IP administrativas de streaming'),$this->a('api_ips','IP API'),$this->p('api_password','Contraseña API'),$this->b('disable_epg_line','Desactivar EPG para líneas'),$this->b('disable_epg_restreamer','Desactivar EPG para restreamers'),$this->b('disable_playlist_line','Desactivar playlist para líneas'),$this->b('disable_playlist_restreamer','Desactivar playlist restreamer'),$this->b('disable_player_api','Desactivar Player API'),$this->b('disable_enigma_api','Desactivar Enigma2 API'),$this->b('disable_ministra_api','Desactivar Ministra API'),$this->b('verify_hosts','Verificar hosts')]
 ]],
 'streaming'=>['label'=>'Streaming','sections'=>[
  'Acceso y salida'=>[$this->p('streaming_password','Contraseña de streaming'),$this->b('isp_lock','Bloqueo ISP'),$this->b('asn_lock','Bloqueo ASN'),$this->b('disable_mpegts','Desactivar MPEG-TS'),$this->b('restream_mpegts','Permitir MPEG-TS a restreamers'),$this->b('disable_hls','Desactivar HLS'),$this->b('restream_hls','Permitir HLS a restreamers'),$this->b('disable_rtmp','Desactivar RTMP'),$this->b('restream_rtmp','Permitir RTMP a restreamers'),$this->b('case_sensitive_lines','Líneas sensibles a mayúsculas'),$this->b('encrypt_hls','Cifrar segmentos HLS'),$this->b('disallow_empty_ua','Prohibir User-Agent vacío'),$this->n('vod_bitrate_buffer','Buffer bitrate VOD',3000,0,100000),$this->n('vod_limit_percent','Límite VOD %',100,1,100),$this->n('auto_kick_hours','Auto-kick horas',8,0,168)],
  'Balanceo y conexión'=>[$this->s('load_balancing','Balanceo','connections',['connections'=>'Conexiones','load'=>'Carga','region'=>'Región']),$this->b('restream_bypass_proxy','Restreamer sin proxy'),$this->s('channel_sort','Orden de canales','legacy',['legacy'=>'Legacy','name'=>'Nombre','number'=>'Número']),$this->b('sort_vod_date','Ordenar VOD por fecha'),$this->b('nginx_buffer','Usar buffer Nginx'),$this->b('log_client_isp','Registrar ISP'),$this->n('capacity_interval','Intervalo de capacidad',10,1,3600),$this->b('monitor_connections','Monitorizar conexiones',true),$this->b('restart_php_fpm','Reiniciar PHP-FPM caído'),$this->b('kill_rogue_ffmpeg','Cerrar FFmpeg huérfano'),$this->n('redirect_expiration','Expiración redirect',127,1,3600),$this->b('hls_read_native','Lectura HLS nativa'),$this->n('read_buffer_size','Tamaño buffer',8192,1024,1048576),$this->n('redis_sync_timer','Sincronización Redis',1,1,60),$this->b('allow_cdn_forward','Permitir CDN/forwarding'),$this->n('max_failures','Máximo de fallos',3,1,100)]
 ]],
 'processing'=>['label'=>'On-demand y encoding','sections'=>[
  'On-demand'=>[$this->b('ondemand_instant_off','Apagado inmediato'),$this->b('ondemand_exit_failure','Salir al fallar'),$this->n('ondemand_wait_timeout','Tiempo de espera',20,1,600),$this->n('ondemand_prebuffer','Prebuffer solicitado',0,0,600),$this->b('ondemand_balance_live','Balancear como live'),$this->b('scanner_enabled','Habilitar scanner'),$this->n('scanner_time','Tiempo scanner',3600,60,86400),$this->n('max_probe_time','Tiempo máximo probe',5,1,300),$this->n('ondemand_logs_keep','Conservar logs',604800,60,31536000)],
  'Cola y segmentos'=>[$this->n('max_movie_encodes','Máximo encoding películas',1000,1,10000),$this->n('max_channel_encodes','Máximo encoding canales',1,1,1000),$this->n('queue_loop_timer','Intervalo de cola',1,1,60),$this->n('segment_duration','Duración segmento',10,1,60),$this->n('segment_list_size','Tamaño lista',6,2,100),$this->n('segment_delete_threshold','Umbral borrado',4,1,100),$this->n('segment_wait','Espera máxima segmento',20,1,300),$this->n('analysis_duration','Duración de análisis',5000000,1000,100000000),$this->n('probe_size','Probe size',10000000,1000,100000000),$this->t('ffmpeg_version','Versión FFmpeg','system'),$this->s('ffmpeg_segment_type','Tipo segmento FFmpeg','hls',['hls'=>'-f hls','segment'=>'-f segment']),$this->b('ffmpeg_warnings','Mostrar advertencias FFmpeg'),$this->b('ignore_keyframes','Ignorar keyframes'),$this->b('loopback_php','Loopback mediante PHP')],
  'Monitor de streams'=>[$this->b('restart_audio_loss','Reiniciar por pérdida de audio'),$this->b('priority_backup','Respaldo por prioridad',true),$this->n('probe_duration','Duración probe',10,1,120),$this->n('stream_failure_sleep','Espera tras fallo',10,1,600),$this->n('fps_start_delay','Retraso FPS',600,0,3600),$this->s('fps_check_type','Tipo comprobación FPS','avg_frame_rate',['avg_frame_rate'=>'avg_frame_rate','r_frame_rate'=>'r_frame_rate']),$this->b('probe_via_api','Probe mediante API')]
 ]],
 'ministra'=>['label'=>'Ministra y dispositivos','sections'=>[
  'Preferencias'=>[$this->b('stb_all_categories','Mostrar todas las categorías'),$this->s('stb_default_container','Contenedor','ts',['ts'=>'TS','m3u8'=>'HLS']),$this->b('stb_subtitles','Subtítulos siempre activos'),$this->b('stb_connection_indicator','Indicar problema de conexión'),$this->b('stb_channel_logos','Mostrar logos',true),$this->b('stb_preview_logos','Mostrar logos en preview'),$this->n('stb_playback_limit','Límite playback',3,1,20),$this->s('stb_aspect_ratio','Aspect ratio','fit',['fit'=>'fit','fill'=>'fill','16:9'=>'16:9']),$this->s('stb_theme','Tema','modern',['modern'=>'Modern','legacy'=>'Legacy']),$this->b('stb_keep_extension','Mantener extensión URL'),$this->b('stb_disable_ssl','Desactivar SSL'),$this->b('stb_load_startup','Cargar canales al iniciar'),$this->b('stb_disable_token','Desactivar token MAG'),$this->a('stb_allowed_types','Tipos STB permitidos'),$this->a('stb_recording_types','Tipos STB con grabación'),$this->t('stb_speedtest_url','URL speedtest','https://speed.hetzner.de/100MB.bin'),$this->a('stb_information','Mensaje informativo')]
 ]],
 'logs'=>['label'=>'Retención de logs','sections'=>[
  'Políticas'=>[$this->b('activity_logs','Logs de actividad',true),$this->n('activity_logs_days','Conservar actividad (días)',7,1,3650),$this->b('client_logs','Logs de clientes',true),$this->n('client_logs_days','Conservar clientes (días)',7,1,3650),$this->b('login_logs','Logs de login',true),$this->n('login_logs_days','Conservar login (días)',7,1,3650),$this->b('stream_error_logs','Logs de errores de stream',true),$this->n('stream_error_hours','Conservar errores (horas)',1,1,8760),$this->b('stream_restart_logs','Logs de reinicios',true),$this->n('stream_restart_hours','Conservar reinicios (horas)',1,1,8760)]
 ]]
 ];}
 public function values():array{$out=[];foreach($this->db->query('SELECT setting_key,setting_value,is_secret FROM system_settings') as $r)$out[$r['setting_key']]=$r['is_secret']?'':json_decode($r['setting_value']??'null',true);return $out;}
 public function save(string $tab,array $input):void{$defs=$this->definitions();if(!isset($defs[$tab]))throw new RuntimeException('Pestaña inválida.');$allowed=[];foreach($defs[$tab]['sections'] as $fields)foreach($fields as $f)$allowed[$f['key']]=$f;$s=$this->db->prepare('INSERT INTO system_settings(setting_key,setting_value,secret_ciphertext,is_secret,updated_by) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),secret_ciphertext=COALESCE(VALUES(secret_ciphertext),secret_ciphertext),is_secret=VALUES(is_secret),updated_by=VALUES(updated_by)');foreach($allowed as $key=>$f){if(($f['enabled']??true)===false)continue;$value=$f['type']==='checkbox'?isset($input[$key]):($input[$key]??$f['default']);$value=$this->validate($f,$value);$secret=$f['type']==='password';if($secret&&$value==='')continue;$s->execute([$key,$secret?null:json_encode($value,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$secret?$this->cipher->encrypt((string)$value):null,$secret,Auth::id()]);}$this->audit->record('settings.updated','settings',null,['tab'=>$tab,'count'=>count($allowed)]);}
 private function validate(array $f,mixed $v):mixed{if($f['type']==='checkbox')return(bool)$v;if($f['type']==='number'){$n=(int)$v;if($n<$f['min']||$n>$f['max'])throw new RuntimeException($f['label'].' fuera de rango.');return$n;}if($f['type']==='select'&&!array_key_exists((string)$v,$f['options']))throw new RuntimeException($f['label'].' inválido.');$v=trim((string)$v);if(strlen($v)>10000)throw new RuntimeException($f['label'].' demasiado largo.');return$v;}
 private function t($k,$l,$d=''):array{return['key'=>$k,'label'=>$l,'type'=>'text','default'=>$d];}private function a($k,$l,$d=''):array{return['key'=>$k,'label'=>$l,'type'=>'textarea','default'=>$d];}private function p($k,$l):array{return['key'=>$k,'label'=>$l,'type'=>'password','default'=>''];}private function b($k,$l,$d=false,$enabled=true):array{return['key'=>$k,'label'=>$l,'type'=>'checkbox','default'=>$d,'enabled'=>$enabled];}private function n($k,$l,$d,$min,$max):array{return['key'=>$k,'label'=>$l,'type'=>'number','default'=>$d,'min'=>$min,'max'=>$max];}private function s($k,$l,$d,$o):array{return['key'=>$k,'label'=>$l,'type'=>'select','default'=>$d,'options'=>$o];}
}
