<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use App\Security\DeviceCredentialCipher;use PDO;use RuntimeException;use Throwable;
final readonly class LiveChannelService
{
 public function __construct(private PDO $db,private AuditRepository $audit,private DeviceCredentialCipher $cipher){}
 public function create(array $input):int
 {
  $title=trim((string)($input['title']??''));if($title===''||strlen($title)>255)throw new RuntimeException('Título inválido.');
  $url=$this->url((string)($input['source_url']??''));$slug=$this->slug($title).'-'.substr(bin2hex(random_bytes(4)),0,8);$headers=$this->headers((string)($input['http_headers']??''));
  $this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO content_items(type,category_id,title,slug,status) VALUES('live',?,?,?,'draft')");$s->execute([(int)($input['category_id']??0)?:null,$title,$slug]);$id=(int)$this->db->lastInsertId();
   $this->db->prepare('INSERT INTO live_channels(content_item_id,channel_number,logo_url,country,language,epg_channel_id,delivery_mode,transcode_enabled,assigned_server_id,preferred_server_id,monitoring_enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,(int)($input['channel_number']??0)?:null,trim((string)($input['logo_url']??''))?:null,strtoupper(trim((string)($input['country']??'')))?:null,trim((string)($input['language']??''))?:null,trim((string)($input['epg_channel_id']??''))?:null,($input['delivery_mode']??'on_demand')==='always_on'?'always_on':'on_demand',isset($input['transcode_enabled'])?1:0,(int)($input['assigned_server_id']??0)?:null,(int)($input['preferred_server_id']??0)?:null,1]);
   $this->insertSource($id,['name'=>'Principal','source_url'=>$url,'priority'=>1,'authorized'=>isset($input['authorized']),'http_headers'=>$headers,'user_agent'=>$input['user_agent']??null,'referer'=>$input['referer']??null,'cookies'=>$input['cookies']??null,'timeout_seconds'=>$input['timeout_seconds']??15]);
   $this->audit->record('live_channel.created','content_item',$id,['title'=>$title]);$this->db->commit();return $id;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
 public function addSource(int $channelId,array $input):void{$exists=$this->db->prepare("SELECT 1 FROM content_items WHERE id=? AND type='live'");$exists->execute([$channelId]);if(!$exists->fetchColumn())throw new RuntimeException('Canal no encontrado.');$this->insertSource($channelId,['name'=>trim((string)($input['name']??'Respaldo')),'source_url'=>$this->url((string)($input['source_url']??'')),'priority'=>(int)($input['priority']??100),'authorized'=>isset($input['authorized']),'http_headers'=>$this->headers((string)($input['http_headers']??'')),'user_agent'=>$input['user_agent']??null,'referer'=>$input['referer']??null,'cookies'=>$input['cookies']??null,'timeout_seconds'=>$input['timeout_seconds']??15]);$this->audit->record('stream_source.created','content_item',$channelId,['authorized'=>isset($input['authorized'])]);}
 private function insertSource(int $channelId,array $data):void{$timeout=max(3,min(120,(int)$data['timeout_seconds']));$cookies=trim((string)($data['cookies']??''));$s=$this->db->prepare('INSERT INTO stream_sources(channel_id,name,source_url,priority,authorized,http_headers,user_agent,referer,cookies_ciphertext,timeout_seconds) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([$channelId,$data['name']?:'Fuente',(string)$data['source_url'],max(1,(int)$data['priority']),(bool)$data['authorized']?1:0,$data['http_headers']?json_encode($data['http_headers'],JSON_THROW_ON_ERROR):null,trim((string)$data['user_agent'])?:null,trim((string)$data['referer'])?:null,$cookies===''?null:$this->cipher->encrypt($cookies),$timeout]);}
 private function url(string $url):string{$url=trim($url);$parts=parse_url($url);if(!$parts||!in_array(strtolower((string)($parts['scheme']??'')),['http','https'],true)||empty($parts['host']))throw new RuntimeException('La fuente debe ser una URL HTTP(S) válida.');if(isset($parts['user'])||isset($parts['pass']))throw new RuntimeException('No incluyas credenciales dentro de la URL.');return $url;}
 private function headers(string $json):array{if(trim($json)==='')return [];$data=json_decode($json,true,32,JSON_THROW_ON_ERROR);if(!is_array($data))throw new RuntimeException('Headers inválidos.');foreach($data as $name=>$value)if(!preg_match('/^[A-Za-z0-9-]{1,64}$/',(string)$name)||!is_scalar($value))throw new RuntimeException('Header inválido.');return $data;}
 private function slug(string $title):string{$slug=strtolower(trim((string)preg_replace('/[^A-Za-z0-9]+/','-',$title),'-'));return $slug?:'channel';}
}
