<?php
declare(strict_types=1);
namespace App\Services;
use PDO;use RuntimeException;use Throwable;
final readonly class MediaStatusService
{
 public function __construct(private PDO $db,private TaskQueueService $queue,private FfprobeAnalyzer $probe,private SshProvisioner $ssh){}
 public function queueDue():int{$ids=$this->db->query("SELECT f.id FROM content_files f JOIN content_items c ON c.id=f.content_item_id WHERE c.type IN ('movie','episode') AND (f.last_checked_at IS NULL OR f.last_checked_at<DATE_SUB(NOW(),INTERVAL 6 HOUR)) ORDER BY f.last_checked_at LIMIT 200")->fetchAll(PDO::FETCH_COLUMN);$slot=(int)floor(time()/21600);foreach($ids as $id)$this->queue->enqueue('validate_media_file',['file_id'=>(int)$id],80,'media-status-'.$id.'-'.$slot);return count($ids);}
 public function validate(int $fileId):array
 {
  $q=$this->db->prepare("SELECT f.id,f.content_item_id,f.relative_path,f.server_id,l.mount_path,l.server_id library_server FROM content_files f JOIN storage_libraries l ON l.id=f.library_id JOIN content_items c ON c.id=f.content_item_id AND c.type IN ('movie','episode') WHERE f.id=?");$q->execute([$fileId]);$file=$q->fetch()?:throw new RuntimeException('Archivo multimedia no encontrado.');$server=(int)($file['server_id']?:$file['library_server']);try{if($server){$path=rtrim((string)$file['mount_path'],'/').'/'.ltrim((string)$file['relative_path'],'/');$result=$this->ssh->mediaTask($server,['mode'=>'validate','allowed_roots'=>[$file['mount_path']],'files'=>[['id'=>$fileId,'path'=>$path]]]);$item=$result['items'][0]??null;if(!$item||empty($item['ok']))throw new RuntimeException((string)($item['error']??'Validación remota fallida.'));$probe=$item['probe']??null;$size=$item['size']??null;}else{$candidate=rtrim((string)$file['mount_path'],DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,(string)$file['relative_path']);$analysis=$this->probe->inspect((string)$file['mount_path'],$candidate);$probe=$analysis['probe'];$size=$analysis['size_bytes'];}$this->db->prepare("UPDATE content_files SET status='available',size_bytes=?,probe_data=?,last_checked_at=NOW() WHERE id=?")->execute([$size,json_encode($probe,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$fileId]);$this->db->prepare("UPDATE content_items SET status=IF(status='missing','active',status) WHERE id=?")->execute([$file['content_item_id']]);return ['file_id'=>$fileId,'status'=>'available','server_id'=>$server?:null];}catch(Throwable $e){$missing=str_contains(strtolower($e->getMessage()),'missing')||str_contains(strtolower($e->getMessage()),'inexistente');$status=$missing?'missing':'invalid';$this->db->prepare('UPDATE content_files SET status=?,last_checked_at=NOW() WHERE id=?')->execute([$status,$fileId]);$q=$this->db->prepare("SELECT COUNT(*) FROM content_files WHERE content_item_id=? AND status='available'");$q->execute([$file['content_item_id']]);if(!(int)$q->fetchColumn())$this->db->prepare("UPDATE content_items SET status='missing' WHERE id=?")->execute([$file['content_item_id']]);return ['file_id'=>$fileId,'status'=>$status,'error'=>substr($e->getMessage(),0,500)];}
 }
}
