<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use PDO;use RuntimeException;
final readonly class MediaLibraryService
{
 public function __construct(private PDO $db,private TaskQueueService $queue,private AuditRepository $audit){}
 public function create(array $input):int{$name=trim((string)($input['name']??''));$type=(string)($input['type']??'mounted');$content=(string)($input['content_type']??'mixed');$path=rtrim(str_replace('\\','/',trim((string)($input['mount_path']??''))),'/');if($name===''||strlen($name)>150)throw new RuntimeException('Nombre de biblioteca inválido.');if(!in_array($type,['local','nfs','smb','mounted'],true)||!in_array($content,['mixed','movie','series'],true))throw new RuntimeException('Tipo de biblioteca inválido.');if(!str_starts_with($path,'/')||$path==='/'||str_contains($path,"\0")||preg_match('#(?:^|/)\.\.(?:/|$)#',$path))throw new RuntimeException('Usa una ruta absoluta específica, nunca / ni rutas con ..');$server=(int)($input['server_id']??0)?:null;$s=$this->db->prepare('INSERT INTO storage_libraries(name,type,mount_path,content_type,priority,min_free_bytes,active,server_id) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$name,$type,$path,$content,max(1,(int)($input['priority']??100)),max(1073741824,(int)($input['min_free_gb']??10)*1073741824),isset($input['active'])?1:0,$server]);$id=(int)$this->db->lastInsertId();$this->audit->record('storage.library_created','storage_library',$id,['name'=>$name,'type'=>$type,'server_id'=>$server,'path'=>$path]);return $id;}
 public function scan(int $id,string $type):string{if(!in_array($type,['movie','series'],true))throw new RuntimeException('Escaneo inválido.');$s=$this->db->prepare('SELECT active,server_id FROM storage_libraries WHERE id=?');$s->execute([$id]);$l=$s->fetch()?:throw new RuntimeException('Biblioteca no encontrada.');if(!(int)$l['active'])throw new RuntimeException('Activa primero la biblioteca.');if($l['server_id']!==null)throw new RuntimeException('Esta biblioteca debe escanearse mediante el agente del balanceador. No se ejecutará desde el servidor principal.');$job=$this->queue->enqueue($type==='series'?'import_series':'import_movies',['library_id'=>$id],20,'library-'.$id.'-'.$type.'-'.time());$this->audit->record('storage.scan_queued','storage_library',$id,['job_id'=>$job,'type'=>$type]);return $job;}
}
