<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use PDO;use RuntimeException;use Throwable;
final readonly class MovieService
{
 public function __construct(private PDO $db,private RemoteMediaService $remote,private AuditRepository $audit){}
 public function create(array $in):int{$title=trim((string)($in['title']??''));$libraryId=(int)($in['library_id']??0);$relative=$this->relative((string)($in['relative_path']??''));if($title===''||strlen($title)>255||$libraryId<1||$relative==='')throw new RuntimeException('Completa nombre, biblioteca y archivo.');$l=$this->library($libraryId);$year=(int)($in['year']??0);if($year&&($year<1888||$year>(int)date('Y')+5))throw new RuntimeException('Año inválido.');$this->db->beginTransaction();try{$slug=$this->slug($title).'-'.substr(hash('sha256',$libraryId.'|'.$relative),0,10);$this->db->prepare("INSERT INTO content_items(type,category_id,title,slug,tmdb_id,metadata,status) VALUES('movie',?,?,?,?,?,'draft')")->execute([(int)($in['category_id']??0)?:null,$title,$slug,(int)($in['tmdb_id']??0)?:null,json_encode(['needs_validation'=>true,'tmdb_language'=>$in['tmdb_language']??'es-ES'])]);$id=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO movies(content_item_id,original_title,description,release_year,genres,cast_members,director,rating,language,country,poster_url,backdrop_url,trailer_url,direct_source,direct_stream,native_frames,create_symlink,remove_subtitles,subtitle_location,transcode_profile,target_container,process_movie) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,trim((string)($in['original_title']??''))?:null,trim((string)($in['description']??''))?:null,$year?:null,$this->list($in['genres']??''),$this->list($in['cast']??''),trim((string)($in['director']??''))?:null,trim((string)($in['rating']??''))?:null,trim((string)($in['language']??''))?:null,strtoupper(trim((string)($in['country']??'')))?:null,trim((string)($in['poster_url']??''))?:null,trim((string)($in['backdrop_url']??''))?:null,trim((string)($in['trailer_url']??''))?:null,isset($in['direct_source']),isset($in['direct_stream']),isset($in['native_frames']),isset($in['create_symlink']),isset($in['remove_subtitles']),trim((string)($in['subtitle_location']??''))?:null,trim((string)($in['transcode_profile']??''))?:null,trim((string)($in['target_container']??''))?:null,isset($in['process_movie'])]);$this->db->prepare("INSERT INTO content_files(public_id,content_item_id,library_id,server_id,relative_path,status) VALUES(?,?,?,?,?,'pending')")->execute([bin2hex(random_bytes(16)),$id,$libraryId,$l['server_id']?:null,$relative]);foreach((array)($in['package_ids']??[]) as $package)if((int)$package>0)$this->db->prepare('INSERT IGNORE INTO package_content_items(package_id,content_item_id) VALUES(?,?)')->execute([(int)$package,$id]);$this->db->commit();if($l['server_id'])$this->remote->request($libraryId,'validate');$this->audit->record('movie.created','content_item',$id,['library_id'=>$libraryId,'server_id'=>$l['server_id']]);return $id;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function bulkUpdate(array $in):int
 {
  $ids=array_values(array_unique(array_filter(array_map('intval',(array)($in['ids']??[])),fn($id)=>$id>0)));if(!$ids||count($ids)>500)throw new RuntimeException('Selecciona entre 1 y 500 películas o episodios.');$status=(string)($in['set_status']??'');$category=(string)($in['set_category']??'');$server=(string)($in['set_server']??'');$package=(int)($in['package_id']??0);$packageAction=(string)($in['package_action']??'');if($status===''&&$category===''&&$server===''&&($package<1||!in_array($packageAction,['add','remove'],true)))throw new RuntimeException('Selecciona al menos un cambio.');if($status!==''&&!in_array($status,['draft','active','disabled','missing'],true))throw new RuntimeException('Estado no válido.');
  $marks=implode(',',array_fill(0,count($ids),'?'));$check=$this->db->prepare("SELECT id FROM content_items WHERE id IN ($marks) AND type IN ('movie','episode')");$check->execute($ids);$valid=array_map('intval',$check->fetchAll(PDO::FETCH_COLUMN));if(count($valid)!==count($ids))throw new RuntimeException('La selección contiene elementos no válidos.');$marks=implode(',',array_fill(0,count($valid),'?'));
  $this->db->beginTransaction();try{if($status!==''){$q=$this->db->prepare("UPDATE content_items SET status=? WHERE id IN ($marks)");$q->execute(array_merge([$status],$valid));}if($category!==''){$categoryId=(int)$category?:null;if($categoryId){$q=$this->db->prepare("SELECT COUNT(*) FROM categories WHERE id=? AND type IN ('movie','series') AND active=1");$q->execute([$categoryId]);if(!(int)$q->fetchColumn())throw new RuntimeException('Categoría no válida.');}$q=$this->db->prepare("UPDATE content_items SET category_id=? WHERE id IN ($marks)");$q->execute(array_merge([$categoryId],$valid));}if($server!==''){$serverId=(int)$server?:null;if($serverId){$q=$this->db->prepare('SELECT COUNT(*) FROM servers WHERE id=?');$q->execute([$serverId]);if(!(int)$q->fetchColumn())throw new RuntimeException('Servidor no válido.');}$q=$this->db->prepare("UPDATE content_files SET server_id=? WHERE content_item_id IN ($marks)");$q->execute(array_merge([$serverId],$valid));}if($package>0&&in_array($packageAction,['add','remove'],true)){if($packageAction==='add'){$q=$this->db->prepare('INSERT IGNORE INTO package_content_items(package_id,content_item_id) VALUES(?,?)');foreach($valid as $id)$q->execute([$package,$id]);}else{$q=$this->db->prepare("DELETE FROM package_content_items WHERE package_id=? AND content_item_id IN ($marks)");$q->execute(array_merge([$package],$valid));}}$this->db->commit();$this->audit->record('media.bulk_updated','content_item',null,['count'=>count($valid),'ids'=>$valid,'status'=>$status?:null,'category'=>$category,'server'=>$server,'package_id'=>$package?:null,'package_action'=>$packageAction?:null]);return count($valid);}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
 public function bulkDelete(array $in):int
 {
  if(trim((string)($in['confirmation']??''))!=='ELIMINAR')throw new RuntimeException('Escribe ELIMINAR para confirmar la operación.');$ids=array_values(array_unique(array_filter(array_map('intval',(array)($in['ids']??[])),fn($id)=>$id>0)));if(!$ids||count($ids)>500)throw new RuntimeException('Selecciona entre 1 y 500 películas o episodios.');$marks=implode(',',array_fill(0,count($ids),'?'));$q=$this->db->prepare("SELECT id,title,type FROM content_items WHERE id IN ($marks) AND type IN ('movie','episode') FOR UPDATE");
  $this->db->beginTransaction();try{$q->execute($ids);$items=$q->fetchAll();if(count($items)!==count($ids))throw new RuntimeException('La selección contiene elementos no válidos.');$active=$this->db->prepare("SELECT COUNT(*) FROM active_sessions WHERE content_item_id IN ($marks) AND disconnected_at IS NULL");$active->execute($ids);if((int)$active->fetchColumn()>0)throw new RuntimeException('No se puede eliminar contenido que está reproduciéndose. Detén primero sus sesiones activas.');$history=$this->db->prepare("UPDATE active_sessions SET content_item_id=NULL WHERE content_item_id IN ($marks)");$history->execute($ids);$delete=$this->db->prepare("DELETE FROM content_items WHERE id IN ($marks) AND type IN ('movie','episode')");$delete->execute($ids);$count=$delete->rowCount();$this->db->commit();$this->audit->record('media.bulk_deleted','content_item',null,['count'=>$count,'items'=>$items,'physical_files_deleted'=>false]);return $count;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
 private function library(int $id):array{$s=$this->db->prepare('SELECT * FROM storage_libraries WHERE id=? AND active=1');$s->execute([$id]);return $s->fetch()?:throw new RuntimeException('Biblioteca no disponible.');}
 private function relative(string $p):string{$p=ltrim(str_replace('\\','/',trim($p)),'/');if($p===''||str_contains($p,"\0")||preg_match('#(?:^|/)\.\.(?:/|$)#',$p))throw new RuntimeException('Ruta inválida.');return $p;}
 private function list(mixed $v):string{return json_encode(array_values(array_filter(array_map('trim',explode(',',(string)$v)))),JSON_UNESCAPED_UNICODE);}
 private function slug(string $v):string{$s=strtolower(trim((string)preg_replace('/[^A-Za-z0-9]+/','-',$v),'-'));return $s?:'movie';}
}
