<?php
declare(strict_types=1);namespace App\Services;use App\Repositories\AuditRepository;use App\Security\Auth;use PDO;use RuntimeException;
final readonly class PlaybackControlService{
 public function __construct(private PDO $db,private AuditRepository $audit){}
 public function disconnect(string $id):int{if(!preg_match('/^[a-f0-9-]{16,64}$/i',$id))throw new RuntimeException('Sesión inválida.');$s=$this->db->prepare("UPDATE active_sessions SET disconnected_at=NOW(),disconnect_reason='admin_kill' WHERE id=? AND disconnected_at IS NULL");$s->execute([$id]);$this->audit->record('playback.session_killed','active_session',null,['session_id'=>$id]);return $s->rowCount();}
 public function killContent(int $id):int{if($id<1)throw new RuntimeException('Contenido inválido.');$s=$this->db->prepare("UPDATE active_sessions SET disconnected_at=NOW(),disconnect_reason='content_killed' WHERE content_item_id=? AND disconnected_at IS NULL");$s->execute([$id]);$this->audit->record('playback.content_killed','content_item',$id,['sessions'=>$s->rowCount()]);return $s->rowCount();}
 public function banLine(int $id):void{if($id<1)throw new RuntimeException('Línea inválida.');$this->db->beginTransaction();try{$this->db->prepare("UPDATE end_user_accounts SET status='blocked' WHERE id=? AND deleted_at IS NULL")->execute([$id]);$this->db->prepare("UPDATE active_sessions SET disconnected_at=NOW(),disconnect_reason='line_banned' WHERE account_id=? AND disconnected_at IS NULL")->execute([$id]);$this->db->commit();$this->audit->record('account.banned','end_user_account',$id);}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function banIp(string $ip):void{if(!filter_var($ip,FILTER_VALIDATE_IP))throw new RuntimeException('IP inválida.');$this->db->beginTransaction();try{$this->db->prepare("INSERT INTO blocked_ips(ip,reason,source,active,created_by) VALUES(?,'Bloqueada desde conexiones activas','manual',1,?) ON DUPLICATE KEY UPDATE active=1,reason=VALUES(reason),created_by=VALUES(created_by),expires_at=NULL")->execute([$ip,Auth::id()]);$this->db->prepare("UPDATE active_sessions SET disconnected_at=NOW(),disconnect_reason='ip_banned' WHERE ip=? AND disconnected_at IS NULL")->execute([$ip]);$this->db->commit();$this->audit->record('security.ip_banned','ip',null,['ip'=>$ip]);}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
}
