<?php
declare(strict_types=1);
namespace App\Services;
use App\Domain\Media\EpisodeFilenameParser;use App\Repositories\AuditRepository;use App\Security\Auth;use PDO;use RuntimeException;use Throwable;
final readonly class RemoteMediaService
{
 public function __construct(private PDO $db,private TaskQueueService $queue,private SshProvisioner $ssh,private AuditRepository $audit,private EpisodeFilenameParser $episodes){}
 public function request(int $libraryId,string $operation,?int $targetServer=null):int
 {
  if(!in_array($operation,['inventory','scan','validate','apply_links','publish'],true))throw new RuntimeException('Operación multimedia inválida.');$l=$this->library($libraryId);$server=$operation==='apply_links'?(int)$targetServer:(int)$l['server_id'];if($server<1)throw new RuntimeException('Selecciona una biblioteca y un balanceador remotos.');
  $this->db->prepare('INSERT INTO media_remote_runs(server_id,library_id,operation,requested_by) VALUES(?,?,?,?)')->execute([$server,$libraryId,$operation,Auth::id()]);$id=(int)$this->db->lastInsertId();$agent=$this->db->prepare("SELECT agent_status FROM servers WHERE id=?");$agent->execute([$server]);if($agent->fetchColumn()==='ok'){$payload=$this->taskPayload($id);$task=bin2hex(random_bytes(16));$this->db->prepare('INSERT INTO node_media_tasks(id,server_id,run_id,payload) VALUES(?,?,?,?)')->execute([$task,$server,$id,json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)]);}else{$type=match($operation){'inventory'=>'inventory_media_links','scan'=>'scan_remote_media','validate'=>'validate_remote_media',default=>'apply_media_links'};$job=$this->queue->enqueue($type,['run_id'=>$id],10,'remote-media-'.$id);$this->db->prepare('UPDATE media_remote_runs SET job_id=? WHERE id=?')->execute([$job,$id]);}$this->audit->record('storage.remote_operation_queued','media_remote_run',$id,['operation'=>$operation,'server_id'=>$server,'transport'=>isset($task)?'agent_api':'ssh_bootstrap']);return $id;
 }
 public function run(int $runId):array
 {
  $s=$this->db->prepare('SELECT r.*,l.mount_path FROM media_remote_runs r JOIN storage_libraries l ON l.id=r.library_id WHERE r.id=?');$s->execute([$runId]);$run=$s->fetch()?:throw new RuntimeException('Operación remota no encontrada.');$this->db->prepare("UPDATE media_remote_runs SET status='running',started_at=NOW(),error_message=NULL WHERE id=?")->execute([$runId]);
  try{$roots=$this->roots((int)$run['server_id']);$task=['mode'=>$run['operation'],'allowed_roots'=>$roots];if(in_array($run['operation'],['inventory','scan'],true))$task['root']=$run['mount_path'];elseif($run['operation']==='validate')$task['files']=$this->files((int)$run['library_id']);elseif($run['operation']==='publish')$task['links']=$this->deliveryLinks((int)$run['library_id']);else$task['links']=$this->links((int)$run['library_id']);$result=$this->ssh->mediaTask((int)$run['server_id'],$task);$summary=$this->store($run,$result);$this->db->prepare("UPDATE media_remote_runs SET status='completed',summary=?,completed_at=NOW() WHERE id=?")->execute([json_encode($summary),$runId]);return $summary;}catch(Throwable $e){$this->db->prepare("UPDATE media_remote_runs SET status='failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($e->getMessage(),0,65535),$runId]);throw $e;}
 }
 public function acceptNodeResult(int $runId,array $result):array{$s=$this->db->prepare('SELECT r.*,l.mount_path FROM media_remote_runs r JOIN storage_libraries l ON l.id=r.library_id WHERE r.id=?');$s->execute([$runId]);$run=$s->fetch()?:throw new RuntimeException('Operación remota no encontrada.');$summary=$this->store($run,$result);$this->db->prepare("UPDATE media_remote_runs SET status='completed',summary=?,completed_at=NOW() WHERE id=?")->execute([json_encode($summary),$runId]);return $summary;}
 public function failNodeRun(int $runId,string $error):void{$this->db->prepare("UPDATE media_remote_runs SET status='failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($error,0,65535),$runId]);}
 private function taskPayload(int $runId):array{$s=$this->db->prepare('SELECT r.*,l.mount_path FROM media_remote_runs r JOIN storage_libraries l ON l.id=r.library_id WHERE r.id=?');$s->execute([$runId]);$run=$s->fetch()?:throw new RuntimeException('Operación no encontrada.');$task=['mode'=>$run['operation'],'allowed_roots'=>$this->roots((int)$run['server_id'])];if(in_array($run['operation'],['inventory','scan'],true))$task['root']=$run['mount_path'];elseif($run['operation']==='validate')$task['files']=$this->files((int)$run['library_id']);elseif($run['operation']==='publish')$task['links']=$this->deliveryLinks((int)$run['library_id']);else$task['links']=$this->links((int)$run['library_id']);return $task;}
 private function store(array $run,array $result):array
 {
  $ok=0;$failed=0;
  if($run['operation']==='inventory'){$s=$this->db->prepare('INSERT INTO media_symlink_inventory(run_id,library_id,link_path,target_path,valid,error_message) VALUES(?,?,?,?,?,?)');foreach($result['items']??[] as $x){$s->execute([$run['id'],$run['library_id'],$x['link'],$x['target'],$x['valid']?1:0,$x['error']]);$x['valid']?$ok++:$failed++;}}
  elseif($run['operation']==='scan'){foreach($result['items']??[] as $x){if(empty($x['ok'])){$failed++;continue;}$this->importRemote($run,$x)?$ok++:$failed++;}}
  elseif($run['operation']==='validate'){$s=$this->db->prepare("UPDATE content_files SET status=?,size_bytes=?,probe_data=?,last_checked_at=NOW() WHERE id=?");foreach($result['items']??[] as $x){$valid=!empty($x['ok']);$s->execute([$valid?'available':'invalid',$valid?($x['size']??null):null,$valid?json_encode($x['probe']??null):json_encode(['error'=>$x['error']??'failed']),$x['id']]);if($valid){$this->db->prepare("UPDATE content_items c JOIN content_files f ON f.content_item_id=c.id SET c.status='active' WHERE f.id=?")->execute([$x['id']]);$ok++;}else$failed++;}}
  else{foreach($result['items']??[] as $x){if(!empty($x['ok'])){if($run['operation']==='apply_links')$this->db->prepare('UPDATE media_symlink_inventory SET applied_server_id=?,applied_at=NOW() WHERE id=?')->execute([$run['server_id'],$x['id']]);$ok++;}else$failed++;}}
  $summary=['processed'=>$ok+$failed,'valid'=>$ok,'failed'=>$failed];if($ok>0&&in_array($run['operation'],['scan','validate'],true))$summary['publish_run']=$this->queueDelivery((int)$run['library_id'],(int)$run['server_id'],(int)$run['requested_by']);return $summary;
 }
 private function importRemote(array $run,array $x):bool
 {
  $relative=str_replace('\\','/',trim((string)($x['relative']??''),'/'));if($relative==='')return false;$known=$this->db->prepare('SELECT 1 FROM content_files WHERE library_id=? AND relative_path=?');$known->execute([$run['library_id'],$relative]);if($known->fetchColumn())return true;$library=$this->library((int)$run['library_id']);$type=$library['content_type']==='movie'?'movie':'series';$this->db->beginTransaction();try{if($type==='series'){$p=$this->episodes->parse($relative);if(!$p||empty($p['series_title'])){$this->db->rollBack();return false;}$slug=$this->slug($p['series_title']);$s=$this->db->prepare("SELECT id FROM content_items WHERE type='series' AND slug=?");$s->execute([$slug]);$series=(int)($s->fetchColumn()?:0);if(!$series){$this->db->prepare("INSERT INTO content_items(type,title,slug,status) VALUES('series',?,?,'active')")->execute([$p['series_title'],$slug]);$series=(int)$this->db->lastInsertId();}$this->db->prepare('INSERT INTO series_seasons(series_id,season_number,title) VALUES(?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)')->execute([$series,$p['season'],'Temporada '.$p['season']]);$season=(int)$this->db->lastInsertId();$title=$p['series_title'].' S'.str_pad((string)$p['season'],2,'0',STR_PAD_LEFT).'E'.str_pad((string)$p['episode'],2,'0',STR_PAD_LEFT);$episodeSlug=$slug.'-s'.$p['season'].'e'.$p['episode'];$this->db->prepare("INSERT INTO content_items(type,title,slug,status) VALUES('episode',?,?,'active') ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='active'")->execute([$title,$episodeSlug]);$content=(int)$this->db->lastInsertId();$this->db->prepare('INSERT IGNORE INTO series_episodes(season_id,content_item_id,episode_number) VALUES(?,?,?)')->execute([$season,$content,$p['episode']]);}else{$title=trim((string)preg_replace('/\b(19|20)\d{2}\b.*$/','',(string)preg_replace('/[._]+/',' ',pathinfo($relative,PATHINFO_FILENAME))));if($title===''){$this->db->rollBack();return false;}$slug=$this->slug($title).'-'.substr(hash('sha256',$relative),0,10);$this->db->prepare("INSERT INTO content_items(type,title,slug,status) VALUES('movie',?,?,'active') ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='active'")->execute([$title,$slug]);$content=(int)$this->db->lastInsertId();$duration=(int)round((float)($x['probe']['format']['duration']??0));$this->db->prepare('INSERT IGNORE INTO movies(content_item_id,original_title,duration_seconds) VALUES(?,?,?)')->execute([$content,$title,$duration?:null]);}$this->db->prepare("INSERT INTO content_files(public_id,content_item_id,library_id,server_id,relative_path,size_bytes,probe_data,status,last_checked_at) VALUES(?,?,?,?,?,?,?,'available',NOW())")->execute([bin2hex(random_bytes(16)),$content,$run['library_id'],$run['server_id'],$relative,$x['size']??null,json_encode($x['probe']??null)]);$this->db->commit();return true;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
 private function slug(string $value):string{$s=strtolower(trim((string)preg_replace('/[^A-Za-z0-9]+/','-',$value),'-'));return $s?:'media';}
 private function library(int $id):array{$s=$this->db->prepare('SELECT * FROM storage_libraries WHERE id=?');$s->execute([$id]);return $s->fetch()?:throw new RuntimeException('Biblioteca no encontrada.');}
 private function roots(int $server):array{$s=$this->db->prepare('SELECT mount_path FROM storage_libraries WHERE server_id=? AND active=1');$s->execute([$server]);$roots=$s->fetchAll(PDO::FETCH_COLUMN);if(!$roots)throw new RuntimeException('El balanceador no tiene bibliotecas activas autorizadas.');return array_values($roots);}
 private function files(int $library):array{$s=$this->db->prepare('SELECT id,CONCAT((SELECT CONCAT(TRIM(TRAILING \'/\' FROM mount_path),\'/\') FROM storage_libraries WHERE id=?),relative_path) path FROM content_files WHERE library_id=?');$s->execute([$library,$library]);return $s->fetchAll();}
 private function links(int $library):array{$s=$this->db->prepare('SELECT i.id,i.link_path link,i.target_path target FROM media_symlink_inventory i JOIN media_remote_runs r ON r.id=i.run_id WHERE i.library_id=? AND i.valid=1 AND i.applied_at IS NULL ORDER BY i.id');$s->execute([$library]);return $s->fetchAll();}
 private function deliveryLinks(int $library):array{$s=$this->db->prepare("SELECT f.id,f.public_id,CONCAT(TRIM(TRAILING '/' FROM l.mount_path),'/',f.relative_path) target FROM content_files f JOIN storage_libraries l ON l.id=f.library_id WHERE f.library_id=? AND f.status='available'");$s->execute([$library]);return $s->fetchAll();}
 private function queueDelivery(int $library,int $server,int $user):int{$this->db->prepare("INSERT INTO media_remote_runs(server_id,library_id,operation,requested_by) VALUES(?,?,'publish',?)")->execute([$server,$library,$user]);$run=(int)$this->db->lastInsertId();$status=$this->db->prepare('SELECT agent_status FROM servers WHERE id=?');$status->execute([$server]);if($status->fetchColumn()==='ok'){$task=bin2hex(random_bytes(16));$this->db->prepare('INSERT INTO node_media_tasks(id,server_id,run_id,payload) VALUES(?,?,?,?)')->execute([$task,$server,$run,json_encode($this->taskPayload($run),JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)]);}else{$job=$this->queue->enqueue('apply_media_links',['run_id'=>$run],10,'remote-media-'.$run);$this->db->prepare('UPDATE media_remote_runs SET job_id=? WHERE id=?')->execute([$job,$run]);}return $run;}
}
