<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use PDO;use RuntimeException;
final readonly class StreamMonitorService
{
 public function __construct(private PDO $db,private TaskQueueService $queue,private AuditRepository $audit){}
 public function queueDue():int{$rows=$this->db->query("SELECT s.id FROM stream_sources s JOIN live_channels l ON l.content_item_id=s.channel_id WHERE s.active=1 AND s.authorized=1 AND l.monitoring_enabled=1 AND (s.last_checked_at IS NULL OR s.last_checked_at<DATE_SUB(NOW(),INTERVAL 2 MINUTE)) ORDER BY s.last_checked_at LIMIT 500")->fetchAll(PDO::FETCH_COLUMN);foreach($rows as $id)$this->queue->enqueue('test_stream',['source_id'=>(int)$id],40,'stream-check-'.$id.'-'.date('YmdHi'));return count($rows);}
 public function check(int $sourceId):array{$s=$this->db->prepare('SELECT s.*,l.runtime_status FROM stream_sources s JOIN live_channels l ON l.content_item_id=s.channel_id WHERE s.id=? AND s.active=1 AND s.authorized=1');$s->execute([$sourceId]);$source=$s->fetch()?:throw new RuntimeException('Fuente no disponible para monitorización.');$started=microtime(true);$available=false;$error=null;$http=0;$curl=curl_init($source['source_url']);$headers=[];foreach(json_decode($source['http_headers']?:'{}',true)?:[] as $k=>$v)$headers[]=$k.': '.$v;curl_setopt_array($curl,[CURLOPT_NOBODY=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>min(10,(int)$source['timeout_seconds']),CURLOPT_TIMEOUT=>(int)$source['timeout_seconds'],CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_HTTPHEADER=>$headers,CURLOPT_USERAGENT=>$source['user_agent']?:'OrionX-Monitor/1.0',CURLOPT_REFERER=>$source['referer']?:'']);$ok=curl_exec($curl);$http=(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE);$error=curl_error($curl);curl_close($curl);$available=$ok!==false&&($http===0||$http<400);$ms=(int)round((microtime(true)-$started)*1000);$failures=$available?0:(int)$source['consecutive_failures']+1;$status=$available?'healthy':($failures>=3?'failed':'degraded');$this->db->prepare('UPDATE stream_sources SET status=?,consecutive_failures=?,last_checked_at=NOW(),last_success_at=IF(?,NOW(),last_success_at) WHERE id=?')->execute([$status,$failures,$available,$sourceId]);$this->db->prepare('INSERT INTO stream_health_checks(source_id,available,response_ms,error_code,error_message) VALUES(?,?,?,?,?)')->execute([$sourceId,$available,$ms,$available?null:('http_'.$http),$available?null:substr($error?:'HTTP '.$http,0,500)]);$this->refreshChannel((int)$source['channel_id']);if(!$available&&$failures===3&&(int)$source['auto_restart']===1)$this->restart((int)$source['channel_id'],true,'Tres comprobaciones consecutivas fallidas');return ['available'=>$available,'response_ms'=>$ms,'http_status'=>$http,'failures'=>$failures];}
 public function restart(int $channelId,bool $automatic=false,string $reason='Reinicio solicitado desde el dashboard'):void{$s=$this->db->prepare("SELECT id FROM stream_sources WHERE channel_id=? AND active=1 AND authorized=1 ORDER BY status='healthy' DESC,priority,id LIMIT 1");$s->execute([$channelId]);$source=(int)($s->fetchColumn()?:0);if(!$source)throw new RuntimeException('El canal no tiene una fuente autorizada activa.');$this->db->prepare("UPDATE live_channels SET restart_count=restart_count+1,runtime_status='unknown' WHERE content_item_id=?")->execute([$channelId]);$this->db->prepare("UPDATE stream_sources SET status='unknown',consecutive_failures=0 WHERE channel_id=?")->execute([$channelId]);$this->db->prepare('INSERT INTO stream_restart_events(channel_id,source_id,reason,automatic) VALUES(?,?,?,?)')->execute([$channelId,$source,substr($reason,0,255),$automatic]);$this->queue->enqueue('test_stream',['source_id'=>$source],10,'stream-restart-'.$channelId.'-'.time());if(!$automatic)$this->audit->record('stream.restart_requested','content_item',$channelId,['source_id'=>$source]);}
 private function refreshChannel(int $channel):void{$s=$this->db->prepare("SELECT id,status FROM stream_sources WHERE channel_id=? AND active=1 AND authorized=1 ORDER BY status='healthy' DESC,priority,id");$s->execute([$channel]);$sources=$s->fetchAll();$healthy=array_values(array_filter($sources,static fn($x)=>$x['status']==='healthy'));$runtime=$healthy?'online':(array_filter($sources,static fn($x)=>$x['status']==='degraded')?'degraded':'down');$active=$healthy[0]['id']??null;$this->db->prepare("UPDATE live_channels SET runtime_status=?,active_source_id=?,last_healthy_at=IF(?='online',NOW(),last_healthy_at),online_since=IF(?='online',COALESCE(online_since,NOW()),NULL),last_down_at=IF(?='down',NOW(),last_down_at) WHERE content_item_id=?")->execute([$runtime,$active,$runtime,$runtime,$runtime,$channel]);}
}
