<?php
declare(strict_types=1);
namespace App\Services;
use PDO;use Predis\Client as RedisClient;use RuntimeException;use Throwable;
final readonly class TaskQueueService
{
 public const TYPES=['import_movies','import_series','analyze_file','query_tmdb','download_image','test_stream','restart_stream','generate_thumbnail','move_file','sync_balancers','create_backup','cleanup_sessions','rotate_logs','send_alerts','issue_certificate','provision_balancer','sync_balancer','update_balancer','xui_import','xui_sql_upload','inventory_media_links','scan_remote_media','validate_remote_media','apply_media_links'];
 public function __construct(private PDO $db,private RedisClient $redis){}
 public function enqueue(string $type,array $payload,int $priority=100,?string $idempotencyKey=null,int $maxAttempts=3):string
 {if(!in_array($type,self::TYPES,true))throw new RuntimeException('Tipo de tarea inválido.');if($idempotencyKey!==null&&!preg_match('/^[A-Za-z0-9._:-]{1,190}$/',$idempotencyKey))throw new RuntimeException('Clave idempotente inválida.');$priority=max(1,min(1000,$priority));$id=bin2hex(random_bytes(16));try{$s=$this->db->prepare('INSERT INTO jobs(id,type,payload,priority,idempotency_key,max_attempts) VALUES(?,?,?,?,?,?)');$s->execute([$id,$type,json_encode($payload,JSON_THROW_ON_ERROR),$priority,$idempotencyKey,max(1,min(20,$maxAttempts))]);}catch(Throwable $e){if($idempotencyKey===null)throw $e;$s=$this->db->prepare('SELECT id FROM jobs WHERE type=? AND idempotency_key=?');$s->execute([$type,$idempotencyKey]);$existing=$s->fetchColumn();if(!$existing)throw $e;return (string)$existing;}$this->event($id,'queued',0,'Tarea encolada');$this->push($id,$priority,time());return $id;}
 public function reserve(string $id,string $worker):?array{$this->db->beginTransaction();try{$s=$this->db->prepare("SELECT * FROM jobs WHERE id=? AND status='pending' AND available_at<=NOW() FOR UPDATE");$s->execute([$id]);$job=$s->fetch();if(!$job){$this->db->commit();return null;}$this->db->prepare("UPDATE jobs SET status='running',attempts=attempts+1,worker=?,started_at=COALESCE(started_at,NOW()) WHERE id=?")->execute([$worker,$id]);$this->event($id,'started',(int)$job['progress'],'Reservada por '.$worker);$this->db->commit();$job['payload']=json_decode($job['payload'],true,64,JSON_THROW_ON_ERROR);$job['attempts']=(int)$job['attempts']+1;return $job;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function progress(string $id,int $progress,string $message=''):void{$progress=max(0,min(99,$progress));$this->db->prepare("UPDATE jobs SET progress=? WHERE id=? AND status='running'")->execute([$progress,$id]);$this->event($id,'progress',$progress,$message);}
 public function complete(string $id,array $result=[]):void{$this->db->prepare("UPDATE jobs SET status='completed',progress=100,error_message=NULL,finished_at=NOW() WHERE id=?")->execute([$id]);$this->event($id,'completed',100,$result?json_encode($result,JSON_THROW_ON_ERROR):'Completada');}
 public function fail(array $job,Throwable $error):void{$retry=(int)$job['attempts']<(int)$job['max_attempts'];$delay=min(300,2**min(8,(int)$job['attempts']));$status=$retry?'pending':'failed';$this->db->prepare("UPDATE jobs SET status=?,error_message=?,available_at=DATE_ADD(NOW(),INTERVAL ? SECOND),finished_at=IF(?='failed',NOW(),NULL) WHERE id=?")->execute([$status,substr($error->getMessage(),0,65535),$delay,$status,$job['id']]);$this->event($job['id'],$retry?'retrying':'failed',(int)$job['progress'],substr($error->getMessage(),0,500));if($retry)$this->push($job['id'],(int)$job['priority'],time()+$delay);}
 public function pop():?array{$items=$this->redis->zpopmin('jobs:ready',1);if(!$items)return null;$id=(string)array_key_first($items);$score=(float)$items[$id];$available=(int)floor($score/10000);if($available>time()){$this->redis->zadd('jobs:ready',[$id=>$score]);return null;}return ['id'=>$id];}
 public function recoverPending():int{$rows=$this->db->query("SELECT id,priority,UNIX_TIMESTAMP(available_at) available FROM jobs WHERE status='pending' ORDER BY priority,available_at LIMIT 1000")->fetchAll();foreach($rows as $row)$this->push($row['id'],(int)$row['priority'],(int)$row['available']);return count($rows);}
 private function push(string $id,int $priority,int $available):void{$this->redis->zadd('jobs:ready',[$id=>$available*10000+$priority]);}
 private function event(string $id,string $event,?int $progress,string $message):void{$this->db->prepare('INSERT INTO job_events(job_id,event,progress,message) VALUES(?,?,?,?)')->execute([$id,$event,$progress,substr($message,0,500)]);}
}
