<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use App\Security\Auth;use PDO;use RuntimeException;use Throwable;
final readonly class WafService
{
 public function __construct(private PDO $db,private TaskQueueService $queue,private SshProvisioner $ssh,private AuditRepository $audit){}
 public function settings(array $in):void{$mode=($in['mode']??'detection')==='blocking'?'blocking':'detection';$level=max(1,min(4,(int)($in['paranoia_level']??1)));$inbound=max(1,min(100,(int)($in['inbound_threshold']??5)));$outbound=max(1,min(100,(int)($in['outbound_threshold']??4)));$this->db->prepare('UPDATE waf_settings SET enabled=?,mode=?,paranoia_level=?,inbound_threshold=?,outbound_threshold=?,updated_by=? WHERE id=1')->execute([isset($in['enabled']),$mode,$level,$inbound,$outbound,Auth::id()]);$this->audit->record('waf.settings_updated','waf',1,['mode'=>$mode,'paranoia'=>$level]);}
 public function addRule(array $in):void{$id=(int)($in['rule_id']??0);$name=trim((string)($in['name']??''));$target=(string)($in['target']??'uri');$operator=(string)($in['operator']??'contains');$pattern=trim((string)($in['pattern']??''));$action=(string)($in['action']??'log');if($id<200000||$id>299999)throw new RuntimeException('Usa un ID de regla entre 200000 y 299999.');if($name===''||strlen($name)>150||$pattern===''||strlen($pattern)>500||preg_match('/[\r\n\x00]/',$pattern))throw new RuntimeException('Nombre o patrón no válido.');if(!in_array($target,['uri','args','headers','user_agent'],true)||!in_array($operator,['contains','regex','equals'],true)||!in_array($action,['log','block'],true))throw new RuntimeException('Configuración de regla no válida.');$this->db->prepare('INSERT INTO waf_custom_rules(rule_id,name,target,operator,pattern,action,active,created_by) VALUES(?,?,?,?,?,?,1,?)')->execute([$id,$name,$target,$operator,$pattern,$action,Auth::id()]);$this->audit->record('waf.rule_created','waf_rule',$id,['name'=>$name,'action'=>$action]);}
 public function addExclusion(array $in):void{$name=trim((string)($in['name']??''));$path=trim((string)($in['path_prefix']??''))?:null;$ip=trim((string)($in['ip']??''))?:null;$rule=(int)($in['rule_id']??0)?:null;if($name===''||strlen($name)>150||(!$path&&!$ip))throw new RuntimeException('Completa nombre y al menos una ruta o IP.');if($path&&(!str_starts_with($path,'/')||preg_match('/[\r\n"\x00]/',$path)))throw new RuntimeException('Ruta de exclusión no válida.');if($ip&&!filter_var($ip,FILTER_VALIDATE_IP))throw new RuntimeException('IP no válida.');$this->db->prepare('INSERT INTO waf_exclusions(name,path_prefix,ip,rule_id,created_by) VALUES(?,?,?,?,?)')->execute([$name,$path,$ip,$rule,Auth::id()]);$this->audit->record('waf.exclusion_created','waf_exclusion',(int)$this->db->lastInsertId(),['name'=>$name]);}
 public function toggle(string $kind,int $id):void{$table=$kind==='rule'?'waf_custom_rules':($kind==='exclusion'?'waf_exclusions':throw new RuntimeException('Tipo inválido.'));$q=$this->db->prepare("UPDATE $table SET active=NOT active WHERE id=?");$q->execute([$id]);if(!$q->rowCount())throw new RuntimeException('Registro no encontrado.');$this->audit->record('waf.'.$kind.'_toggled','waf_'.$kind,$id);}
 public function requestDeploy(?int $serverId):int{$s=$this->db->query('SELECT mode FROM waf_settings WHERE id=1')->fetch();if($serverId){$q=$this->db->prepare('SELECT COUNT(*) FROM servers WHERE id=?');$q->execute([$serverId]);if(!(int)$q->fetchColumn())throw new RuntimeException('Servidor no encontrado.');}$this->db->prepare('INSERT INTO waf_deployments(server_id,mode,requested_by) VALUES(?,?,?)')->execute([$serverId,$s['mode'],Auth::id()]);$id=(int)$this->db->lastInsertId();$job=$this->queue->enqueue('deploy_waf',['deployment_id'=>$id],3,'waf-'.$id);$this->db->prepare('UPDATE waf_deployments SET job_id=? WHERE id=?')->execute([$job,$id]);$this->audit->record('waf.deployment_queued','waf_deployment',$id,['server_id'=>$serverId]);return $id;}
 public function deploy(int $id):array{$q=$this->db->prepare('SELECT * FROM waf_deployments WHERE id=?');$q->execute([$id]);$d=$q->fetch()?:throw new RuntimeException('Despliegue WAF no encontrado.');$this->db->prepare("UPDATE waf_deployments SET status='running',started_at=NOW() WHERE id=?")->execute([$id]);try{$config=$this->render();$output=$d['server_id']?$this->ssh->wafTask((int)$d['server_id'],$config):$this->mainDeploy($id);$this->db->prepare("UPDATE waf_deployments SET status='completed',output=?,completed_at=NOW() WHERE id=?")->execute([substr($output,0,65535),$id]);return ['deployment_id'=>$id,'server_id'=>$d['server_id'],'status'=>'completed'];}catch(Throwable $e){$this->db->prepare("UPDATE waf_deployments SET status='failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($e->getMessage(),0,65535),$id]);throw $e;}}
 public function render():string{$s=$this->db->query('SELECT * FROM waf_settings WHERE id=1')->fetch();$out="Include /etc/modsecurity/modsecurity.conf\nSecRuleEngine ".(!$s['enabled']?'Off':($s['mode']==='blocking'?'On':'DetectionOnly'))."\nSecAuditEngine RelevantOnly\nSecAuditLogFormat JSON\nSecAuditLog /var/log/nginx/modsec_audit.log\nSecRequestBodyAccess On\nSecResponseBodyAccess Off\nInclude /etc/modsecurity/crs/crs-setup.conf\nSecAction \"id:100000,phase:1,pass,nolog,setvar:tx.paranoia_level={$s['paranoia_level']}\"\nSecAction \"id:100001,phase:1,pass,nolog,setvar:tx.inbound_anomaly_score_threshold={$s['inbound_threshold']},setvar:tx.outbound_anomaly_score_threshold={$s['outbound_threshold']}\"\nInclude /usr/share/modsecurity-crs/rules/*.conf\n";$targets=['uri'=>'REQUEST_URI','args'=>'ARGS','headers'=>'REQUEST_HEADERS','user_agent'=>'REQUEST_HEADERS:User-Agent'];$ops=['contains'=>'@contains','equals'=>'@streq','regex'=>'@rx'];foreach($this->db->query('SELECT * FROM waf_custom_rules WHERE active=1 ORDER BY rule_id') as $r){$pattern=addcslashes($r['pattern'],"\\\"");$deny=$r['action']==='block'?'deny,status:403':'pass';$msg=addcslashes($r['name'],"\\\"");$out.="SecRule {$targets[$r['target']]} \"{$ops[$r['operator']]} $pattern\" \"id:{$r['rule_id']},phase:2,$deny,log,msg:'$msg',tag:'ORIONX/CUSTOM'\"\n";}foreach($this->db->query('SELECT * FROM waf_exclusions WHERE active=1 ORDER BY id') as $x){$rid=300000+(int)$x['id'];$ctl=$x['rule_id']?'ctl:ruleRemoveById='.(int)$x['rule_id']:'ctl:ruleEngine=Off';if($x['ip'])$out.="SecRule REMOTE_ADDR \"@ipMatch {$x['ip']}\" \"id:$rid,phase:1,pass,nolog,$ctl\"\n";elseif($x['path_prefix']){$path=addcslashes($x['path_prefix'],"\\\"");$out.="SecRule REQUEST_URI \"@beginsWith $path\" \"id:$rid,phase:1,pass,nolog,$ctl\"\n";}}return $out;}
 public function importBarracuda(string $path):int{if(!is_file($path)||filesize($path)>10485760)throw new RuntimeException('Archivo inválido o mayor de 10 MB.');$fh=fopen($path,'rb');$q=$this->db->prepare("INSERT INTO waf_events(source,ip,rule_id,severity,method,path,message,action,occurred_at) VALUES('barracuda',?,?,?,?,?,?,?,?)");$count=0;while(($line=fgets($fh))!==false&&$count<50000){$line=trim($line);if($line==='')continue;$j=json_decode($line,true);$ip=is_array($j)?($j['client_ip']??$j['ip']??null):(preg_match('/\b(?:\d{1,3}\.){3}\d{1,3}\b/',$line,$m)?$m[0]:null);if($ip&&!filter_var($ip,FILTER_VALIDATE_IP))$ip=null;$q->execute([$ip,is_array($j)?(string)($j['rule_id']??''):null,is_array($j)?(string)($j['severity']??''):null,is_array($j)?(string)($j['method']??''):null,is_array($j)?(string)($j['path']??$j['url']??''):null,substr(is_array($j)?(string)($j['message']??$line):$line,0,4000),is_array($j)?(string)($j['action']??'observed'):'observed',date('Y-m-d H:i:s')]);$count++;}fclose($fh);$this->audit->record('waf.barracuda_logs_imported','waf',null,['count'=>$count]);return $count;}
 private function mainDeploy(int $id):string{$helper='/usr/local/sbin/orionx-waf-helper';if(!is_executable($helper))throw new RuntimeException('Actualiza primero el servidor principal para instalar el helper WAF.');$p=proc_open(['/usr/bin/sudo','-n',$helper,(string)$id],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,['PATH'=>'/usr/sbin:/usr/bin:/sbin:/bin'],['bypass_shell'=>true]);if(!is_resource($p))throw new RuntimeException('No se pudo iniciar el helper WAF.');$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);if($exit!==0)throw new RuntimeException(substr(trim($err?:$out),0,2000));return trim($out);}
}
