<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use App\Security\{Auth,DeviceCredentialCipher};use PDO;use RuntimeException;
final readonly class XuiImportService
{
 public function __construct(private PDO $db,private DeviceCredentialCipher $cipher,private TaskQueueService $queue,private AuditRepository $audit,private XuiNativeConverter $converter){}
 public function save(array $input):int{$host=trim((string)($input['host']??''));$port=(int)($input['port']??3306);$database=trim((string)($input['database']??''));$username=trim((string)($input['username']??''));$password=(string)($input['password']??'');$name=trim((string)($input['name']??'XUI One'));$prefix=trim((string)($input['prefix']??'xui_legacy__'));if(!filter_var($host,FILTER_VALIDATE_IP))throw new RuntimeException('La dirección de XUI debe ser una IP válida.');if($port<1||$port>65535)throw new RuntimeException('Puerto inválido.');foreach([$database,$username] as $value)if(!preg_match('/^[A-Za-z0-9_\-]{1,64}$/',$value))throw new RuntimeException('Base o usuario inválido.');if($password===''||!preg_match('/^[A-Za-z][A-Za-z0-9_]{0,39}$/',$prefix))throw new RuntimeException('Contraseña o prefijo inválido.');$s=$this->db->prepare('INSERT INTO xui_source_connections(name,host,port,database_name,username,password_ciphertext,table_prefix,created_by) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$name,$host,$port,$database,$username,$this->cipher->encrypt($password),$prefix,Auth::id()??0]);$id=(int)$this->db->lastInsertId();$this->audit->record('xui.connection_created','xui_source_connection',$id,['host'=>$host,'database'=>$database,'username'=>$username]);return $id;}
 public function test(int $id):array{$c=$this->connection($id);try{$source=$this->source($c);$tables=(int)$source->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_TYPE='BASE TABLE'")->fetchColumn();if($tables<1)throw new RuntimeException('La base no contiene tablas.');$grants=implode(' ',array_map('implode',$source->query('SHOW GRANTS')->fetchAll(PDO::FETCH_NUM)));if(preg_match('/\b(ALL PRIVILEGES|INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|FILE|SUPER|RELOAD|SHUTDOWN|PROCESS)\b/i',$grants))throw new RuntimeException('El usuario XUI no es de solo lectura. Crea uno únicamente con permiso SELECT.');$this->db->prepare("UPDATE xui_source_connections SET status='ready',last_tested_at=NOW(),last_error=NULL WHERE id=?")->execute([$id]);return ['tables'=>$tables];}catch(\Throwable $e){$this->db->prepare("UPDATE xui_source_connections SET status='error',last_tested_at=NOW(),last_error=? WHERE id=?")->execute([substr($e->getMessage(),0,1000),$id]);throw $e;}}
 public function queue(int $id,bool $replace=false):string{$c=$this->connection($id);if($c['status']!=='ready')throw new RuntimeException('Prueba primero la conexión de solo lectura.');$active=$this->db->prepare("SELECT 1 FROM jobs WHERE type='xui_import' AND status IN ('pending','reserved','running') LIMIT 1");$active->execute();if($active->fetchColumn())throw new RuntimeException('Ya existe una importación XUI en curso.');$job=$this->queue->enqueue('xui_import',['connection_id'=>$id,'replace'=>$replace],2,'xui-import-'.$id.'-'.time());$this->audit->record('xui.import_queued','xui_source_connection',$id,['job_id'=>$job,'replace'=>$replace]);return $job;}
 public function run(int $connectionId,bool $replace):array{$c=$this->connection($connectionId);$command=[PHP_BINARY,dirname(__DIR__,2).'/scripts/xui-import.php','--execute'];if($replace)$command[]='--replace';$env=array_merge($_ENV,['XUI_DB_HOST'=>$c['host'],'XUI_DB_PORT'=>(string)$c['port'],'XUI_DB_DATABASE'=>$c['database_name'],'XUI_DB_USERNAME'=>$c['username'],'XUI_DB_PASSWORD'=>$this->cipher->decrypt($c['password_ciphertext']),'XUI_IMPORT_PREFIX'=>$c['table_prefix']]);$pipes=[];$process=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2),$env,['bypass_shell'=>true]);if(!is_resource($process))throw new RuntimeException('No se pudo iniciar el importador.');$stdout=stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($process);if($exit!==0)throw new RuntimeException(substr($stderr?:$stdout,0,4000));$latest=$this->db->query('SELECT id,tables_copied,rows_copied FROM xui_imports ORDER BY id DESC LIMIT 1')->fetch();if($latest)$this->db->prepare('UPDATE xui_imports SET connection_id=? WHERE id=?')->execute([$connectionId,$latest['id']]);$native=$latest?$this->converter->convert((int)$latest['id'],(string)$c['table_prefix']):[];return ['import_id'=>(int)($latest['id']??0),'tables'=>(int)($latest['tables_copied']??0),'rows'=>(int)($latest['rows_copied']??0),'native'=>$native];}
 public function upload(array $file):int
 {
  if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!isset($file['tmp_name'],$file['name'],$file['size']))throw new RuntimeException('No se recibió un respaldo SQL válido.');
  $name=basename((string)$file['name']);$size=(int)$file['size'];$gzip=str_ends_with(strtolower($name),'.sql.gz');
  if(!$gzip&&!str_ends_with(strtolower($name),'.sql'))throw new RuntimeException('Solo se permiten archivos .sql o .sql.gz.');
  if($size<1||$size>5368709120)throw new RuntimeException('El respaldo debe medir entre 1 byte y 5 GB.');
  if(!is_uploaded_file((string)$file['tmp_name']))throw new RuntimeException('La subida HTTP no es válida.');
  $hash=hash_file('sha256',(string)$file['tmp_name']);if($hash===false)throw new RuntimeException('No se pudo calcular el checksum del respaldo.');
  $dir=dirname(__DIR__,2).'/storage/imports/xui';if(!is_dir($dir)&&!mkdir($dir,0770,true))throw new RuntimeException('No se pudo crear el almacenamiento de importaciones.');
  $this->db->beginTransaction();
  try{$this->db->prepare("INSERT INTO xui_sql_uploads(original_name,stored_path,size_bytes,sha256,status,created_by) VALUES(?,?,?,?,'uploaded',?)")->execute([$name,'',$size,$hash,Auth::id()??0]);$id=(int)$this->db->lastInsertId();$path=$dir.'/'.$id.($gzip?'.sql.gz':'.sql');if(!move_uploaded_file((string)$file['tmp_name'],$path))throw new RuntimeException('No se pudo almacenar el respaldo.');chmod($path,0640);$database='orionx_xui_upload_'.$id;$username='orionx_xui_'.$id;$password=bin2hex(random_bytes(24));$this->db->prepare("INSERT INTO xui_source_connections(name,host,port,database_name,username,password_ciphertext,table_prefix,status,created_by) VALUES(?, '127.0.0.1',3306,?,?,?,'xui_upload__','untested',?)")->execute(['SQL XUI #'.$id,$database,$username,$this->cipher->encrypt($password),Auth::id()??0]);$connectionId=(int)$this->db->lastInsertId();$this->db->prepare("UPDATE xui_sql_uploads SET connection_id=?,stored_path=?,status='uploaded',job_id=NULL WHERE id=?")->execute([$connectionId,$path,$id]);$this->audit->record('xui.sql_uploaded','xui_sql_upload',$id,['name'=>$name,'size'=>$size,'sha256'=>$hash,'processing'=>'direct']);$this->db->commit();return $id;}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();if(isset($path)&&is_file($path))unlink($path);throw $e;}
 }
 public function runUpload(int $id):array
 {
  $s=$this->db->prepare('SELECT u.*,c.database_name,c.username,c.password_ciphertext FROM xui_sql_uploads u JOIN xui_source_connections c ON c.id=u.connection_id WHERE u.id=?');$s->execute([$id]);$u=$s->fetch()?:throw new RuntimeException('Respaldo SQL no encontrado.');
  if($u['status']==='completed')throw new RuntimeException('Este respaldo ya fue importado.');
  if(in_array($u['status'],['restoring','importing'],true))throw new RuntimeException('Este respaldo ya se está procesando.');
  if(!empty($u['job_id'])){$cancel=$this->db->prepare("UPDATE jobs SET status='cancelled',finished_at=NOW(),error_message='Reemplazada por procesamiento directo' WHERE id=? AND status='pending'");$cancel->execute([$u['job_id']]);}
  $this->db->prepare("UPDATE xui_sql_uploads SET status='restoring',started_at=NOW(),error_message=NULL WHERE id=?")->execute([$id]);
  try{$control=dirname(__DIR__,2).'/storage/imports/xui/'.$id.'.json';$data=['database'=>$u['database_name'],'username'=>$u['username'],'password'=>$this->cipher->decrypt($u['password_ciphertext']),'dump'=>$u['stored_path']];if(file_put_contents($control,json_encode($data,JSON_THROW_ON_ERROR),LOCK_EX)===false)throw new RuntimeException('No se pudo preparar la restauración.');chmod($control,0600);$pipes=[];$process=proc_open(['/usr/bin/sudo','-n','/usr/local/sbin/orionx-xui-sql-helper',(string)$id],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,['PATH'=>'/usr/sbin:/usr/bin:/sbin:/bin'],['bypass_shell'=>true]);if(!is_resource($process))throw new RuntimeException('No se pudo iniciar la restauración aislada.');$stdout=stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($process);if($exit!==0||!str_contains($stdout,'XUI_SQL_RESTORE_OK'))throw new RuntimeException(substr($stderr?:$stdout,0,4000));$this->db->prepare("UPDATE xui_source_connections SET status='ready',last_tested_at=NOW(),last_error=NULL WHERE id=?")->execute([$u['connection_id']]);$this->db->prepare("UPDATE xui_sql_uploads SET status='importing' WHERE id=?")->execute([$id]);$result=$this->run((int)$u['connection_id'],false);$this->db->prepare("UPDATE xui_sql_uploads SET status='completed',completed_at=NOW() WHERE id=?")->execute([$id]);return $result;}catch(\Throwable $e){if(isset($control)&&is_file($control))unlink($control);$this->db->prepare("UPDATE xui_sql_uploads SET status='failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($e->getMessage(),0,65535),$id]);throw $e;}
 }
 private function connection(int $id):array{$s=$this->db->prepare('SELECT * FROM xui_source_connections WHERE id=?');$s->execute([$id]);return $s->fetch()?:throw new RuntimeException('Conexión XUI no encontrada.');}
 private function source(array $c):PDO{return new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',$c['host'],$c['port'],$c['database_name']),$c['username'],$this->cipher->decrypt($c['password_ciphertext']),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false,PDO::ATTR_TIMEOUT=>8]);}
}
