<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use App\Security\{Auth,DeviceCredentialCipher};use PDO;use RuntimeException;
final readonly class XuiImportService
{
 public function __construct(private PDO $db,private DeviceCredentialCipher $cipher,private TaskQueueService $queue,private AuditRepository $audit){}
 public function save(array $input):int{$host=trim((string)($input['host']??''));$port=(int)($input['port']??3306);$database=trim((string)($input['database']??''));$username=trim((string)($input['username']??''));$password=(string)($input['password']??'');$name=trim((string)($input['name']??'XUI One'));$prefix=trim((string)($input['prefix']??'xui_legacy__'));if(!filter_var($host,FILTER_VALIDATE_IP))throw new RuntimeException('La dirección de XUI debe ser una IP válida.');if($port<1||$port>65535)throw new RuntimeException('Puerto inválido.');foreach([$database,$username] as $value)if(!preg_match('/^[A-Za-z0-9_\-]{1,64}$/',$value))throw new RuntimeException('Base o usuario inválido.');if($password===''||!preg_match('/^[A-Za-z][A-Za-z0-9_]{0,39}$/',$prefix))throw new RuntimeException('Contraseña o prefijo inválido.');$s=$this->db->prepare('INSERT INTO xui_source_connections(name,host,port,database_name,username,password_ciphertext,table_prefix,created_by) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$name,$host,$port,$database,$username,$this->cipher->encrypt($password),$prefix,Auth::id()??0]);$id=(int)$this->db->lastInsertId();$this->audit->record('xui.connection_created','xui_source_connection',$id,['host'=>$host,'database'=>$database,'username'=>$username]);return $id;}
 public function test(int $id):array{$c=$this->connection($id);try{$source=$this->source($c);$tables=(int)$source->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_TYPE='BASE TABLE'")->fetchColumn();if($tables<1)throw new RuntimeException('La base no contiene tablas.');$grants=implode(' ',array_map('implode',$source->query('SHOW GRANTS')->fetchAll(PDO::FETCH_NUM)));if(preg_match('/\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE)\b/i',$grants))throw new RuntimeException('El usuario XUI no es de solo lectura. Crea uno con permiso SELECT.');$this->db->prepare("UPDATE xui_source_connections SET status='ready',last_tested_at=NOW(),last_error=NULL WHERE id=?")->execute([$id]);return ['tables'=>$tables];}catch(\Throwable $e){$this->db->prepare("UPDATE xui_source_connections SET status='error',last_tested_at=NOW(),last_error=? WHERE id=?")->execute([substr($e->getMessage(),0,1000),$id]);throw $e;}}
 public function queue(int $id,bool $replace=false):string{$c=$this->connection($id);if($c['status']!=='ready')throw new RuntimeException('Prueba primero la conexión de solo lectura.');$active=$this->db->prepare("SELECT 1 FROM jobs WHERE type='xui_import' AND status IN ('pending','reserved','running') LIMIT 1");$active->execute();if($active->fetchColumn())throw new RuntimeException('Ya existe una importación XUI en curso.');$job=$this->queue->enqueue('xui_import',['connection_id'=>$id,'replace'=>$replace],2,'xui-import-'.$id.'-'.time());$this->audit->record('xui.import_queued','xui_source_connection',$id,['job_id'=>$job,'replace'=>$replace]);return $job;}
 public function run(int $connectionId,bool $replace):array{$c=$this->connection($connectionId);$command=[PHP_BINARY,dirname(__DIR__,2).'/scripts/xui-import.php','--execute'];if($replace)$command[]='--replace';$env=array_merge($_ENV,['XUI_DB_HOST'=>$c['host'],'XUI_DB_PORT'=>(string)$c['port'],'XUI_DB_DATABASE'=>$c['database_name'],'XUI_DB_USERNAME'=>$c['username'],'XUI_DB_PASSWORD'=>$this->cipher->decrypt($c['password_ciphertext']),'XUI_IMPORT_PREFIX'=>$c['table_prefix']]);$pipes=[];$process=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2),$env,['bypass_shell'=>true]);if(!is_resource($process))throw new RuntimeException('No se pudo iniciar el importador.');$stdout=stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($process);if($exit!==0)throw new RuntimeException(substr($stderr?:$stdout,0,4000));$latest=$this->db->query('SELECT id,tables_copied,rows_copied FROM xui_imports ORDER BY id DESC LIMIT 1')->fetch();if($latest)$this->db->prepare('UPDATE xui_imports SET connection_id=? WHERE id=?')->execute([$connectionId,$latest['id']]);return ['import_id'=>(int)($latest['id']??0),'tables'=>(int)($latest['tables_copied']??0),'rows'=>(int)($latest['rows_copied']??0)];}
 private function connection(int $id):array{$s=$this->db->prepare('SELECT * FROM xui_source_connections WHERE id=?');$s->execute([$id]);return $s->fetch()?:throw new RuntimeException('Conexión XUI no encontrada.');}
 private function source(array $c):PDO{return new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',$c['host'],$c['port'],$c['database_name']),$c['username'],$this->cipher->decrypt($c['password_ciphertext']),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false,PDO::ATTR_TIMEOUT=>8]);}
}
