<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\AuditRepository;use App\Security\{DeviceCredentialCipher,LegacyPassword};use PDO;use RuntimeException;use Throwable;

final class XuiNativeConverter
{
 private int $run=0,$created=0,$updated=0,$conflicts=0;private array $maps=[];
 public function __construct(private readonly PDO $db,private readonly DeviceCredentialCipher $cipher,private readonly AuditRepository $audit,private readonly LegacyPassword $passwords){}

 public function convert(int $importId,string $prefix):array
 {
  if(!preg_match('/^[A-Za-z][A-Za-z0-9_]{0,39}$/',$prefix))throw new RuntimeException('Prefijo XUI inválido.');
  $this->assertTables($prefix,['lines','users','users_groups','bouquets','streams','streams_types','streams_categories','streams_series','streams_episodes','streams_servers','servers']);
  $this->db->prepare("INSERT INTO xui_conversion_runs(import_id) VALUES(?)")->execute([$importId]);$this->run=(int)$this->db->lastInsertId();
  try{
   $this->loadMaps($importId);$this->packages($importId,$prefix);$this->resellers($importId,$prefix);$this->lines($importId,$prefix);
   $this->categories($importId,$prefix);$this->epg($importId,$prefix);$this->servers($importId,$prefix);$this->streams($importId,$prefix);$this->series($importId,$prefix);$this->episodes($importId,$prefix);$this->bouquets($importId,$prefix);
   $this->lineAccess($prefix);$this->mag($importId,$prefix);$this->packageAccess($importId,$prefix);
   $summary=['created'=>$this->created,'updated'=>$this->updated,'conflicts'=>$this->conflicts];$status=$this->conflicts?'completed_with_conflicts':'completed';
   $this->db->prepare('UPDATE xui_conversion_runs SET status=?,entities_created=?,entities_updated=?,conflicts_count=?,summary=?,completed_at=NOW() WHERE id=?')->execute([$status,$this->created,$this->updated,$this->conflicts,json_encode($summary),$this->run]);
   $this->audit->record('xui.native_conversion_completed','xui_conversion_run',$this->run,$summary);return ['conversion_run_id'=>$this->run]+$summary;
  }catch(Throwable $e){$this->db->prepare("UPDATE xui_conversion_runs SET status='failed',entities_created=?,entities_updated=?,conflicts_count=?,error_message=?,completed_at=NOW() WHERE id=?")->execute([$this->created,$this->updated,$this->conflicts,substr($e->getMessage(),0,65535),$this->run]);throw $e;}
 }
 public function convertLinesOnly(int $importId,string $prefix):array
 {
  if(!preg_match('/^[A-Za-z][A-Za-z0-9_]{0,39}$/',$prefix)||!$this->table($prefix.'lines'))throw new RuntimeException('La copia XUI no contiene una tabla de líneas válida.');
  $this->db->prepare("INSERT INTO xui_conversion_runs(import_id) VALUES(?)")->execute([$importId]);$this->run=(int)$this->db->lastInsertId();
  try{$this->loadMaps($importId);$this->packages($importId,$prefix);$this->resellers($importId,$prefix);$this->lines($importId,$prefix);$summary=['created'=>$this->created,'updated'=>$this->updated,'conflicts'=>$this->conflicts,'scope'=>'lines'];$status=$this->conflicts?'completed_with_conflicts':'completed';$this->db->prepare('UPDATE xui_conversion_runs SET status=?,entities_created=?,entities_updated=?,conflicts_count=?,summary=?,completed_at=NOW() WHERE id=?')->execute([$status,$this->created,$this->updated,$this->conflicts,json_encode($summary),$this->run]);return ['conversion_run_id'=>$this->run]+$summary;}catch(Throwable $e){$this->db->prepare("UPDATE xui_conversion_runs SET status='failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($e->getMessage(),0,65535),$this->run]);throw $e;}
 }
 private function categories(int $i,string $p):void{foreach($this->rows($p.'streams_categories') as $r){$type=$this->contentType((string)$r['category_type']);$name=trim((string)$r['category_name']);if(!$type||$name===''){$this->conflict('category',(string)$r['id'],'unsupported_or_empty',['type'=>$r['category_type']]);continue;}$s=$this->db->prepare('INSERT INTO categories(name,type,active) VALUES(?,?,1) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),name=VALUES(name)');$s->execute([$name,$type]);$this->map($i,'category',(string)$r['id'],(int)$this->db->lastInsertId());}}
 private function epg(int $i,string $p):void{if(!$this->table($p.'epg'))return;foreach($this->rows($p.'epg') as $r){$name=trim((string)$r['epg_name'])?:'XUI EPG '.$r['id'];$source=trim((string)$r['epg_file'])?:'xui-import://epg/'.$r['id'];$this->db->prepare('INSERT INTO epg_sources(name,source_url,timezone,refresh_minutes,active,last_import_at) VALUES(?,?,\'UTC\',360,0,?)')->execute([$name,$source,$this->date($r['last_updated'])]);$this->map($i,'epg',(string)$r['id'],(int)$this->db->lastInsertId());}if(!$this->table($p.'epg_data'))return;$sql='INSERT IGNORE INTO epg_programmes(source_id,external_channel_id,starts_at,ends_at,title,description,metadata) SELECT m.native_id,d.channel_id,FROM_UNIXTIME(d.`start`),FROM_UNIXTIME(d.`end`),COALESCE(NULLIF(d.title,\'\'),\'Sin título\'),d.description,JSON_OBJECT(\'legacy_id\',d.id,\'language\',d.lang) FROM `'.$p.'epg_data` d JOIN xui_native_mappings m ON m.import_id=? AND m.entity_type=\'epg\' AND m.legacy_id=CAST(d.epg_id AS CHAR) WHERE d.`start`>0 AND d.`end`>d.`start` AND d.channel_id IS NOT NULL';$s=$this->db->prepare($sql);$s->execute([$i]);$this->created+=$s->rowCount();}
 private function servers(int $i,string $p):void{foreach($this->rows($p.'servers') as $r){if((int)$r['is_main']===1){$this->conflict('server',(string)$r['id'],'xui_main_not_balancer',['name'=>$r['server_name']]);continue;}$ip=filter_var($r['server_ip'],FILTER_VALIDATE_IP)?$r['server_ip']:null;$private=filter_var($r['private_ip'],FILTER_VALIDATE_IP)?$r['private_ip']:null;$s=$this->db->prepare("INSERT INTO servers(name,public_ip,private_ip,status,max_capacity,weight,priority,legacy_origin) VALUES(?,?,?,'pending',?,100,100,'xui_one')");$s->execute([trim((string)$r['server_name'])?:'XUI node '.$r['id'],$ip,$private,max(1,(int)$r['total_clients'])]);$this->created++;$this->map($i,'server',(string)$r['id'],(int)$this->db->lastInsertId());}}
 private function packages(int $i,string $p):void{if(!$this->table($p.'users_packages'))return;foreach($this->rows($p.'users_packages') as $r){$days=$this->days((int)$r['official_duration'],(string)$r['official_duration_in']);$cost=(int)round((float)$r['official_credits']*100);$s=$this->db->prepare('INSERT INTO packages(name,duration_days,credit_cost,active) VALUES(?,?,?,1) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)');$s->execute([trim((string)$r['package_name'])?:'XUI package '.$r['id'],$days,$cost]);$this->map($i,'package',(string)$r['id'],(int)$this->db->lastInsertId());}}
 private function resellers(int $i,string $p):void{$groups=[];foreach($this->rows($p.'users_groups') as $g)$groups[(int)$g['group_id']]=$g;$owners=[];foreach($this->rows($p.'users') as $r){$g=$groups[(int)$r['member_group_id']]??null;if(!$g)continue;$isReseller=(int)$g['is_reseller']===1;$isAdmin=(int)$g['is_admin']===1;if(!$isReseller&&!$isAdmin)continue;$email=filter_var($r['email'],FILTER_VALIDATE_EMAIL)?strtolower($r['email']):'xui-'.$r['id'].'@invalid.local';$password=(string)$r['password'];if($password===''){$this->conflict('panel_user',(string)$r['id'],'missing_password',[]);continue;}$s=$this->db->prepare("INSERT INTO users(name,email,password_hash,status) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)");$s->execute([trim((string)$r['username'])?:'XUI user '.$r['id'],$email,$this->passwords->forImport($password),(int)$r['status']===1?'active':'suspended']);$user=(int)$this->db->lastInsertId();$this->map($i,'panel_user',(string)$r['id'],$user);$slug=$isAdmin?'admin':'reseller';$role=$this->db->prepare('SELECT id FROM roles WHERE slug=?');$role->execute([$slug]);$role=$role->fetchColumn();if($role)$this->db->prepare('INSERT IGNORE INTO user_roles(user_id,role_id) VALUES(?,?)')->execute([$user,$role]);if(!$isReseller)continue;$balance=(int)round((float)$r['credits']*100);$this->db->prepare('INSERT INTO resellers(user_id,credit_balance,active,can_create_subresellers) VALUES(?,0,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),active=VALUES(active)')->execute([$user,(int)$r['status']===1,(int)$g['create_sub_resellers']===1]);$rid=(int)$this->db->lastInsertId();$uuid=substr(hash('sha256','xui-opening-'.$i.'-'.$r['id']),0,32);$actor=(int)$this->db->query('SELECT id FROM users ORDER BY id LIMIT 1')->fetchColumn();$ledger=$this->db->prepare('INSERT IGNORE INTO reseller_credit_transactions(reseller_id,amount,balance_before,balance_after,reason,actor_user_id,ip,uuid) VALUES(?,?,0,?, ?,?,NULL,?)');$ledger->execute([$rid,$balance,$balance,'Saldo inicial importado desde XUI One',$actor,$uuid]);if($ledger->rowCount())$this->db->prepare('UPDATE resellers SET credit_balance=? WHERE id=?')->execute([$balance,$rid]);$this->map($i,'reseller',(string)$r['id'],$rid);$owners[(string)$r['id']]=(string)$r['owner_id'];}foreach($owners as $legacy=>$owner){$parent=$this->maps['reseller'][$owner]??null;if($parent&&$parent!==($this->maps['reseller'][$legacy]??null))$this->db->prepare('UPDATE resellers SET parent_reseller_id=? WHERE id=?')->execute([$parent,$this->maps['reseller'][$legacy]]);}}
 private function streams(int $i,string $p):void{$types=[];$episodeStreams=[];foreach($this->rows($p.'streams_episodes') as $e)$episodeStreams[(int)$e['stream_id']]=true;foreach($this->rows($p.'streams_types') as $t)$types[(int)$t['type_id']]=strtolower((string)($t['type_key']?:$t['type_name']));foreach($this->rows($p.'streams') as $r){if(isset($episodeStreams[(int)$r['id']]))continue;$kind=$types[(int)$r['type']]??'';if(str_contains($kind,'series')||str_contains($kind,'episode'))continue;$type=(str_contains($kind,'movie')||str_contains($kind,'vod'))?'movie':((str_contains($kind,'live')||str_contains($kind,'radio'))?'live':null);if(!$type){$this->conflict('stream',(string)$r['id'],'unknown_stream_type',['xui_type'=>$kind]);continue;}$cat=$this->firstId($r['category_id']);$category=$cat!==null?($this->maps['category'][$cat]??null):null;$title=trim((string)$r['stream_display_name'])?:'XUI '.$type.' '.$r['id'];$id=$this->content($i,'stream',(string)$r['id'],$type,$title,$category,$r['tmdb_id']?:null,$r['movie_properties']?:null);$server=$this->streamServer($p,(int)$r['id']);if($type==='live'){$this->db->prepare('INSERT IGNORE INTO live_channels(content_item_id,logo_url,epg_channel_id,delivery_mode,transcode_enabled,assigned_server_id,monitoring_enabled) VALUES(?,?,?,?,?,?,1)')->execute([$id,$r['stream_icon']?:null,$r['channel_id']?:null,$this->onDemand($p,(int)$r['id'])?'on_demand':'always_on',(int)$r['enable_transcode'],$server]);foreach($this->list($r['stream_source']) as $n=>$url){if(!is_string($url)||trim($url)==='')continue;$this->db->prepare('INSERT INTO stream_sources(channel_id,name,source_url,priority,authorized,active,auto_restart) VALUES(?,?,?,?,1,1,?)')->execute([$id,'Fuente XUI '.($n+1),$url,($n+1)*10,$r['auto_restart']!==null]);}}else{$this->db->prepare('INSERT IGNORE INTO movies(content_item_id,release_year,rating,poster_url) VALUES(?,?,?,?)')->execute([$id,$r['year']?:null,$r['rating']?:null,$r['stream_icon']?:null]);$this->file($id,$server,$r['stream_source']);}}}
 private function series(int $i,string $p):void{foreach($this->rows($p.'streams_series') as $r){$cat=$this->firstId($r['category_id']);$category=$cat!==null?($this->maps['category'][$cat]??null):null;$meta=json_encode(['plot'=>$r['plot'],'cover'=>$r['cover'],'backdrop'=>$this->list($r['backdrop_path']),'genre'=>$r['genre'],'cast'=>$r['cast'],'director'=>$r['director'],'year'=>$r['year']],JSON_UNESCAPED_UNICODE);$this->content($i,'series',(string)$r['id'],'series',trim((string)$r['title'])?:'XUI series '.$r['id'],$category,$r['tmdb_id']?:null,$meta);}}
 private function episodes(int $i,string $p):void{foreach($this->rows($p.'streams_episodes') as $e){$series=$this->maps['series'][(string)$e['series_id']]??null;if(!$series){$this->conflict('episode',(string)$e['id'],'series_not_found',[]);continue;}$stream=$this->one($p.'streams','id',(int)$e['stream_id']);if(!$stream){$this->conflict('episode',(string)$e['id'],'stream_not_found',[]);continue;}$season=max(0,(int)$e['season_num']);$this->db->prepare('INSERT INTO series_seasons(series_id,season_number) VALUES(?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)')->execute([$series,$season]);$seasonId=(int)$this->db->lastInsertId();$title=trim((string)$stream['stream_display_name'])?:'Episode '.$e['episode_num'];$content=$this->content($i,'episode',(string)$e['id'],'episode',$title,$this->categoryOf($series),$stream['tmdb_id']?:null,$stream['movie_properties']?:null);$this->db->prepare('INSERT IGNORE INTO series_episodes(season_id,content_item_id,episode_number) VALUES(?,?,?)')->execute([$seasonId,$content,max(0,(int)$e['episode_num'])]);$this->file($content,$this->streamServer($p,(int)$e['stream_id']),$stream['stream_source']);}}
 private function lines(int $i,string $p):void{foreach($this->rows($p.'lines') as $r){$username=trim((string)$r['username']);if($username===''||(string)$r['password']===''){$this->conflict('line',(string)$r['id'],'missing_credentials',[]);continue;}$status=((int)$r['enabled']!==1||(int)$r['admin_enabled']!==1)?'suspended':(((int)$r['exp_date']>0&&(int)$r['exp_date']<time())?'expired':'active');$reseller=$this->maps['reseller'][(string)$r['member_id']]??null;$s=$this->db->prepare('INSERT INTO end_user_accounts(reseller_id,username,credential_ciphertext,status,expires_at,max_connections,is_trial,is_restreamer,allowed_ip,allowed_country,allowed_user_agent,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),reseller_id=VALUES(reseller_id),credential_ciphertext=VALUES(credential_ciphertext),status=VALUES(status),expires_at=VALUES(expires_at),max_connections=VALUES(max_connections),is_trial=VALUES(is_trial),is_restreamer=VALUES(is_restreamer),allowed_ip=VALUES(allowed_ip),allowed_country=VALUES(allowed_country),allowed_user_agent=VALUES(allowed_user_agent),notes=VALUES(notes)');$s->execute([$reseller,$username,$this->cipher->encrypt((string)$r['password']),$status,$this->date($r['exp_date']),max(1,(int)$r['max_connections']),(int)($r['is_trial']??0),(int)($r['is_restreamer']??0),$this->single($r['allowed_ips']),$r['forced_country']?:null,$this->single($r['allowed_ua']),trim((string)$r['admin_notes'].' '.(string)$r['reseller_notes'])?:null,$this->date($r['created_at'])??date('Y-m-d H:i:s')]);$account=(int)$this->db->lastInsertId();$this->map($i,'account',(string)$r['id'],$account);if($r['package_id']&&isset($this->maps['package'][(string)$r['package_id']]))$this->db->prepare('INSERT IGNORE INTO account_packages(account_id,package_id) VALUES(?,?)')->execute([$account,$this->maps['package'][(string)$r['package_id']]]);$this->grantBouquets($account,$this->list($r['bouquet']),$p);}}
 private function mag(int $i,string $p):void{if(!$this->table($p.'mag_devices'))return;$creator=(int)$this->db->query('SELECT id FROM users ORDER BY id LIMIT 1')->fetchColumn();foreach($this->rows($p.'mag_devices') as $r){$account=$this->maps['account'][(string)$r['user_id']]??null;$mac=strtoupper(trim((string)$r['mac']));if(!$account||!preg_match('/^([0-9A-F]{2}:){5}[0-9A-F]{2}$/',$mac)){$this->conflict('mag',(string)$r['mag_id'],'account_or_mac_invalid',[]);continue;}$this->db->prepare("INSERT INTO mag_devices(account_id,mac_hash,mac_ciphertext,status,last_ip,last_seen_at,created_by) VALUES(?,?,?,? ,?,?,?) ON DUPLICATE KEY UPDATE account_id=VALUES(account_id),status=VALUES(status)")->execute([$account,hash('sha256',$mac),$this->cipher->encrypt($mac),(int)$r['lock_device']?'blocked':'active',filter_var($r['ip'],FILTER_VALIDATE_IP)?$r['ip']:null,$this->date($r['last_active']),$creator]);}}
 private function packageAccess(int $i,string $p):void{if(!$this->table($p.'users_packages'))return;foreach($this->rows($p.'users_packages') as $r){$package=$this->maps['package'][(string)$r['id']]??null;if(!$package)continue;foreach($this->list($r['bouquets']) as $b){$row=$this->one($p.'bouquets','id',(int)$b);if(!$row)continue;foreach(['bouquet_channels'=>'stream','bouquet_movies'=>'stream','bouquet_series'=>'series'] as $field=>$map)foreach($this->list($row[$field]) as $legacy){$content=$this->maps[$map][(string)$legacy]??null;if($content)$this->db->prepare('INSERT IGNORE INTO package_content_items(package_id,content_item_id) VALUES(?,?)')->execute([$package,$content]);}}}}
 private function grantBouquets(int $account,array $bouquets,string $p):void{foreach($bouquets as $b){$row=$this->one($p.'bouquets','id',(int)$b);if(!$row)continue;foreach(['bouquet_channels'=>'stream','bouquet_movies'=>'stream','bouquet_series'=>'series'] as $field=>$map)foreach($this->list($row[$field]) as $legacy){$content=$this->maps[$map][(string)$legacy]??null;if($content)$this->db->prepare('INSERT IGNORE INTO account_content_items(account_id,content_item_id) VALUES(?,?)')->execute([$account,$content]);}}}
 private function content(int $i,string $map,string $legacy,string $type,string $title,?int $category,mixed $tmdb,?string $metadata):int{if(isset($this->maps[$map][$legacy]))return $this->maps[$map][$legacy];$slug='xui-'.$map.'-'.$legacy;$this->db->prepare("INSERT INTO content_items(type,category_id,title,slug,tmdb_id,metadata,status) VALUES(?,?,?,?,?,?, 'draft')")->execute([$type,$category,$title,$slug,$tmdb?:null,$this->jsonObject($metadata)]);$id=(int)$this->db->lastInsertId();$this->created++;$this->map($i,$map,$legacy,$id);return $id;}
 private function file(int $content,?int $server,mixed $source):void{$list=$this->list($source);$path=is_string($list[0]??null)?$list[0]:null;if(!$path||preg_match('#^https?://#i',$path))return;$mount='/';$name='XUI storage '.($server?:'main');$this->db->prepare("INSERT INTO storage_libraries(name,type,mount_path,content_type,active) VALUES(?,'mounted',?,'mixed',0) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)")->execute([$name,$mount]);$library=(int)$this->db->lastInsertId();$relative=ltrim(str_replace('\\','/',$path),'/');if($relative==='')return;$this->db->prepare("INSERT IGNORE INTO content_files(content_item_id,library_id,server_id,relative_path,public_id,status) VALUES(?,?,?,?,?,'pending')")->execute([$content,$library,$server,$relative,bin2hex(random_bytes(16))]);}
 private function streamServer(string $p,int $stream):?int{$s=$this->db->prepare('SELECT server_id FROM `'.$p.'streams_servers` WHERE stream_id=? ORDER BY parent_id IS NULL DESC,server_stream_id LIMIT 1');$s->execute([$stream]);$legacy=$s->fetchColumn();return $legacy===false?null:($this->maps['server'][(string)$legacy]??null);}
 private function onDemand(string $p,int $stream):bool{$s=$this->db->prepare('SELECT MAX(on_demand) FROM `'.$p.'streams_servers` WHERE stream_id=?');$s->execute([$stream]);return (int)$s->fetchColumn()===1;}
 private function categoryOf(int $content):?int{$s=$this->db->prepare('SELECT category_id FROM content_items WHERE id=?');$s->execute([$content]);$v=$s->fetchColumn();return $v===false||$v===null?null:(int)$v;}
 private function map(int $i,string $type,string $legacy,int $native):void{$this->db->prepare('INSERT INTO xui_native_mappings(import_id,entity_type,legacy_id,native_id) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE native_id=VALUES(native_id)')->execute([$i,$type,$legacy,$native]);$this->maps[$type][$legacy]=$native;}
 private function loadMaps(int $i):void{$s=$this->db->prepare('SELECT entity_type,legacy_id,native_id FROM xui_native_mappings WHERE import_id=?');$s->execute([$i]);foreach($s as $r)$this->maps[$r['entity_type']][$r['legacy_id']]=(int)$r['native_id'];}
 private function conflict(string $type,string $legacy,string $reason,array $details):void{$this->db->prepare('INSERT INTO xui_conversion_conflicts(run_id,entity_type,legacy_id,reason,details) VALUES(?,?,?,?,?)')->execute([$this->run,$type,$legacy,$reason,json_encode($details,JSON_UNESCAPED_UNICODE)]);$this->conflicts++;}
 private function rows(string $table):iterable{return $this->db->query('SELECT * FROM `'.$table.'`');}
 private function one(string $table,string $column,int $id):array|false{$s=$this->db->prepare('SELECT * FROM `'.$table.'` WHERE `'.$column.'`=? LIMIT 1');$s->execute([$id]);return $s->fetch();}
 private function table(string $name):bool{$s=$this->db->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->execute([$name]);return (bool)$s->fetchColumn();}
 private function assertTables(string $p,array $tables):void{foreach($tables as $t)if(!$this->table($p.$t))throw new RuntimeException('Falta la tabla XUI requerida: '.$t);}
 private function list(mixed $v):array{if(is_array($v))return $v;if(!is_string($v)||trim($v)==='')return [];$j=json_decode($v,true);if(is_array($j))return array_values($j);$u=@unserialize($v,['allowed_classes'=>false]);return is_array($u)?array_values($u):[];}
 private function firstId(mixed $v):?string{$l=$this->list($v);return isset($l[0])?(string)$l[0]:(is_numeric($v)?(string)$v:null);}
 private function single(mixed $v):?string{$l=$this->list($v);$x=$l[0]??null;return is_string($x)&&$x!==''?$x:null;}
 private function date(mixed $v):?string{return is_numeric($v)&&(int)$v>0?date('Y-m-d H:i:s',(int)$v):null;}
 private function days(int $n,string $unit):?int{if($n<1)return null;$u=strtolower($unit);return match(true){str_contains($u,'hour')=>max(1,(int)ceil($n/24)),str_contains($u,'month')=>$n*30,str_contains($u,'year')=>$n*365,default=>$n};}
 private function contentType(string $v):?string{$v=strtolower($v);return match(true){str_contains($v,'live')||str_contains($v,'radio')=>'live',str_contains($v,'movie')||str_contains($v,'vod')=>'movie',str_contains($v,'series')=>'series',default=>null};}
 private function bouquets(int $i,string $p):void{foreach($this->rows($p.'bouquets') as $r){$name=trim((string)($r['bouquet_name']??''))?:'XUI bouquet '.$r['id'];$this->db->prepare('INSERT INTO bouquets(name,active) VALUES(?,1) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)')->execute([$name]);$bouquet=(int)$this->db->lastInsertId();$this->map($i,'bouquet',(string)$r['id'],$bouquet);foreach(['bouquet_channels'=>'stream','bouquet_movies'=>'stream','bouquet_series'=>'series'] as $field=>$map)foreach($this->list($r[$field]??null) as $legacy){$content=$this->maps[$map][(string)$legacy]??null;if($content)$this->db->prepare('INSERT IGNORE INTO bouquet_content_items(bouquet_id,content_item_id) VALUES(?,?)')->execute([$bouquet,$content]);}}}
 private function lineAccess(string $p):void{foreach($this->rows($p.'lines') as $r){$account=$this->maps['account'][(string)$r['id']]??null;if($account)$this->grantBouquets($account,$this->list($r['bouquet']),$p);}}
 private function jsonObject(?string $v):?string{if(!$v)return null;$j=json_decode($v,true);return json_encode(is_array($j)?$j:['legacy'=>$v],JSON_UNESCAPED_UNICODE);}
}
