<div class="space-y-8">
 <div><h1 class="text-3xl font-bold">Usuarios administrativos</h1><p class="text-slate-400">Agrega usuarios y controla su acceso al panel.</p></div>
 <section id="agregar-usuario" class="scroll-mt-24 max-w-4xl mx-auto" x-data="{password:'',generate(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const bytes=new Uint32Array(16);crypto.getRandomValues(bytes);this.password=Array.from(bytes,n=>chars[n%chars.length]).join('')}}">
  <div class="flex justify-between items-center mb-4"><h2 class="text-xl font-bold">Agregar usuario</h2><a href="#manejar-usuarios" class="bg-blue-700 px-4 py-2 rounded text-sm">Manejar usuarios</a></div>
  <div class="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-xl"><div class="bg-blue-600 text-center font-bold p-3">▣ Detalles</div>
   <form method="post" class="p-6 md:p-8 space-y-5"><?=$csrf->field()?>
    <label class="grid md:grid-cols-[220px_1fr] items-center gap-3"><span>Nombre de usuario</span><input class="bg-slate-800 border border-slate-700 p-3 rounded" name="name" pattern="[A-Za-z0-9._-]{3,120}" maxlength="120" autocomplete="username" required></label>
    <label class="grid md:grid-cols-[220px_1fr] items-center gap-3"><span>Contraseña</span><span class="flex gap-2"><input x-model="password" class="flex-1 min-w-0 bg-slate-800 border border-slate-700 p-3 rounded" name="password" type="text" minlength="12" autocomplete="new-password" required><button type="button" @click="generate()" class="bg-slate-700 hover:bg-slate-600 px-4 rounded">Generar</button></span></label>
    <label class="grid md:grid-cols-[220px_1fr] items-center gap-3"><span>Correo <small class="text-slate-500">(opcional)</small></span><input class="bg-slate-800 border border-slate-700 p-3 rounded" name="email" type="email" autocomplete="email" placeholder="Puede dejarse vacío"></label>
    <label class="grid md:grid-cols-[220px_1fr] items-center gap-3"><span>Grupo de seguridad</span><select required name="group_id" class="bg-slate-800 border border-slate-700 p-3 rounded"><option value="">Seleccione un grupo</option><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=htmlspecialchars($g['name'])?><?=$g['is_reseller']?' · reseller':''?></option><?php endforeach?></select></label>
    <div class="flex justify-end pt-3"><button class="bg-blue-600 hover:bg-blue-500 px-6 py-3 rounded font-bold">Agregar usuario</button></div>
   </form>
  </div>
 </section>
 <section id="manejar-usuarios" class="scroll-mt-24"><h2 class="text-xl font-bold mb-3">Manejar usuarios</h2><div class="overflow-auto border border-slate-800 rounded-xl"><table class="w-full"><thead class="bg-slate-900 text-left text-slate-400"><tr><th class="p-3">ID</th><th>Nombre</th><th>Correo</th><th>Grupo</th><th>Estado</th><th class="p-3 text-right">Control</th></tr></thead><tbody><?php foreach($users as $u):?><tr class="border-t border-slate-800"><td class="p-3"><?=$u['id']?></td><td><?=htmlspecialchars($u['name'])?></td><td><?=$u['email']?htmlspecialchars($u['email']):'<span class="text-slate-500">Sin correo</span>'?></td><td><?=htmlspecialchars($u['group_names']?:'Sin grupo')?></td><td><?=htmlspecialchars($u['status'])?></td><td class="p-3"><div class="flex justify-end"><?php if($u['id']!==\App\Security\Auth::id()):?><form method="post" action="/users/status" onsubmit="return confirm('¿Cambiar el acceso de este usuario administrativo?')"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$u['id']?>"><input type="hidden" name="status" value="<?=$u['status']==='blocked'?'active':'blocked'?>"><button class="<?=$u['status']==='blocked'?'bg-blue-700':'bg-red-800'?> px-3 py-1 rounded"><?=$u['status']==='blocked'?'Activar':'Bloquear usuario'?></button></form><?php else:?><span class="text-xs text-slate-500">Sesión actual</span><?php endif?></div></td></tr><?php endforeach?></tbody></table></div></section>
</div>
