<?php $uploadStatus=['uploaded'=>'Listo para procesar','queued'=>'Pendiente de una instalación anterior','restoring'=>'Restaurando base aislada','importing'=>'Importando datos','completed'=>'Completado','failed'=>'Falló']; ?>
<div x-data="{resultModalOpen:false,resultRows:[]}" class="space-y-6"<?php if(array_filter($uploads,fn($u)=>in_array($u['status'],['restoring','importing'],true))):?> x-init="setTimeout(()=>location.reload(),5000)"<?php endif?>>
 <div><h1 class="text-3xl font-bold">Importar XUI One</h1><p class="text-slate-400">Copia íntegra y verificable desde un usuario MySQL de solo lectura.</p></div>
 <div class="rounded-xl border border-amber-700/50 bg-amber-950/30 p-4 text-sm"><strong>Antes de comenzar:</strong> crea y prueba un backup de XUI One. El panel nunca necesita permisos de escritura sobre la base original.</div>
 <section class="bg-slate-900 border border-slate-800 rounded-xl p-5"><div class="mb-4 rounded-lg border border-blue-800 bg-blue-950/40 p-4"><strong class="text-blue-300">Importación opcional</strong><p class="text-sm text-slate-300 mt-1">OrionX funciona como panel nuevo sin XUI. Si no subes un respaldo SQL ni agregas una conexión, este módulo no ejecuta ninguna importación ni modifica la base de datos.</p></div><h2 class="text-xl font-bold">Subir respaldo SQL de XUI</h2><p class="text-sm text-slate-400 mt-1">Solo al seleccionar y enviar un archivo .sql o .sql.gz se restaura en una base aislada y después se copian los datos compatibles a OrionX.</p><form method="post" action="/xui-import/upload" enctype="multipart/form-data" class="flex flex-wrap gap-3 mt-4"><?=$csrf->field()?><input required type="file" name="sql_dump" accept=".sql,.gz,application/sql,application/gzip" class="grow bg-slate-800 p-2 rounded"><button class="bg-emerald-700 px-4 py-2 rounded" onclick="this.disabled=true;this.form.submit()">Subir e importar</button></form></section>
 <?php if($uploads):?><section><h2 class="text-xl font-bold mb-3">Respaldos subidos</h2><div class="space-y-2"><?php foreach($uploads as $u):?><article class="bg-slate-900 border border-slate-800 rounded p-3"><div class="flex flex-wrap items-center gap-4"><div class="mr-auto"><strong><?=htmlspecialchars($u['original_name'])?></strong><div class="text-xs text-slate-400"><?=number_format((int)$u['size_bytes']/1048576,2)?> MB · SHA-256 <?=htmlspecialchars(substr($u['sha256'],0,16))?>… · subido <?=htmlspecialchars($u['created_at'])?></div><?php if($u['current_table']):?><div class="text-xs text-cyan-300 mt-1">Tabla <?=htmlspecialchars($u['current_table'])?>: <?=number_format((int)$u['current_copied_rows'])?> / <?=number_format((int)$u['current_source_rows'])?> filas · <?=$u['tables_copied']?> / <?=$u['tables_total']?> tablas</div><?php elseif($u['import_id']):?><div class="text-xs text-cyan-300 mt-1"><?=number_format((int)$u['rows_copied'])?> filas · <?=$u['tables_copied']?> / <?=$u['tables_total']?> tablas</div><?php endif?><?php if($u['error_message']):?><div class="text-xs text-red-400 mt-1"><?=htmlspecialchars(substr($u['error_message'],0,500))?></div><?php endif?></div><span class="<?=$u['status']==='failed'?'text-red-400':($u['status']==='completed'?'text-emerald-400':'text-amber-300')?>"><?=htmlspecialchars($uploadStatus[$u['status']]??$u['status'])?></span><?php if(in_array($u['status'],['uploaded','queued','failed'],true)):?><form method="post" action="/xui-import/upload/process" onsubmit="this.querySelector('button').disabled=true;this.querySelector('button').textContent='Procesando…'"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$u['id']?>"><button class="bg-emerald-700 px-3 py-2 rounded">Procesar ahora</button></form><?php endif?></div></article><?php endforeach?></div></section><?php endif?>
 <form method="post" action="/xui-import/connections" class="bg-slate-900 border border-slate-800 rounded-xl p-5 grid md:grid-cols-4 gap-4"><?=$csrf->field()?>
  <label><span>Nombre</span><input required name="name" value="Servidor XUI" class="w-full bg-slate-800 p-2 rounded"></label>
  <label><span>IP de MySQL XUI</span><input required name="host" placeholder="10.0.0.10" class="w-full bg-slate-800 p-2 rounded"></label>
  <label><span>Puerto</span><input required type="number" min="1" max="65535" name="port" value="3306" class="w-full bg-slate-800 p-2 rounded"></label>
  <label><span>Base de datos</span><input required name="database" value="xui" class="w-full bg-slate-800 p-2 rounded"></label>
  <label><span>Usuario solo lectura</span><input required name="username" value="xui_reader" class="w-full bg-slate-800 p-2 rounded"></label>
  <label><span>Contraseña</span><input required type="password" autocomplete="new-password" name="password" class="w-full bg-slate-800 p-2 rounded"></label>
  <label><span>Prefijo de copia</span><input required name="prefix" value="xui_legacy__" class="w-full bg-slate-800 p-2 rounded"></label>
  <button class="bg-cyan-700 rounded self-end p-2">Guardar conexión cifrada</button>
 </form>
 <section class="space-y-3"><h2 class="text-xl font-bold">Conexiones</h2><?php foreach($connections as $c):?><article class="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-wrap items-center gap-4"><div class="mr-auto"><strong><?=htmlspecialchars($c['name'])?></strong><div class="text-sm text-slate-400"><?=htmlspecialchars($c['host'])?>:<?=$c['port']?> / <?=htmlspecialchars($c['database_name'])?> · <?=htmlspecialchars($c['username'])?></div><div class="text-xs text-red-400"><?=htmlspecialchars($c['last_error']??'')?></div></div><span class="<?=$c['status']==='ready'?'text-emerald-400':'text-amber-400'?>"><?=htmlspecialchars($c['status'])?></span><form method="post" action="/xui-import/test"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$c['id']?>"><button class="bg-indigo-700 px-3 py-2 rounded">Probar conexión</button></form><?php if($c['status']==='ready'):?><form method="post" action="/xui-import/run" onsubmit="return confirm('Se copiará toda la base XUI en tablas aisladas. ¿Continuar?')"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$c['id']?>"><button class="bg-emerald-700 px-3 py-2 rounded">Importar todo</button></form><?php endif?></article><?php endforeach?></section>
 <section><h2 class="text-xl font-bold mb-3">Historial</h2><div class="overflow-x-auto border border-slate-800 rounded-xl"><table class="w-full text-sm"><thead class="bg-slate-900"><tr><th class="p-3 text-left">Origen</th><th>Estado</th><th>Tablas</th><th>Filas</th><th>Inicio</th><th></th></tr></thead><tbody><?php foreach($imports as $i):?><tr class="border-t border-slate-800"><td class="p-3"><?=htmlspecialchars($i['connection_name']??$i['source_database'])?></td><td class="text-center"><?=htmlspecialchars($i['status'])?></td><td class="text-center"><?=$i['tables_copied']?> / <?=$i['tables_total']?></td><td class="text-center"><?=number_format((int)$i['rows_copied'])?></td><td class="text-center"><?=$i['started_at']?></td><td class="p-3"><button @click="fetch('/xui-import/detail?id=<?=$i['id']?>').then(r=>r.json()).then(r=>{resultRows=Array.isArray(r.tables)?r.tables:[];resultModalOpen=true})" class="bg-slate-700 px-2 py-1 rounded">Detalle</button></td></tr><?php endforeach?></tbody></table></div></section>
 <?php if($conversions):?><section><h2 class="text-xl font-bold mb-3">Conversión nativa OrionX</h2><div class="space-y-2"><?php foreach($conversions as $c):?><article class="bg-slate-900 border border-slate-800 rounded p-3 flex flex-wrap gap-4"><strong>#<?=$c['id']?> · <?=htmlspecialchars($c['status'])?></strong><span>Creados: <?=number_format((int)$c['entities_created'])?></span><span>Conflictos: <?=number_format((int)$c['conflicts_count'])?></span><?php if($c['conflicts_count']):?><button @click="fetch('/xui-import/conflicts?id=<?=$c['id']?>').then(r=>r.json()).then(r=>{resultRows=Array.isArray(r.conflicts)?r.conflicts:[];resultModalOpen=true})" class="ml-auto bg-amber-700 px-2 py-1 rounded">Revisar conflictos</button><?php endif?></article><?php endforeach?></div></section><?php endif?>
 <section x-show="resultModalOpen" x-cloak style="display:none" class="bg-slate-900 border border-blue-800 rounded-xl p-5 overflow-auto"><div class="flex justify-between items-center gap-3"><h2 class="font-bold">Resultado de importación</h2><button type="button" @click="resultModalOpen=false" class="bg-slate-700 px-4 py-2 rounded">Cerrar resultado</button></div><div class="mt-3"><template x-for="(t,index) in resultRows" :key="index"><div class="grid grid-cols-4 gap-2 border-t border-slate-800 py-2 text-sm"><span x-text="t.source_table||t.entity_type||'Registro'"></span><span x-text="t.status||t.reason||''"></span><span x-text="t.copied_rows!==undefined?t.copied_rows+' / '+t.source_rows:''"></span><span class="truncate" x-text="t.checksum_sha256||t.error_message||''"></span></div></template><p x-show="resultRows.length===0" class="text-slate-500 py-3">No hay detalles disponibles.</p></div></section>
</div>
