<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title??'OrionX')?></title><style>[x-cloak]{display:none!important}</style><script src="https://cdn.tailwindcss.com"></script><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script><script src="https://unpkg.com/htmx.org@2.0.4"></script></head>
<body class="bg-slate-950 text-slate-100 min-h-screen"><header x-data="{mobile:false,menu:null}" @keydown.escape.window="menu=null" class="sticky top-0 z-40 border-b border-slate-700 bg-slate-900/95 backdrop-blur"><nav class="max-w-[1600px] mx-auto px-4"><div class="h-16 flex items-center gap-6"><a class="font-black text-xl tracking-wide text-cyan-400" href="/"><span class="text-white">ORION</span>X</a><?php if(\App\Security\Auth::id() && \App\Security\Auth::portal()==='admin'): ?><button @click="mobile=!mobile" class="md:hidden ml-auto border border-slate-700 px-3 py-2 rounded" aria-label="Menú">☰</button><div :class="mobile?'flex':'hidden'" class="absolute md:static top-16 left-0 right-0 md:flex flex-col md:flex-row bg-slate-900 md:bg-transparent border-b md:border-0 border-slate-700 md:items-stretch md:h-full p-3 md:p-0 shadow-xl md:shadow-none">
<?php $groups=[
 ['label'=>'Dashboard','icon'=>'⌁','href'=>'/','items'=>[]],
 ['label'=>'Servidores','icon'=>'▤','items'=>[['Servidores','/servers'],['Instalar y actualizar','/deployments'],['Certificados TLS','/certificates'],['Bibliotecas y discos','/libraries']]],
 ['label'=>'Usuarios','icon'=>'♟','items'=>[['Administradores','/users'],['Revendedores','/resellers'],['Dispositivos MAG','/mag-devices']]],
 ['label'=>'Líneas','icon'=>'▣','items'=>[['Cuentas finales','/accounts'],['Packages','/packages']]],
 ['label'=>'Contenido','icon'=>'▶','items'=>[['Canales en vivo','/live'],['Películas','/movies'],['EPG','/epg'],['Watch Folders','/libraries'],['Categorías','/categories']]],
 ['label'=>'Bouquets','icon'=>'◉','items'=>[['Administrar bouquets','/bouquets'],['Administrar packages','/packages']]],
 ['label'=>'Administración','icon'=>'⌕','items'=>[['Backups','/backups'],['Importar XUI','/xui-import'],['IP bloqueadas','/security/ip-blocks'],['Logs y auditoría','/logs']]],
 ];foreach($groups as $index=>$group):if(empty($group['items'])):?><a href="<?=$group['href']?>" class="flex items-center gap-2 px-4 py-3 md:py-0 hover:text-cyan-300 hover:bg-slate-800/70"><span class="text-slate-400"><?=$group['icon']?></span><?=$group['label']?></a><?php else:?><div class="relative" @click.outside="if(menu===<?=$index?>)menu=null"><button type="button" @click="menu=menu===<?=$index?>?null:<?=$index?>" class="w-full h-full flex items-center justify-between md:justify-start gap-2 px-4 py-3 md:py-0 hover:text-cyan-300 hover:bg-slate-800/70"><span class="text-slate-400"><?=$group['icon']?></span><?=$group['label']?><span class="text-[10px] text-slate-500">▼</span></button><div x-show="menu===<?=$index?>" x-cloak x-transition class="md:absolute left-0 top-full min-w-56 bg-slate-900 border border-slate-700 rounded-b-lg shadow-2xl overflow-hidden"><?php foreach($group['items'] as [$label,$url]):?><a @click="menu=null;mobile=false" href="<?=$url?>" class="block px-4 py-3 text-sm border-b border-slate-800 last:border-0 hover:bg-cyan-950 hover:text-cyan-300"><?=$label?></a><?php endforeach?></div></div><?php endif;endforeach?>
<form class="md:ml-auto flex items-center" method="post" action="/logout"><?=$csrf?->field()??(new \App\Core\Csrf())->field()?><button class="w-full md:w-auto text-left px-4 py-3 md:py-2 text-slate-300 hover:text-red-300">Salir</button></form></div><?php endif?></div></nav><div class="h-0.5 bg-gradient-to-r from-cyan-500 via-emerald-500 to-violet-600"></div></header><main class="max-w-7xl mx-auto p-4 md:p-6">
