<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#05070b"><title><?=htmlspecialchars($title??'OrionX')?></title><style>[x-cloak]{display:none!important}:root{color-scheme:dark;--orion-blue:#2563eb;--orion-blue-light:#60a5fa;--orion-black:#05070b}body{background:radial-gradient(circle at 50% -20%,#172554 0,#05070b 42%,#020305 100%)!important}.orion-logo{display:block;background:url('/assets/orionx-logo.png') no-repeat transparent}.orion-logo-nav{width:82px;height:54px;background-size:174px 95px;background-position:-35px -18px}.orion-logo-login{width:270px;height:180px;background-size:581px 317px;background-position:-116px -61px;margin:auto}.bg-cyan-500,.bg-cyan-600,.bg-cyan-700,.bg-cyan-800,.bg-indigo-600,.bg-indigo-700,.bg-violet-700,.bg-violet-800,.bg-fuchsia-700,.bg-fuchsia-800,.bg-teal-700{background-color:var(--orion-blue)!important}.text-cyan-300,.text-cyan-400,.text-cyan-500,.text-indigo-300,.text-indigo-400,.text-violet-400,.text-fuchsia-400,.text-orange-400{color:var(--orion-blue-light)!important}.border-cyan-900,.border-indigo-800,.border-violet-800{border-color:#1e3a8a!important}.from-violet-600,.from-emerald-500,.from-cyan-500,.from-amber-500{--tw-gradient-from:#2563eb var(--tw-gradient-from-position)!important;--tw-gradient-to:rgb(37 99 235/0) var(--tw-gradient-to-position)!important}.to-indigo-700,.to-teal-700,.to-blue-700,.to-orange-700{--tw-gradient-to:#111827 var(--tw-gradient-to-position)!important}button,a,input,select,textarea{transition:color .18s ease,border-color .18s ease,background-color .18s ease}input:focus,select:focus,textarea:focus{outline:2px solid #3b82f6;outline-offset:1px}</style><script src="https://cdn.tailwindcss.com"></script><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script><script src="https://unpkg.com/htmx.org@2.0.4"></script></head>
<body class="bg-black text-slate-100 min-h-screen"><header x-data="{mobile:false,menu:null}" @keydown.escape.window="menu=null" class="sticky top-0 z-40 border-b border-slate-700 bg-black/95 backdrop-blur"><nav class="max-w-[1600px] mx-auto px-4"><div class="h-16 flex items-center gap-5"><a class="orion-logo orion-logo-nav shrink-0" href="/" aria-label="OrionX"></a><?php if(\App\Security\Auth::id() && \App\Security\Auth::portal()==='admin'): ?><button @click="mobile=!mobile" class="md:hidden ml-auto border border-slate-700 px-3 py-2 rounded" aria-label="Menú">☰</button><div :class="mobile?'flex':'hidden'" class="absolute md:static top-16 left-0 right-0 md:flex flex-col md:flex-row bg-black md:bg-transparent border-b md:border-0 border-slate-700 md:items-stretch md:h-full p-3 md:p-0 shadow-xl md:shadow-none">
<?php $groups=[
 ['label'=>'Dashboard','icon'=>'⌁','href'=>'/','items'=>[]],
 ['label'=>'Servidores','icon'=>'▤','items'=>[['Servidores','/servers'],['Proxies','/servers/proxies'],['Mover contenido','/servers/move-content'],['Instalar y actualizar','/deployments'],['Certificados TLS','/certificates'],['Bibliotecas y discos','/libraries']]],
 ['label'=>'Usuarios','icon'=>'♟','items'=>[['Administradores','/users'],['Grupos de seguridad','/security/groups'],['Revendedores','/resellers']]],
 ['label'=>'Dispositivos MAG','icon'=>'▣','href'=>'/mag-devices','items'=>[]],
 ['label'=>'Líneas','icon'=>'▣','items'=>[['Cuentas finales','/accounts'],['Conexiones activas','/sessions'],['Packages','/packages']]],
 ['label'=>'Contenido','icon'=>'▶','items'=>[['Canales en vivo','/live'],['Ingest RTMP','/rtmp'],['Películas','/movies'],['Edición masiva VOD','/media/bulk'],['Eliminación masiva VOD','/media/delete'],['EPG','/epg'],['Watch Folders','/libraries'],['Categorías','/categories']]],
 ['label'=>'Bouquets','icon'=>'◉','items'=>[['Administrar bouquets','/bouquets'],['Administrar packages','/packages']]],
 ['label'=>'Administración','icon'=>'⌕','items'=>[['Ajustes generales','/settings'],['Seguridad de base de datos','/security/database'],['Backups','/backups'],['Importar XUI','/xui-import'],['IP bloqueadas','/security/ip-blocks'],['Logs y auditoría','/logs']]],
 ];foreach($groups as $index=>$group):if(empty($group['items'])):?><a href="<?=$group['href']?>" class="flex items-center gap-2 px-4 py-3 md:py-0 hover:text-cyan-300 hover:bg-slate-800/70"><span class="text-slate-400"><?=$group['icon']?></span><?=$group['label']?></a><?php else:?><div class="relative" @click.outside="if(menu===<?=$index?>)menu=null"><button type="button" @click="menu=menu===<?=$index?>?null:<?=$index?>" class="w-full h-full flex items-center justify-between md:justify-start gap-2 px-4 py-3 md:py-0 hover:text-cyan-300 hover:bg-slate-800/70"><span class="text-slate-400"><?=$group['icon']?></span><?=$group['label']?><span class="text-[10px] text-slate-500">▼</span></button><div x-show="menu===<?=$index?>" x-cloak x-transition class="md:absolute left-0 top-full min-w-56 bg-slate-900 border border-slate-700 rounded-b-lg shadow-2xl overflow-hidden"><?php foreach($group['items'] as [$label,$url]):?><a @click="menu=null;mobile=false" href="<?=$url?>" class="block px-4 py-3 text-sm border-b border-slate-800 last:border-0 hover:bg-cyan-950 hover:text-cyan-300"><?=$label?></a><?php endforeach?></div></div><?php endif;endforeach?>
<form class="md:ml-auto flex items-center" method="post" action="/logout"><?=$csrf?->field()??(new \App\Core\Csrf())->field()?><button class="w-full md:w-auto text-left px-4 py-3 md:py-2 text-slate-300 hover:text-red-300">Salir</button></form></div><?php endif?></div></nav><div class="h-0.5 bg-gradient-to-r from-blue-700 via-blue-400 to-white"></div></header><main class="max-w-7xl mx-auto p-4 md:p-6">
