<?php $e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$summary=[];foreach($counts as $c)$summary[(int)$c['id']]=$c;$hasResult=isset($result['live'])||isset($result['movie'])||isset($result['series']);?>
<div x-data="{source:'',target:'',confirmation:'',types:['live','movie','series'],data:<?=htmlspecialchars(json_encode($summary,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT),ENT_QUOTES)?>}" class="space-y-5">
 <div><h1 class="text-3xl font-bold">Mover contenido entre servidores</h1><p class="text-slate-400">Reasigna streaming, películas y series por separado sin mantenimiento ni corte de sesiones actuales.</p></div>
 <?php if($hasResult):?><div class="bg-emerald-950 border border-emerald-700 rounded-xl p-4 text-emerald-200">Movimiento completado: <?=number_format((int)($result['live']??0))?> streams, <?=number_format((int)($result['movie']??0))?> películas y <?=number_format((int)($result['series']??0))?> episodios.</div><?php endif?>
 <section class="grid md:grid-cols-2 xl:grid-cols-4 gap-3"><?php foreach($counts as $c):?><article class="bg-slate-900 border border-slate-800 rounded-xl p-4"><div class="flex justify-between"><strong><?=$e($c['name'])?></strong><span class="text-xs <?=$c['status']==='online'?'text-emerald-400':'text-amber-400'?>"><?=$e($c['status'])?></span></div><div class="text-xs text-slate-500"><?=$e($c['region']??'Sin región')?> · <?=$c['active_sessions']?> sesiones actuales</div><div class="grid grid-cols-3 gap-2 mt-3 text-center"><div class="bg-slate-800 rounded p-2"><b><?=$c['live_count']?></b><small class="block text-slate-500">Streaming</small></div><div class="bg-slate-800 rounded p-2"><b><?=$c['movie_count']?></b><small class="block text-slate-500">Movies</small></div><div class="bg-slate-800 rounded p-2"><b><?=$c['series_count']?></b><small class="block text-slate-500">Episodios</small></div></div></article><?php endforeach?></section>
 <form method="post" action="/servers/move-content" onsubmit="return confirm('¿Confirmas la reasignación masiva entre estos servidores?')" class="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-5"><?=$csrf->field()?>
  <div class="grid md:grid-cols-2 gap-4"><label>Servidor de origen<select required name="source_server_id" x-model="source" class="mt-1 w-full bg-slate-800 p-3 rounded"><option value="">Seleccionar origen</option><?php foreach($servers as $s):?><option value="<?=$s['id']?>"><?=$e($s['name'])?> · <?=$e($s['status'])?></option><?php endforeach?></select></label><label>Servidor de destino<select required name="target_server_id" x-model="target" class="mt-1 w-full bg-slate-800 p-3 rounded"><option value="">Seleccionar destino</option><?php foreach($servers as $s):?><option value="<?=$s['id']?>"><?=$e($s['name'])?> · <?=$e($s['status'])?></option><?php endforeach?></select></label></div>
  <fieldset><legend class="font-bold mb-3">Contenido que se moverá</legend><div class="grid md:grid-cols-3 gap-3"><label class="bg-blue-950/40 border border-blue-800 p-4 rounded-xl"><input type="checkbox" name="types[]" value="live" x-model="types"> <strong>Streaming en vivo</strong><span class="block text-sm text-slate-400 mt-1" x-text="source&&data[source]?data[source].live_count+' canales':'Selecciona origen'"></span></label><label class="bg-violet-950/40 border border-violet-800 p-4 rounded-xl"><input type="checkbox" name="types[]" value="movie" x-model="types"> <strong>Películas</strong><span class="block text-sm text-slate-400 mt-1" x-text="source&&data[source]?data[source].movie_count+' archivos':'Selecciona origen'"></span></label><label class="bg-fuchsia-950/40 border border-fuchsia-800 p-4 rounded-xl"><input type="checkbox" name="types[]" value="series" x-model="types"> <strong>Series y episodios</strong><span class="block text-sm text-slate-400 mt-1" x-text="source&&data[source]?data[source].series_count+' episodios':'Selecciona origen'"></span></label></div></fieldset>
  <div class="bg-amber-950/40 border border-amber-700 p-4 rounded-xl text-sm text-amber-100"><strong>Importante para VOD:</strong> cambia la asignación del servidor, pero no copia ni borra archivos físicos. La biblioteca debe estar montada y accesible en el destino. Las sesiones actuales continúan en su servidor y las nuevas usarán el destino.</div>
  <div class="grid md:grid-cols-[1fr_240px] gap-3 items-end"><label>Escribe MOVER para confirmar<input name="confirmation" x-model="confirmation" autocomplete="off" class="mt-1 w-full bg-slate-800 p-3 rounded" placeholder="MOVER"></label><button :disabled="!source||!target||source===target||types.length===0||confirmation!=='MOVER'" class="bg-blue-700 disabled:opacity-40 p-3 rounded font-bold">Mover contenido</button></div>
 </form>
</div>
