<div x-data="{fps:{},errors:{},newFp:'',newError:'',probing:false,probe(id,port,csrf){this.errors[id]='';fetch('/deployments/fingerprint',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(csrf)+'&server_id='+id+'&port='+port}).then(r=>r.json()).then(r=>{if(r.ok)this.fps[id]=r.fingerprint;else this.errors[id]=r.error})},probeNew(csrf){this.newError='';this.newFp='';this.probing=true;fetch('/deployments/fingerprint-host',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(csrf)+'&server_ip='+encodeURIComponent(this.$refs.newIp.value)+'&port='+encodeURIComponent(this.$refs.newPort.value)}).then(async r=>({ok:r.ok,data:await r.json()})).then(r=>{if(r.ok&&r.data.ok)this.newFp=r.data.fingerprint;else this.newError=r.data.error||'No se pudo verificar el servidor'}).catch(()=>this.newError='No se pudo conectar al servidor').finally(()=>this.probing=false)}}" class="space-y-6">
 <div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-3xl font-bold">Instalar balanceador</h1><p class="text-slate-400">Instalación remota como root por SSH 35222, con huella verificada, secretos cifrados y progreso auditable.</p></div><a href="/servers" class="bg-blue-700 px-4 py-2 rounded self-start">Manejar servidores</a></div>
 <section class="max-w-4xl mx-auto bg-slate-900 border border-slate-700 rounded-xl overflow-hidden shadow-2xl">
  <div class="bg-blue-600 px-5 py-3 text-center font-bold">✦ Detalles del balanceador</div>
  <form method="post" action="/deployments/install" class="p-6 md:p-8 space-y-5" onsubmit="return confirm('La instalación comenzará inmediatamente. ¿Continuar?')">
   <?=$csrf->field()?><input type="hidden" name="fingerprint" x-model="newFp">
   <label class="grid md:grid-cols-[180px_1fr] items-center gap-3"><span>Nombre del servidor</span><input required maxlength="120" name="name" class="bg-slate-800 border border-slate-700 rounded p-3" placeholder="Balanceador principal"></label>
   <div class="grid md:grid-cols-2 gap-5"><label class="grid md:grid-cols-[180px_1fr] items-center gap-3"><span>IP del servidor</span><input x-ref="newIp" required name="server_ip" class="bg-slate-800 border border-slate-700 rounded p-3" placeholder="203.0.113.10"></label><label class="grid grid-cols-[110px_1fr] items-center gap-3"><span>Puerto SSH</span><input x-ref="newPort" required type="number" min="1" max="65535" name="port" value="35222" class="bg-slate-800 border border-slate-700 rounded p-3"></label></div>
   <div class="grid md:grid-cols-2 gap-5"><label class="grid md:grid-cols-[180px_1fr] items-center gap-3"><span>Usuario SSH</span><input required readonly name="ssh_user" value="root" class="bg-slate-800 border border-slate-700 rounded p-3"></label><label class="grid grid-cols-[110px_1fr] items-center gap-3"><span>Contraseña</span><input type="password" name="ssh_password" autocomplete="new-password" class="bg-slate-800 border border-slate-700 rounded p-3" placeholder="Contraseña root"></label></div>
   <details class="border border-slate-700 rounded-lg"><summary class="cursor-pointer p-3 text-sm text-slate-300">Usar clave privada SSH en lugar de contraseña</summary><textarea name="private_key" class="m-3 mt-0 w-[calc(100%-1.5rem)] h-32 bg-slate-800 border border-slate-700 rounded p-3" placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"></textarea></details>
   <div class="flex flex-wrap items-center gap-3"><button type="button" @click="probeNew('<?=rawurlencode($csrf->token())?>')" :disabled="probing" class="bg-slate-700 hover:bg-slate-600 disabled:opacity-50 px-4 py-2 rounded" x-text="probing?'Verificando…':'Verificar conexión y huella'"></button><span x-show="newFp" class="text-emerald-400 text-sm">✓ Servidor verificado</span><span x-show="newError" x-text="newError" class="text-red-400 text-sm"></span></div>
   <div class="bg-amber-950/40 border border-amber-800 rounded-lg p-4 text-sm text-amber-100">La instalación se ejecutará en segundo plano. OrionX instalará los paquetes, configurará el agente y mostrará el progreso en el historial. Algunos ajustes del sistema pueden requerir reiniciar posteriormente, pero no se reiniciará sin autorización.</div>
   <div class="flex justify-end"><button :disabled="!newFp" class="bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:cursor-not-allowed px-6 py-3 rounded font-bold">Instalar balanceador</button></div>
  </form>
 </section>
 <h2 class="text-xl font-bold">Balanceadores registrados</h2>
 <div class="grid gap-5">
 <?php foreach($servers as $server):?>
  <article class="bg-slate-900 border border-slate-800 rounded-xl p-5">
   <div class="flex justify-between"><div><h2 class="text-xl font-bold"><?=htmlspecialchars($server['name'])?></h2><p class="text-slate-400"><?=htmlspecialchars($server['private_ip']?:$server['public_ip'])?> · <?=htmlspecialchars($server['region']??'')?></p></div><span class="<?=$server['ssh_configured']?'text-emerald-400':'text-amber-400'?>"><?=$server['ssh_configured']?'SSH configurado':'Pendiente SSH'?></span></div>
   <form method="post" action="/deployments/credentials" class="grid md:grid-cols-4 gap-3 mt-4">
    <?=$csrf->field()?><input type="hidden" name="server_id" value="<?=$server['id']?>">
    <input x-ref="port<?=$server['id']?>" type="number" min="1" max="65535" name="port" value="<?=$server['ssh_port']?:35222?>" class="bg-slate-800 p-2 rounded" placeholder="Puerto SSH">
    <input name="ssh_user" value="<?=htmlspecialchars($server['ssh_user']??'root')?>" class="bg-slate-800 p-2 rounded" placeholder="Usuario SSH (root permitido)">
    <button type="button" @click="probe(<?=$server['id']?>,$refs.port<?=$server['id']?>.value,'<?=rawurlencode($csrf->token())?>')" class="bg-indigo-700 rounded">Obtener huella</button>
    <input required name="fingerprint" x-model="fps[<?=$server['id']?>]" value="<?=htmlspecialchars($server['host_fingerprint']??'')?>" class="bg-slate-800 p-2 rounded" placeholder="Huella SSH confirmada">
    <textarea name="private_key" class="md:col-span-2 bg-slate-800 p-2 rounded" placeholder="Clave privada SSH (preferida)"></textarea>
    <input type="password" name="ssh_password" autocomplete="new-password" class="bg-slate-800 p-2 rounded" placeholder="Contraseña SSH alternativa">
    <button class="bg-cyan-700 rounded">Guardar conexión cifrada</button><p class="md:col-span-4 text-red-400" x-text="errors[<?=$server['id']?>]"></p>
   </form>
   <?php if(($server['legacy_origin']??null)==='xui_one'&&empty($server['cutover_authorized_at'])):?><div class="mt-4 rounded bg-amber-950/50 border border-amber-700 p-3 text-amber-200">Nodo XUI activo: instalación bloqueada para evitar cortar clientes. Prepare un balanceador OrionX paralelo.</div><?php elseif($server['ssh_configured']):?><div class="flex flex-wrap gap-3 mt-4"><form method="post" action="/deployments/run"><?=$csrf->field()?><input type="hidden" name="server_id" value="<?=$server['id']?>"><input type="hidden" name="type" value="install"><button class="bg-emerald-700 px-4 py-2 rounded">Instalar paquetes y agente</button></form><form method="post" action="/deployments/run"><?=$csrf->field()?><input type="hidden" name="server_id" value="<?=$server['id']?>"><input type="hidden" name="type" value="sync"><button class="bg-slate-700 px-4 py-2 rounded">Sincronizar configuración</button></form><form method="post" action="/deployments/run" onsubmit="return confirm('La actualización conservará el estado actual y las sesiones activas. ¿Continuar?')"><?=$csrf->field()?><input type="hidden" name="server_id" value="<?=$server['id']?>"><input type="hidden" name="type" value="update"><button class="bg-amber-600 px-4 py-2 rounded">Actualizar balanceador</button></form></div><?php endif?>
   <?php if(($server['legacy_origin']??null)==='xui_one'&&empty($server['cutover_authorized_at'])):?><form method="post" action="/deployments/cutover" class="mt-3" onsubmit="return confirm('Esto autoriza reemplazar XUI por OrionX en este mismo servidor. ¿Confirmas que el inventario está completo?')"><?=$csrf->field()?><input type="hidden" name="server_id" value="<?=$server['id']?>"><button class="bg-red-700 px-4 py-2 rounded">Autorizar reemplazo de XUI</button></form><?php endif?>
  </article>
 <?php endforeach?>
 </div>
 <section><h2 class="text-xl font-bold mb-3">Historial</h2><div class="space-y-2"><?php foreach($history as $deployment):?><article class="bg-slate-900 border border-slate-800 rounded p-3 flex justify-between"><div><strong><?=htmlspecialchars($deployment['server_name'])?></strong> · <?=htmlspecialchars($deployment['type'])?><div class="text-xs text-red-400"><?=htmlspecialchars($deployment['error_message']?substr($deployment['error_message'],0,300):'')?></div></div><div class="text-right"><?=htmlspecialchars($deployment['status'])?><div class="text-xs text-slate-500"><?=$deployment['created_at']?></div></div></article><?php endforeach?></div></section>
</div>
