<?php
declare(strict_types=1);
$config=parse_ini_file('/opt/media-balancer/agent.env',false,INI_SCANNER_RAW);if(!$config)exit(1);
function commandStatus(array $command):string{$p=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,null,['bypass_shell'=>true]);if(!is_resource($p))return 'error';foreach($pipes as $pipe){stream_get_contents($pipe);fclose($pipe);}return proc_close($p)===0?'ok':'error';}
function api(array $config,string $method,string $path,?array $payload=null):array{$raw=$payload===null?'':json_encode($payload,JSON_THROW_ON_ERROR);$timestamp=(string)time();$nonce=bin2hex(random_bytes(16));$canonical=$timestamp."\n".$nonce."\n".$method."\n".$path."\n".hash('sha256',$raw);$signature=hash_hmac('sha256',$canonical,$config['NODE_SECRET']);$curl=curl_init(rtrim($config['MAIN_URL'],'/').$path);curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_POSTFIELDS=>$raw===''?null:$raw,CURLOPT_HTTPHEADER=>['Content-Type: application/json','X-Node-Key: '.$config['NODE_KEY'],'X-Node-Timestamp: '.$timestamp,'X-Node-Nonce: '.$nonce,'X-Node-Signature: '.$signature],CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>20,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS]);$body=curl_exec($curl);$status=(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE);curl_close($curl);if($body===false||$status<200||$status>=300)throw new RuntimeException('API principal HTTP '.$status);return json_decode($body,true,32,JSON_THROW_ON_ERROR);}
$load=sys_getloadavg();$memory=file('/proc/meminfo',FILE_IGNORE_NEW_LINES)?:[];$mem=[];foreach($memory as $line)if(preg_match('/^(MemTotal|MemAvailable):\s+(\d+)/',$line,$m))$mem[$m[1]]=(int)$m[2];$ram=isset($mem['MemTotal'],$mem['MemAvailable'])&&$mem['MemTotal']>0?100*(1-$mem['MemAvailable']/$mem['MemTotal']):0;$diskTotal=disk_total_space('/');$diskFree=disk_free_space('/');$disk=$diskTotal?100*(1-$diskFree/$diskTotal):0;
$cpuCount=max(1,count(preg_grep('/^processor\s*:/',file('/proc/cpuinfo',FILE_IGNORE_NEW_LINES)?:[])));$heartbeat=['cpu'=>min(100,max(0,($load[0]??0)*100/$cpuCount)),'ram'=>$ram,'disk'=>$disk,'network_rx_bps'=>0,'network_tx_bps'=>0,'active_sessions'=>0,'active_streams'=>0,'connected_users'=>0,'installed_version'=>$config['AGENT_VERSION'],'ffmpeg_status'=>commandStatus(['/usr/local/bin/ffmpeg','-version']),'nginx_status'=>commandStatus(['/usr/bin/systemctl','is-active','--quiet','nginx']),'redis_status'=>commandStatus(['/usr/bin/systemctl','is-active','--quiet','redis-server']),'agent_status'=>'ok'];
api($config,'POST','/api/v1/internal/heartbeat',$heartbeat);
$pending=api($config,'GET','/api/v1/internal/certificates/pending');$request=$pending['data']??[];if(!empty($request['id'])&&preg_match('/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/',$request['domain'])&&filter_var($request['email'],FILTER_VALIDATE_EMAIL)){$p=proc_open(['/usr/bin/certbot','certonly','--nginx','--non-interactive','--agree-tos','--keep-until-expiring','--email',$request['email'],'--domains',$request['domain']],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,null,['bypass_shell'=>true]);$output='';$error='';if(is_resource($p)){$output=stream_get_contents($pipes[1]);$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$success=proc_close($p)===0;}else $success=false;$path='/etc/letsencrypt/live/'.$request['domain'].'/fullchain.pem';$cert=$success&&is_file($path)?openssl_x509_parse((string)file_get_contents($path)):false;api($config,'POST','/api/v1/internal/certificates/result',['request_id'=>(int)$request['id'],'success'=>$success,'certificate_path'=>$success?$path:null,'expires_at'=>$cert?date('Y-m-d H:i:s',$cert['validTo_time_t']):null,'error'=>$success?null:substr($error,0,1000)]);}
