#!/usr/bin/php
<?php
declare(strict_types=1);
$config=json_decode((string)file_get_contents($argv[1]??''),true,64,JSON_THROW_ON_ERROR);
$roots=array_values(array_filter(array_map(static function($p){$r=realpath((string)$p);return $r&&is_dir($r)&&$r!=='/'?rtrim(str_replace('\\','/',$r),'/'):null;},$config['allowed_roots']??[])));
if(!$roots)throw new RuntimeException('No hay raíces autorizadas disponibles.');
function inside(string $path,array $roots):bool{$p=str_replace('\\','/',$path);foreach($roots as $r)if($p===$r||str_starts_with($p,$r.'/'))return true;return false;}
function safeRoot(string $path,array $roots):string{$r=realpath($path);if($r===false||!is_dir($r)||!inside($r,$roots))throw new RuntimeException('Raíz no autorizada.');return $r;}
function probe(string $path):array{$p=proc_open(['/usr/local/bin/ffprobe','-v','error','-show_format','-show_streams','-of','json',$path],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,null,['bypass_shell'=>true]);if(!is_resource($p))return ['ok'=>false,'error'=>'ffprobe_unavailable'];$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);return $exit===0?['ok'=>true,'probe'=>json_decode($out,true)]:['ok'=>false,'error'=>substr(trim($err),0,300)];}
$mode=$config['mode']??'';$result=['ok'=>true,'mode'=>$mode,'items'=>[]];
if($mode==='inventory'){$root=safeRoot((string)$config['root'],$roots);$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isLink())continue;$link=str_replace('\\','/',$f->getPathname());$target=realpath($link);$valid=$target!==false&&is_file($target)&&inside($target,$roots);$result['items'][]=['link'=>$link,'target'=>$target?:null,'valid'=>$valid,'error'=>$valid?null:'Destino inexistente o fuera de biblioteca'];}}
elseif($mode==='scan'){$root=safeRoot((string)$config['root'],$roots);$extensions=['mkv','mp4','avi','mov','m4v','webm','ts'];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){$shown=str_replace('\\','/',$f->getPathname());$real=realpath($shown);if($real===false||!is_file($real)||!inside($real,$roots)||!in_array(strtolower(pathinfo($shown,PATHINFO_EXTENSION)),$extensions,true))continue;$check=probe($real);$result['items'][]=['path'=>$shown,'relative'=>ltrim(substr($shown,strlen(rtrim(str_replace('\\','/',$root),'/'))),'/'),'ok'=>$check['ok'],'size'=>filesize($real),'probe'=>$check['probe']??null,'error'=>$check['error']??null];}}
elseif($mode==='validate'){foreach($config['files']??[] as $file){$path=realpath((string)($file['path']??''));if($path===false||!is_file($path)||!inside($path,$roots)){$result['items'][]=['id'=>(int)$file['id'],'ok'=>false,'error'=>'missing_or_outside'];continue;}$check=probe($path);$result['items'][]=['id'=>(int)$file['id'],'ok'=>$check['ok'],'size'=>filesize($path),'probe'=>$check['probe']??null,'error'=>$check['error']??null];}}
elseif($mode==='apply_links'){foreach($config['links']??[] as $item){$link=str_replace('\\','/',(string)($item['link']??''));$target=realpath((string)($item['target']??''));$parent=realpath(dirname($link));$valid=$target!==false&&is_file($target)&&inside($target,$roots)&&$parent!==false&&inside($parent,$roots);if(!$valid){$result['items'][]=['id'=>(int)$item['id'],'ok'=>false,'error'=>'outside_or_missing'];continue;}if(file_exists($link)&&!is_link($link)){$result['items'][]=['id'=>(int)$item['id'],'ok'=>false,'error'=>'regular_file_exists'];continue;}if(is_link($link)&&!unlink($link)){$result['items'][]=['id'=>(int)$item['id'],'ok'=>false,'error'=>'unlink_failed'];continue;}$ok=symlink($target,$link);$result['items'][]=['id'=>(int)$item['id'],'ok'=>$ok,'error'=>$ok?null:'symlink_failed'];}}
else throw new RuntimeException('Operación no permitida.');
echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);
