server {
 listen 80 default_server;
 server_name _;
 server_tokens off;
 autoindex off;
 location ~ ^/vod/[A-Za-z0-9._-]+$ { include fastcgi_params; fastcgi_param SCRIPT_FILENAME /opt/media-balancer/media-gateway.php; fastcgi_pass unix:/run/php/php__PHP_VERSION__-fpm.sock; }
 location /__vod/ { internal; alias /srv/orionx/media/; sendfile on; aio threads; directio 8m; }
 location / { return 404; }
 location ~ /\. { deny all; }
}
