ALTER TABLE movies ADD COLUMN direct_source BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN direct_stream BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN native_frames BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN create_symlink BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN remove_subtitles BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN subtitle_location VARCHAR(1536) NULL,
 ADD COLUMN transcode_profile VARCHAR(120) NULL,
 ADD COLUMN target_container VARCHAR(20) NULL,
 ADD COLUMN process_movie BOOLEAN NOT NULL DEFAULT FALSE;
