CREATE TABLE IF NOT EXISTS server_proxies(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 server_id BIGINT UNSIGNED NULL,
 name VARCHAR(150) NOT NULL,
 scheme ENUM('http','https','socks5') NOT NULL DEFAULT 'http',
 host VARCHAR(255) NOT NULL,
 port SMALLINT UNSIGNED NOT NULL,
 username VARCHAR(255) NULL,
 password_ciphertext TEXT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(server_id) REFERENCES servers(id) ON DELETE CASCADE,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 UNIQUE(server_id,name),INDEX(server_id,active)
) ENGINE=InnoDB;
