<div x-data="{mac:null}" class="space-y-6">
 <div><h1 class="text-3xl font-bold">Dispositivos MAG</h1><p class="text-slate-400">Vincula una MAC a una cuenta y usa como portal la URL principal del panel.</p></div>
 <form method="post" action="/mag-devices" class="bg-slate-900 border border-slate-800 rounded-xl p-5 grid md:grid-cols-3 gap-4"><?=$csrf->field()?>
  <label><span>Cuenta</span><select required name="account_id" class="w-full bg-slate-800 p-2 rounded"><?php foreach($accounts as $a):?><option value="<?=$a['id']?>"><?=htmlspecialchars($a['username'])?> · <?=htmlspecialchars($a['status'])?></option><?php endforeach?></select></label>
  <label><span>Dirección MAC</span><input required name="mac" placeholder="00:1A:79:00:00:00" class="w-full bg-slate-800 p-2 rounded"></label>
  <button class="bg-cyan-700 rounded self-end p-2">Vincular MAG</button>
 </form>
 <div class="overflow-x-auto border border-slate-800 rounded-xl"><table class="w-full text-sm"><thead class="bg-slate-900"><tr><th class="p-3 text-left">Cuenta</th><th>Estado</th><th>Última IP</th><th>Última conexión</th><th class="p-3 text-right">Acciones</th></tr></thead><tbody><?php foreach($devices as $d):?><tr class="border-t border-slate-800"><td class="p-3"><?=htmlspecialchars($d['username'])?></td><td class="text-center"><?=htmlspecialchars($d['status'])?></td><td class="text-center"><?=htmlspecialchars($d['last_ip']??'—')?></td><td class="text-center"><?=htmlspecialchars($d['last_seen_at']??'Nunca')?></td><td class="p-3"><div class="flex justify-end gap-2"><button class="bg-indigo-700 px-2 py-1 rounded" @click="fetch('/mag-devices/reveal',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf=<?=rawurlencode($csrf->token())?>&id=<?=$d['id']?>'}).then(r=>r.json()).then(r=>mac=r.mac||r.error)">Ver MAC</button><form method="post" action="/mag-devices/status"><?=$csrf->field()?><input type="hidden" name="id" value="<?=$d['id']?>"><input type="hidden" name="status" value="<?=$d['status']==='active'?'blocked':'active'?>"><button class="bg-amber-700 px-2 py-1 rounded"><?=$d['status']==='active'?'Bloquear':'Activar'?></button></form></div></td></tr><?php endforeach?></tbody></table></div>
 <div x-show="mac" class="fixed inset-0 bg-black/70 grid place-items-center"><div class="bg-slate-900 p-6 rounded-xl"><code x-text="mac"></code><button @click="mac=null" class="block mt-4 bg-slate-700 px-4 py-2 rounded">Cerrar</button></div></div>
</div>
