<?php
declare(strict_types=1);
namespace App\Repositories;
use PDO;
final readonly class DashboardRepository
{
 public function __construct(private PDO $db){}
 public function data():array
 {
  $queries=['active_users'=>"SELECT COUNT(*) FROM end_user_accounts WHERE deleted_at IS NULL AND status='active' AND (expires_at IS NULL OR expires_at>NOW())",'expired_users'=>"SELECT COUNT(*) FROM end_user_accounts WHERE deleted_at IS NULL AND (status='expired' OR expires_at<=NOW())",'connections'=>"SELECT COUNT(*) FROM active_sessions WHERE disconnected_at IS NULL",'connected_users'=>"SELECT COUNT(DISTINCT account_id) FROM active_sessions WHERE disconnected_at IS NULL",'watching_live'=>"SELECT COUNT(DISTINCT s.content_item_id) FROM active_sessions s JOIN content_items c ON c.id=s.content_item_id AND c.type='live' WHERE s.disconnected_at IS NULL",'live_viewers'=>"SELECT COUNT(*) FROM active_sessions s JOIN content_items c ON c.id=s.content_item_id AND c.type='live' WHERE s.disconnected_at IS NULL",'watching_movies'=>"SELECT COUNT(DISTINCT s.content_item_id) FROM active_sessions s JOIN content_items c ON c.id=s.content_item_id AND c.type='movie' WHERE s.disconnected_at IS NULL",'movie_viewers'=>"SELECT COUNT(*) FROM active_sessions s JOIN content_items c ON c.id=s.content_item_id AND c.type='movie' WHERE s.disconnected_at IS NULL",'watching_series'=>"SELECT COUNT(DISTINCT ss.series_id) FROM active_sessions s JOIN series_episodes e ON e.content_item_id=s.content_item_id JOIN series_seasons ss ON ss.id=e.season_id WHERE s.disconnected_at IS NULL",'series_viewers'=>"SELECT COUNT(*) FROM active_sessions s JOIN content_items c ON c.id=s.content_item_id AND c.type='episode' WHERE s.disconnected_at IS NULL",'active_streams'=>"SELECT COUNT(*) FROM content_items WHERE type='live' AND status='active'",'stream_errors'=>"SELECT COUNT(*) FROM stream_sources WHERE status='failed'",'movies'=>"SELECT COUNT(*) FROM content_items WHERE type='movie'",'series'=>"SELECT COUNT(*) FROM content_items WHERE type='series'",'episodes'=>"SELECT COUNT(*) FROM content_items WHERE type='episode'",'resellers'=>"SELECT COUNT(*) FROM resellers WHERE active=1",'credits_consumed'=>"SELECT COALESCE(ABS(SUM(amount)),0) FROM reseller_credit_transactions WHERE amount<0",'servers_active'=>"SELECT COUNT(*) FROM servers WHERE status='online' AND last_heartbeat_at>DATE_SUB(NOW(),INTERVAL 90 SECOND)",'servers_problem'=>"SELECT COUNT(*) FROM servers WHERE status IN ('degraded','offline','quarantined') OR last_heartbeat_at<=DATE_SUB(NOW(),INTERVAL 90 SECOND)",'pending_jobs'=>"SELECT COUNT(*) FROM jobs WHERE status IN ('pending','reserved','running')",'storage_bytes'=>"SELECT COALESCE(SUM(size_bytes),0) FROM content_files WHERE status='available'",'security_alerts'=>"SELECT COUNT(*) FROM alerts WHERE status='open' AND severity='critical'"];$stats=[];foreach($queries as $key=>$sql)$stats[$key]=(int)$this->db->query($sql)->fetchColumn();
  $metrics=$this->db->query("SELECT COALESCE(AVG(m.cpu),0) cpu,COALESCE(AVG(m.ram),0) ram,COALESCE(AVG(m.disk),0) disk,COALESCE(SUM(m.network_rx_bps),0) network_rx_bps,COALESCE(SUM(m.network_tx_bps),0) network_tx_bps,COALESCE(SUM(m.active_sessions),0) reported_sessions,COALESCE(SUM(m.connected_users),0) connected_users FROM server_metrics m JOIN (SELECT server_id,MAX(id) id FROM server_metrics GROUP BY server_id) latest ON latest.id=m.id")->fetch()?:[];
  $servers=$this->db->query("SELECT s.id,s.name,s.region,s.status,s.max_capacity,s.installed_version,s.last_heartbeat_at,s.ffmpeg_status,s.nginx_status,s.redis_status,s.agent_status,s.quarantined_reason,COALESCE(m.cpu,0) cpu,COALESCE(m.ram,0) ram,COALESCE(m.disk,0) disk,COALESCE(m.network_rx_bps,0) network_rx_bps,COALESCE(m.network_tx_bps,0) network_tx_bps,COALESCE(m.active_sessions,0) active_sessions,COALESCE(m.active_streams,0) active_streams,COALESCE(m.connected_users,0) connected_users FROM servers s LEFT JOIN server_metrics m ON m.id=(SELECT MAX(mx.id) FROM server_metrics mx WHERE mx.server_id=s.id) ORDER BY FIELD(s.status,'quarantined','offline','degraded','pending','online'),s.name")->fetchAll();
  $security=$this->db->query("SELECT (SELECT COUNT(*) FROM blocked_ips WHERE active=1 AND (expires_at IS NULL OR expires_at>NOW())) blocked_ips,(SELECT COUNT(*) FROM nginx_security_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)) attacks_24h,(SELECT COALESCE(SUM(request_count),0) FROM nginx_security_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)) requests_24h")->fetch()?:[];$securityEvents=$this->db->query("SELECT ip,event_type,request_count,sample_path,action,created_at FROM nginx_security_events ORDER BY id DESC LIMIT 8")->fetchAll();
  return ['stats'=>$stats,'metrics'=>$metrics,'servers'=>$servers,'security'=>$security,'securityEvents'=>$securityEvents,'alerts'=>$this->db->query("SELECT severity,title,message,created_at FROM alerts WHERE status='open' ORDER BY FIELD(severity,'critical','warning','info'),id DESC LIMIT 8")->fetchAll(),'events'=>$this->db->query('SELECT action,entity_type,entity_id,created_at FROM audit_logs ORDER BY id DESC LIMIT 8')->fetchAll(),'jobs'=>$this->db->query("SELECT id,type,status,progress,worker,created_at FROM jobs WHERE status IN ('pending','running','failed') ORDER BY FIELD(status,'failed','running','pending'),priority,created_at DESC LIMIT 8")->fetchAll()];
 }
}
