<?php
declare(strict_types=1);
namespace App\Repositories;
use PDO;
final readonly class LiveChannelRepository
{
 public function __construct(private PDO $db){}
 public function all():array{return $this->db->query("SELECT c.id,c.title,c.status,l.channel_number,l.logo_url,l.delivery_mode,l.monitoring_enabled,l.runtime_status,l.online_since,l.last_down_at,l.restart_count,l.last_healthy_at,l.epg_channel_id,cat.name category,srv.name server_name,(SELECT COUNT(*) FROM active_sessions a WHERE a.content_item_id=c.id AND a.disconnected_at IS NULL) clients,(SELECT COUNT(*) FROM stream_sources s WHERE s.channel_id=c.id) source_count,(SELECT COUNT(*) FROM stream_failover_events f WHERE f.channel_id=c.id) failovers,(SELECT response_ms FROM stream_health_checks h JOIN stream_sources ss ON ss.id=h.source_id WHERE ss.channel_id=c.id ORDER BY h.id DESC LIMIT 1) response_ms,(SELECT width FROM stream_health_checks h JOIN stream_sources ss ON ss.id=h.source_id WHERE ss.channel_id=c.id ORDER BY h.id DESC LIMIT 1) width,(SELECT height FROM stream_health_checks h JOIN stream_sources ss ON ss.id=h.source_id WHERE ss.channel_id=c.id ORDER BY h.id DESC LIMIT 1) height,(SELECT video_codec FROM stream_health_checks h JOIN stream_sources ss ON ss.id=h.source_id WHERE ss.channel_id=c.id ORDER BY h.id DESC LIMIT 1) video_codec,(SELECT audio_codec FROM stream_health_checks h JOIN stream_sources ss ON ss.id=h.source_id WHERE ss.channel_id=c.id ORDER BY h.id DESC LIMIT 1) audio_codec,(SELECT bitrate_kbps FROM stream_health_checks h JOIN stream_sources ss ON ss.id=h.source_id WHERE ss.channel_id=c.id ORDER BY h.id DESC LIMIT 1) bitrate_kbps FROM content_items c JOIN live_channels l ON l.content_item_id=c.id LEFT JOIN categories cat ON cat.id=c.category_id LEFT JOIN servers srv ON srv.id=l.assigned_server_id WHERE c.type='live' ORDER BY COALESCE(l.channel_number,999999),c.title")->fetchAll();}
 public function sources(int $channelId):array{$s=$this->db->prepare('SELECT id,name,priority,authorized,active,status,last_checked_at,consecutive_failures FROM stream_sources WHERE channel_id=? ORDER BY priority,id');$s->execute([$channelId]);return $s->fetchAll();}
 public function categories():array{return $this->db->query("SELECT id,name FROM categories WHERE type='live' AND active=1 ORDER BY name")->fetchAll();}
 public function servers():array{return $this->db->query("SELECT id,name FROM servers WHERE status IN ('pending','online') ORDER BY name")->fetchAll();}
}
